// Generated by Java* Fuzzer test generator (1.0.001). Sun Mar 29 19:53:58 2026
public class Test0098 {

    public static final int N = 128;

    public static volatile long instanceCount=6219505178506440366L;
    public int iFld=49124;
    public short sFld=-14326;
    public static long lFld=1387292163L;
    public static boolean bFld=true;
    public static int iFld1=-9;
    public int iFld2=-21;
    public char cFld=11110;
    public static int iArrFld1[]=new int[N];
    public static float fArrFld[]=new float[N];

    static {
        FuzzerUtils.init(Test0098.iArrFld1, -50368);
        FuzzerUtils.init(Test0098.fArrFld, 68.59F);
    }

    public static long vMeth_check_sum = 0;
    public static long iMeth_check_sum = 0;

    public static int iMeth(int i3, int i4) {

        long meth_res = 0;
        int i5=-34806;
        String str1="two", strArr2[]=new String[N];

        FuzzerUtils.init(strArr2, "four");

        i5 = 119;
        do {
            str1 = (Cls.strMeth(i5, false) + str1);
            strArr2[i5 + 1] = str1;
        } while (--i5 > 0);
        meth_res = i3 + i4 + i5 + str1.length() + FuzzerUtils.checkSum(strArr2);
        iMeth_check_sum += meth_res;
        return (int)meth_res;
    }

    public void vMeth(String str, char c) {

        long meth_res = 0;
        double d=-88.56231, d1=15.96434;
        int i=-19573, i1=-115, i2=-5, i17=8, i18=19863, i19=8, i20=98, i21=17, i22=57, i23=-161, i24=42, i25=43,
            iArr[]=new int[N];
        float f=90.679F, fArr1[]=new float[N];
        long l2=-122L;
        Cls O=new Cls(), O1=new Cls(), O7=new Cls(), O8=new Cls(), O9=new Cls(), O10=new Cls(), O11=new Cls();

        FuzzerUtils.init(iArr, 96);
        FuzzerUtils.init(fArr1, 9.839F);

        for (d = (double) (4); 100 > d; d += 3) {
            for (i1 = (int) (47); 1 < i1; i1--) {
                iArr[(int)(d - 1)] += iMeth(i, iFld);
                Cls.fFld /= (float)(i1 | 1);
            }
            synchronized (O7) {
                Cls.dFld -= (double)64151;
                i18 = 1;
                do {
                    i17 = i2;
                    fArr1[(int)(d)] = (float)c;
                } while ((i18 += 3) < 47);
                i += i18;
                i = -92;
            }
            try {
                Cls.instanceCount += (long)i;
                switch ((int)((d % 10) + 13)) {
                    case 13:
                        Cls.fFld += (float)i;
                        synchronized (O8) {
                            try {
                                for (f = (float) (1); 47 > f; ++f) {
                                    if (true) break;
                                    Test0098.lFld = (long)i18;
                                    i /= i17;
                                    if (i != 0) {
                                        vMeth_check_sum += str.length() + (int)c + Double.doubleToLongBits(d) + i + i1
                                            + i2 + i17 + i18 + i19 + Float.floatToIntBits(f) + i20 + i21 + i22 + i23 +
                                            i24 + i25 + Double.doubleToLongBits(d1) + l2 + FuzzerUtils.checkSum(iArr) +
                                            Double.doubleToLongBits(FuzzerUtils.checkSum(fArr1)) +
                                            FuzzerUtils.checkSum(O) + FuzzerUtils.checkSum(O1) +
                                            FuzzerUtils.checkSum(O7) + FuzzerUtils.checkSum(O8) +
                                            FuzzerUtils.checkSum(O9) + FuzzerUtils.checkSum(O10) +
                                            FuzzerUtils.checkSum(O11);
                                        return;
                                    }
                                    if (Test0098.bFld) continue;
                                    iArr[(int)(f)] *= i2;
                                }
                                try {
                                    iArr[(int)(d + 1)] = (-51851 / i19);
                                    i17 = (i18 / i20);
                                    iArr[(int)(d)] = (i2 / i1);
                                } catch (ArithmeticException a_e) {}
                                switch ((((177 >>> 1) % 1) * 5) + 15) {
                                    case 18:
                                        i21 = 47;
                                        do {
                                            for (i22 = (int) (1); i22 > 1; i22 -= 2) {
                                                Cls.instanceCount -= (long)Cls.byFld;
                                                switch ((i21 % 3) + 33) {
                                                    case 33:
                                                        switch (((i21 % 2) * 5) + 30) {
                                                            case 38:
                                                                i19 += i1;
                                                                for (i24 = (int) (d); i24 < 1; i24 += 3) {
                                                                    i19 >>= -108;
                                                                    if (false) continue;
                                                                    i23 >>= i22;
                                                                    i25 *= i17;
                                                                    i = (int)Cls.fFld;
                                                                    i20 -= i22;
                                                                }
                                                                Test0098.iFld1 = i24;
                                                                break;
                                                            case 31:
                                                                switch ((int)((d % 6) + 29)) {
                                                                    case 29:
                                                                        d1 = 1;
                                                                        do {
                                                                            switch (((i22 >>> 1) % 1) + 30) {
                                                                                case 30:
                                                                                    l2 = 1;
                                                                                    while ((l2 -= 3) > 0) {
                                                                                        str = str;
                                                                                    }
                                                                                    break;
                                                                            }
                                                                        } while (--d1 > 0);
                                                                        break;
                                                                    case 30:
                                                                        Cls.instanceCount += (long)i20;
                                                                        break;
                                                                    case 31:
                                                                        if (true) break;
                                                                        break;
                                                                    case 32:
                                                                        i += -2;
                                                                    case 33:
                                                                        break;
                                                                    case 34:
                                                                        Cls.fFld -= (float)i17;
                                                                        break;
                                                                }
                                                                break;
                                                            default:
                                                                iArr[i22 - 1] *= (int)3339798720L;
                                                        }
                                                    case 34:
                                                        Test0098.lFld *= (long)9;
                                                        break;
                                                    case 35:
                                                        // Resetting String variable to a short value to prevent OOM
                                                        str = "";
                                                        str += str;
                                                        break;
                                                }
                                            }
                                        } while (--i21 > 0);
                                        break;
                                    default:
                                }
                            }
                            catch (ArithmeticException exc18) {
                            }
                        }
                    case 14:
                        if (Test0098.bFld) continue;
                        break;
                    case 15:
                        break;
                    case 16:
                        iFld = i20;
                    case 17:
                        // Resetting String variable to a short value to prevent OOM
                        str = "";
                        str += str;
                    case 18:
                        break;
                    case 19:
                        Cls.fFld = (float)l2;
                        break;
                    case 20:
                        Test0098.lFld += (long)i19;
                        break;
                    case 21:
                        iArr[(int)(d + 1)] += iFld2;
                        break;
                    case 22:
                        str = str;
                        break;
                    default:
                        i >>>= iFld2;
                }
            }
            catch (NegativeArraySizeException exc19) {
            }
        }
        vMeth_check_sum += str.length() + (int)c + Double.doubleToLongBits(d) + i + i1 + i2 + i17 + i18 + i19 +
            Float.floatToIntBits(f) + i20 + i21 + i22 + i23 + i24 + i25 + Double.doubleToLongBits(d1) + l2 +
            FuzzerUtils.checkSum(iArr) + Double.doubleToLongBits(FuzzerUtils.checkSum(fArr1)) + FuzzerUtils.checkSum(O)
            + FuzzerUtils.checkSum(O1) + FuzzerUtils.checkSum(O7) + FuzzerUtils.checkSum(O8) + FuzzerUtils.checkSum(O9)
            + FuzzerUtils.checkSum(O10) + FuzzerUtils.checkSum(O11);
    }

    public void mainTest0098(String[] strArr1) {

        long meth_res = 0;
        int i26=14, i27=8, i28=-98, i29=-13, i30=47966, i31=-127, i32=-8, i33=-25110, i34=-4, i35=-11, i36=-5,
            i37=9267, i38=-65, i39=22912, i41=9, i42=-44, i43=0, i44=-54320;
        double d2=0.22743, d3=-59.79000, dArr[]=new double[N];
        String str3="one";
        byte byArr[]=new byte[N];
        long lArr1[]=new long[N];
        char cArr[][]=new char[N][N];
        Cls O12=new Cls(), O13=new Cls(), O14=new Cls(), O15=new Cls(), O16=new Cls(), O17=new Cls(), O18=new Cls(),
            O19=new Cls(), O20=new Cls(), O21=new Cls();

        FuzzerUtils.init(dArr, 103.33864);
        FuzzerUtils.init(byArr, (byte)-33);
        FuzzerUtils.init(lArr1, 39625L);
        FuzzerUtils.init(cArr, (char)31711);

        try {
            iFld = Math.max(iFld, iFld);
            vMeth("three", (char)(cFld));
            for (i26 = (int) (3); i26 < 94; i26 += 3) {
            }
        }
        catch (ArithmeticException exc20) {
            i27 /= (int)(i27 | 1);
        }
        for (i28 = (int) (4); 110 > i28; i28 += 3) {
            i27 *= (int)Cls.byFld;
            d2 = 1;
            while (++d2 < i28) {
                Cls.fFld += (float)-10;
                i30 = 6;
                while (--i30 > 0) {
                    for (i31 = (int) (1); i31 < 1; i31 += 3) {
                    }
                    Cls.fFld += (float)Test0098.iFld1;
                }
                i29 = (int)Cls.instanceCount;
                Test0098.instanceCount %= (long)26712;
                for (i33 = (int) (6); i33 > 1; i33 -= 2) {
                    synchronized (O16) {
                        iFld2 &= -49554;
                        try {
                            i35 = 1;
                            do {
                                if (Test0098.bFld) break;
                                switch ((i33 % 9) + 14) {
                                    case 14:
                                        Cls.instanceCount = (long)51;
                                        Test0098.iArrFld1[i35 - 1] = iFld2;
                                        Test0098.fArrFld[i35 - 1] += (float)cFld;
                                        Test0098.instanceCount -= (long)i33;
                                        Cls.fFld = (float)i26;
                                        Test0098.bFld = Test0098.bFld;
                                        str3 = str3;
                                        break;
                                    case 15:
                                        Test0098.iArrFld1[i35] *= (int)d3;
                                        for (i36 = (int) (1); i36 < ((long)1 + (long)128); ++i36) {
                                            Cls.instanceCount += Test0098.lFld;
                                            Test0098.bFld = Test0098.bFld;
                                            cFld <<= (char)iFld;
                                        }
                                        break;
                                    case 16:
                                    case 17:
                                        Cls.fFld -= (float)iFld2;
                                        i27 *= 112;
                                        Cls.fFld -= (float)Test0098.instanceCount;
                                        switch ((int)(((d2 % 1) * 5) + 126)) {
                                            case 128:
                                                if (Test0098.bFld) break;
                                                synchronized (O18) {
                                                    int i40=-238;
                                                    switch ((((i37 >>> 1) % 1) * 5) + 105) {
                                                        case 109:
                                                            Cls.fFld = (float)i32;
                                                            i39 = 1;
                                                            do {
                                                                iFld2 += (int)Test0098.instanceCount;
                                                                Test0098.instanceCount = (long)iFld;
                                                            } while (++i39 < 1);
                                                            Test0098.iArrFld1[i33] = i35;
                                                            Test0098.lFld = (long)Cls.byFld;
                                                            Cls.dFld = (double)i28;
                                                            Test0098.instanceCount *= (long)-66;
                                                            Cls.fFld = (float)-31770;
                                                            Test0098.bFld = true;
                                                            break;
                                                        default:
                                                            sFld += (short)i29;
                                                            switch ((i35 % 10) + 24) {
                                                                case 24:
                                                                    Test0098.bFld = Test0098.bFld;
                                                                case 25:
                                                                    Cls.instanceCount -= (long)-8;
                                                                    i29 = (int)Test0098.instanceCount;
                                                                    Test0098.bFld = true;
                                                                    Test0098.iFld1 = i33;
                                                                    str3 = str3;
                                                                    break;
                                                                case 26:
                                                                    i27 += i36;
                                                                    switch (((i40 >>> 1) % 1) + 123) {
                                                                        case 123:
                                                                            Cls.instanceCount -= (long)Test0098.iFld1;
                                                                            i29 = (int)Test0098.lFld;
                                                                            Cls.instanceCount = (long)4;
                                                                            if (false) continue;
                                                                            for (i41 = (int) ((long)1 + (long)128); i41
                                                                                > d2; --i41) {
                                                                                Test0098.iFld1 = i33;
                                                                                switch (((i34 >>> 1) % 6) + 123) {
                                                                                    case 123:
                                                                                        Cls.fFld *= (float)166;
                                                                                        i32 += iFld2;
                                                                                        i40 -= i39;
                                                                                        dArr[i41 - 1] =
                                                                                            (double)Cls.instanceCount;
                                                                                        str3 = str3;
                                                                                        i37 >>= -36;
                                                                                        Test0098.fArrFld[i33 - 1] =
                                                                                            (float)Cls.instanceCount;
                                                                                        sFld = (short)Cls.byFld;
                                                                                        break;
                                                                                    case 124:
                                                                                        Cls.instanceCount -= (long)49;
                                                                                        i27 = 32152;
                                                                                        Cls.instanceCount = -167L;
                                                                                        break;
                                                                                    case 125:
                                                                                        synchronized (O20) {
                                                                                            // Resetting String
                                                                                            // variable to a short
                                                                                            // value to prevent OOM
                                                                                            str3 = "";
                                                                                            str3 += str3;
                                                                                        }
                                                                                        byArr[i41 - 1] += (byte)225;
                                                                                        Cls.fFld *= (float)sFld;
                                                                                        synchronized (O21) {
                                                                                            lArr1[i28 - 1] +=
                                                                                                (long)iFld2;
                                                                                            i34 -= i38;
                                                                                        }
                                                                                        break;
                                                                                    case 126:
                                                                                    case 127:
                                                                                        lArr1 = lArr1;
                                                                                        break;
                                                                                    case 128:
                                                                                        cFld *= (char)iFld;
                                                                                        break;
                                                                                }
                                                                            }
                                                                            break;
                                                                        default:
                                                                    }
                                                                    break;
                                                                case 27:
                                                                    Test0098.iArrFld1[i28] = (int)-1.110186;
                                                                    break;
                                                                case 28:
                                                                    Cls.fFld += (float)Test0098.iFld1;
                                                                    break;
                                                                case 29:
                                                                    break;
                                                                case 30:
                                                                    cArr[(int)(d2)][(int)(d2 - 1)] += 41983;
                                                                    break;
                                                                case 31:
                                                                    Test0098.lFld *= (long)Cls.fFld;
                                                                case 32:
                                                                    Test0098.lFld <<= (long)i33;
                                                                case 33:
                                                                    i43 = (int)Cls.instanceCount;
                                                                default:
                                                            }
                                                    }
                                                }
                                            default:
                                        }
                                    case 18:
                                        i42 /= -130;
                                    case 19:
                                        cFld -= (char)Cls.instanceCount;
                                        break;
                                    case 20:
                                        i32 ^= i33;
                                        break;
                                    case 21:
                                        i37 += i38;
                                        break;
                                    case 22:
                                        i42 >>= (int)sFld;
                                        break;
                                    default:
                                        Test0098.iArrFld1[(int)(d2 + 1)] = -13;
                                }
                            } while (++i35 < 3);
                        }
                        catch (UserDefinedExceptionTest0098 exc21) {
                            Cls.byFld <<= (byte)Cls.instanceCount;
                        }
                        catch (ArrayIndexOutOfBoundsException exc22) {
                        }
                    }
                }
            }
        }

        FuzzerUtils.out.println("i26 i27 i28 = " + i26 + "," + i27 + "," + i28);
        FuzzerUtils.out.println("i29 d2 i30 = " + i29 + "," + Double.doubleToLongBits(d2) + "," + i30);
        FuzzerUtils.out.println("i31 i32 i33 = " + i31 + "," + i32 + "," + i33);
        FuzzerUtils.out.println("i34 d3 i35 = " + i34 + "," + Double.doubleToLongBits(d3) + "," + i35);
        FuzzerUtils.out.println("str3 i36 i37 = " + str3.length() + "," + i36 + "," + i37);
        FuzzerUtils.out.println("i38 i39 i41 = " + i38 + "," + i39 + "," + i41);
        FuzzerUtils.out.println("i42 i43 i44 = " + i42 + "," + i43 + "," + i44);
        FuzzerUtils.out.println("dArr byArr lArr1 = " + Double.doubleToLongBits(FuzzerUtils.checkSum(dArr)) + "," +
            FuzzerUtils.checkSum(byArr) + "," + FuzzerUtils.checkSum(lArr1));
        FuzzerUtils.out.println("cArr O12 O13 = " + FuzzerUtils.checkSum(cArr) + "," + FuzzerUtils.checkSum(O12) + ","
            + FuzzerUtils.checkSum(O13));
        FuzzerUtils.out.println("O14 O15 O16 = " + FuzzerUtils.checkSum(O14) + "," + FuzzerUtils.checkSum(O15) + "," +
            FuzzerUtils.checkSum(O16));
        FuzzerUtils.out.println("O17 O18 O19 = " + FuzzerUtils.checkSum(O17) + "," + FuzzerUtils.checkSum(O18) + "," +
            FuzzerUtils.checkSum(O19));
        FuzzerUtils.out.println("O20 O21 Cls = " + FuzzerUtils.checkSum(O20) + "," + FuzzerUtils.checkSum(O21) + "," +
            Cls.instanceCount);

        FuzzerUtils.out.println("Test0098.instanceCount iFld sFld = " + Test0098.instanceCount + "," + iFld + "," + sFld);
        FuzzerUtils.out.println("Test0098.lFld Test0098.bFld Test0098.iFld1 = " + Test0098.lFld + "," + (Test0098.bFld ? 1 : 0) + "," +
            Test0098.iFld1);
        FuzzerUtils.out.println("iFld2 cFld Test0098.iArrFld1 = " + iFld2 + "," + (int)cFld + "," +
            FuzzerUtils.checkSum(Test0098.iArrFld1));
        FuzzerUtils.out.println("Test0098.fArrFld Cls = " + Double.doubleToLongBits(FuzzerUtils.checkSum(Test0098.fArrFld)) +
            "," + Cls.instanceCount);

        FuzzerUtils.out.println("iMeth_check_sum: " + iMeth_check_sum);
        FuzzerUtils.out.println("vMeth_check_sum: " + vMeth_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test0098 _instance = new Test0098();
            for (int i = 0; i < 10; i++ ) {
                try {
                    _instance.mainTest0098(strArr);
                 } catch (OutOfMemoryError ex) {
                    ex.printStackTrace(FuzzerUtils.err);
                    System.exit(1);
                 } catch (Exception ex) {
                    FuzzerUtils.out.println(ex.getClass().getCanonicalName());
                 }
             }
         } catch (Exception ex) {
            FuzzerUtils.out.println(ex.getClass().getCanonicalName());
         }
    }
}
///////////////////////////////////////////////////////////////////////
class Cls {

    public static final int N = 128;

    public static long instanceCount=38304L;
    public static double dFld=-64.55423;
    public static volatile byte byFld=109;
    public static float fFld=28.487F;
    public static volatile int iArrFld[][]=new int[N][N];

    static {
        FuzzerUtils.init(Cls.iArrFld, 47275);
    }

    public static long strMeth_check_sum = 0;

    public static String strMeth(int i6, boolean b) {

        long meth_res = 0;
        String str2="one";
        int i7=-19, i8=31, i9=7, i10=67, i11=11, i12=-11, i13=2, i14=7, i15=44499, i16=1;
        long l1=-1126729438614324699L, lArr[]=new long[N];
        char c1=29663;
        Object OArr[]=new Object[32];
        float fArr[]=new float[N];
        Cls O2=new Cls(), O3=new Cls(), O4=new Cls(), O5=new Cls(), O6=new Cls();

        FuzzerUtils.init(lArr, -87L);
        FuzzerUtils.init(OArr, new Test0098());
        FuzzerUtils.init(fArr, -44.658F);

        // Resetting String variable to a short value to prevent OOM
        str2 = "";
        str2 += "four";
        switch (((i6 >>> 1) % 2) + 30) {
            case 30:
                i6 += (int)Cls.dFld;
                for (long l : lArr) {
                    for (i7 = (int) (1); i7 < 12; i7 += 2) {
                        // Resetting String variable to a short value to prevent OOM
                        str2 = "";
                        str2 += str2;
                        Cls.iArrFld[i7 + 1][i7] |= i7;
                        for (i9 = (int) (i7); i9 < 3; i9 += 2) {
                            switch (((i9 % 2) * 5) + 124) {
                                case 127:
                                case 133:
                                    for (i11 = (int) (1); i11 < 1; i11 += 3) {
                                        short s=6213;
                                        Cls.instanceCount *= -7365728160303435423L;
                                        switch ((i9 % 9) + 21) {
                                            case 21:
                                                Cls.byFld >>= (byte)l1;
                                                i10 *= (int)s;
                                            case 22:
                                                OArr[(i10 >>> 1) % 32] = O2;
                                                Cls.instanceCount -= (long)Cls.fFld;
                                                if (false) continue;
                                                fArr[i7 - 1] = (float)l;
                                            case 23:
                                                Cls.iArrFld[i9 - 1][i11 - 1] = i10;
                                                i12 *= i11;
                                                i12 = 9;
                                                Cls.dFld += (double)65431;
                                                for (i13 = (int) (1); i13 < 1; i13 += 3) {
                                                    i12 <<= i14;
                                                }
                                                s >>= (short)i8;
                                                if (b) continue;
                                                i14 -= (int)Cls.byFld;
                                            case 24:
                                                s += (short)-104;
                                                break;
                                            case 25:
                                                if (b) break;
                                                switch ((i9 % 5) + 125) {
                                                    case 125:
                                                        Test0098.instanceCount = -9445L;
                                                        i14 += (int)4222134622L;
                                                        switch (((i9 >>> 1) % 6) + 52) {
                                                            case 52:
                                                                Cls.dFld -= (double)Cls.instanceCount;
                                                                break;
                                                            case 53:
                                                                i12 >>= i14;
                                                                switch (((i7 % 2) * 5) + 124) {
                                                                    case 134:
                                                                        for (i15 = (int) (1); 1 > i15; i15++) {
                                                                            i8 <<= 7223;
                                                                            lArr = lArr;
                                                                            i8 = (int)-2780679521595187011L;
                                                                            c1 = (char)i7;
                                                                            Cls.dFld -= (double)i16;
                                                                            switch (((i9 % 10) * 5) + 106) {
                                                                                case 146:
                                                                                    Cls.fFld += (float)i12;
                                                                                    l1 >>= (long)s;
                                                                                    break;
                                                                                case 116:
                                                                                case 117:
                                                                                    Cls.iArrFld[i15 + 1][i11 + 1] -= i9;
                                                                                case 108:
                                                                                    i14 <<= i8;
                                                                                    break;
                                                                                case 121:
                                                                                    b = true;
                                                                                    break;
                                                                                case 107:
                                                                                    Cls.iArrFld[i7][i9 + 1] += i16;
                                                                                    break;
                                                                                case 142:
                                                                                    c1 = (char)Test0098.instanceCount;
                                                                                    break;
                                                                                case 145:
                                                                                case 129:
                                                                                    c1 /= (char)11;
                                                                                    break;
                                                                                case 141:
                                                                                    str2 = str2;
                                                                            }
                                                                        }
                                                                        break;
                                                                    case 126:
                                                                        break;
                                                                }
                                                                break;
                                                            case 54:
                                                                Cls.iArrFld[i7 + 1][i9 - 1] += (int)Cls.dFld;
                                                                break;
                                                            case 55:
                                                                i14 = (int)Cls.dFld;
                                                                break;
                                                            case 56:
                                                                // Resetting String variable to a short value to
                                                                // prevent OOM
                                                                str2 = "";
                                                                str2 += str2;
                                                            case 57:
                                                                i16 += i8;
                                                                break;
                                                            default:
                                                                b = b;
                                                        }
                                                        break;
                                                    case 126:
                                                        if (true) continue;
                                                    case 127:
                                                        break;
                                                    case 128:
                                                        lArr[i7 - 1] = (long)i13;
                                                        break;
                                                    case 129:
                                                        Cls.fFld += (float)l;
                                                        break;
                                                }
                                                break;
                                            case 26:
                                                Test0098.instanceCount = (long)i10;
                                                break;
                                            case 27:
                                                Cls.byFld |= (byte)i15;
                                            case 28:
                                                Cls.iArrFld[i9 + 1][i9] -= i7;
                                            case 29:
                                                i8 = i15;
                                                break;
                                            default:
                                                Cls.dFld *= (double)i16;
                                        }
                                    }
                                    break;
                            }
                        }
                    }
                }
                break;
            case 31:
                str2 = "three";
                break;
        }
        meth_res = i6 + (b ? 1 : 0) + str2.length() + i7 + i8 + i9 + i10 + i11 + i12 + l1 + i13 + i14 + i15 + i16 +
            (int)c1 + FuzzerUtils.checkSum(lArr) + FuzzerUtils.checkSum(OArr) +
            Double.doubleToLongBits(FuzzerUtils.checkSum(fArr)) + FuzzerUtils.checkSum(O2) + FuzzerUtils.checkSum(O3) +
            FuzzerUtils.checkSum(O4) + FuzzerUtils.checkSum(O5) + FuzzerUtils.checkSum(O6);
        strMeth_check_sum += meth_res;
        return String.valueOf(meth_res);
    }

}
///////////////////////////////////////////////////////////////////////
class UserDefinedExceptionTest0098 extends RuntimeException {
    public int field;
    public UserDefinedExceptionTest0098() { super("UserDefinedExceptionTest0098"); }
    public UserDefinedExceptionTest0098(String mess) { super(mess); }
}

//DEBUG  Test0098 ->  Test0098
//DEBUG  main ->  main
//DEBUG  mainTest0098 ->  mainTest0098
//DEBUG  vMeth ->  vMeth mainTest0098
//DEBUG  Cls ->  Cls vMeth mainTest0098 strMeth iMeth
//DEBUG  iMeth ->  iMeth vMeth mainTest0098
//DEBUG  strMeth ->  strMeth iMeth vMeth mainTest0098
//DEBUG  Depth = 4
//DEBUG  Classes = 2
//DEBUG  static objects = {}
