// Generated by Java* Fuzzer test generator (1.0.001). Sun Mar 29 19:31:02 2026
public class Test0004 {

    public static final int N = 128;

    public static long instanceCount=8079857952765117020L;
    public float fFld=1.623F;
    public static int iFld=-5;
    public static boolean bFld=false;
    public static double dFld=40.91538;
    public static int iFld1=10;
    public static volatile double dFld1=0.99767;
    public static String strFld="four";
    public static int iFld2=-61;
    public static char cFld=18265;
    public String strFld1="three";
    public static long lArrFld[]=new long[N];
    public static float fArrFld[]=new float[N];
    public static String strArrFld[]=new String[N];
    public static char cArrFld[]=new char[N];
    public static double dArrFld[]=new double[N];
    public byte byArrFld[]=new byte[N];

    static {
        FuzzerUtils.init(Test0004.lArrFld, -4117057838302095548L);
        FuzzerUtils.init(Test0004.fArrFld, 69.359F);
        FuzzerUtils.init(Test0004.strArrFld, "three");
        FuzzerUtils.init(Test0004.cArrFld, (char)43614);
        FuzzerUtils.init(Test0004.dArrFld, 7.3142);
    }

    public static long iMeth_check_sum = 0;
    public static long vMeth_check_sum = 0;
    public static long iMeth1_check_sum = 0;

    public static int iMeth1(int i9, float f1) {

        long meth_res = 0;
        int i11=-236, i12=-11, i13=-27257, i14=-21, i15=-3, i16=10, i17=-201, i18=-5, i19=117, i20=43254, i21=3118,
            i22=-61187, i23=-120, i24=25010, i25=-150, i26=-8, i27=-109, i28=3, i29=-34, i30=56301, i31=12, i32=8,
            iArr1[]=new int[N];
        boolean b=true;
        short s=7711;
        String str2="four";
        byte by2=-29;
        double d=0.112929, dArr[]=new double[N];
        char c=24419;
        float f2=0.483F, fArr[]=new float[N];
        Cls O3=new Cls(), O4=new Cls(), O5=new Cls(), O6=new Cls(), O7=new Cls(), O8=new Cls(), O9=new Cls(), O10=new
            Cls(), O11=new Cls();

        FuzzerUtils.init(iArr1, -41);
        FuzzerUtils.init(fArr, -44.891F);
        FuzzerUtils.init(dArr, 58.73425);

        for (int i10 : iArr1) {
            i11 = 12;
            do {
                b = b;
                for (i12 = (int) (i11); i12 < 2; i12++) {
                    O3 = O3;
                }
                try {
                    if (i11 != 0) {
                    }
                }
                catch (UserDefinedExceptionTest0004 exc8) {
                    i10 -= (int)s;
                    Test0004.iFld = i12;
                    i10 += (int)Cls.instanceCount;
                }
                for (i14 = (int) (2); i14 > 1; i14 -= 3) {
                    for (i16 = (int) (i11); i16 < 2; i16 += 2) {
                        b = b;
                        f1 *= (float)i10;
                        str2 = "four";
                        for (i18 = (int) (1); i18 < 1; i18 += 3) {
                            i19 *= (int)by2;
                        }
                        d = (double)c;
                    }
                }
                for (i20 = (int) (2); 1 < i20; --i20) {
                    i19 >>= (int)s;
                    if (b) {
                        i22 = 2;
                        while ((i22 -= 3) > 0) {
                            Test0004.instanceCount = Cls.instanceCount;
                        }
                        iArr1[i11 + 1] <<= (int)Test0004.instanceCount;
                        s -= (short)f1;
                        i15 = (int)Test0004.instanceCount;
                        iArr1[i11 + 1] <<= (int)Cls.instanceCount;
                        f1 = f1;
                    }
                    iArr1[i11] -= i18;
                }
                O5 = new Cls();
            } while ((i11 -= 2) > 0);
            iArr1[(i12 >>> 1) % N] >>= i19;
            i19 = 8;
        }
        for (i23 = (int) (118); i23 > 1; --i23) {
            for (f2 = (float) (13); f2 > i23; f2--) {
                // Resetting String variable to a short value to prevent OOM
                str2 = "hhhh";
                str2 += str2;
                fArr[i23 + 1] *= (float)Cls.instanceCount;
            }
            i26 = (int)Test0004.instanceCount;
        }
        i21 = (int)s;
        i27 = 95;
        do {
            for (i28 = (int) (47); i28 > 1; --i28) {
                i30 = 2;
                do {
                    dArr[i27] /= (double)(i9 | 1);
                    for (i31 = (int) (1); i31 < 1; ++i31) {
                        i15 += i29;
                        by2 -= (byte)i25;
                        Test0004.lArrFld[i28 - 1] += (long)-120.50566;
                    }
                } while (--i30 > 0);
            }
        } while ((i27 -= 3) > 0);
        meth_res = i9 + Float.floatToIntBits(f1) + i11 + (b ? 1 : 0) + i12 + i13 + s + i14 + i15 + i16 + i17 +
            str2.length() + i18 + i19 + by2 + Double.doubleToLongBits(d) + (int)c + i20 + i21 + i22 + i23 + i24 +
            Float.floatToIntBits(f2) + i25 + i26 + i27 + i28 + i29 + i30 + i31 + i32 + FuzzerUtils.checkSum(iArr1) +
            Double.doubleToLongBits(FuzzerUtils.checkSum(fArr)) + Double.doubleToLongBits(FuzzerUtils.checkSum(dArr)) +
            FuzzerUtils.checkSum(O3) + FuzzerUtils.checkSum(O4) + FuzzerUtils.checkSum(O5) + FuzzerUtils.checkSum(O6) +
            FuzzerUtils.checkSum(O7) + FuzzerUtils.checkSum(O8) + FuzzerUtils.checkSum(O9) + FuzzerUtils.checkSum(O10)
            + FuzzerUtils.checkSum(O11);
        iMeth1_check_sum += meth_res;
        return (int)meth_res;
    }

    public static void vMeth(String str1, int i6) {

        long meth_res = 0;
        int i7=-121, i8=34530, i33=49821, i34=-18336, i35=5225, i36=26883, i37=58301, i38=-10, i39=-3, i40=29943,
            i41=-230, i42=23865, iArr2[]=new int[N];
        byte by1=-5, byArr[]=new byte[N];
        float f3=-119.383F, fArr1[]=new float[N];
        char c1=39944;
        short s1=-1605;
        long l=1707534567L;
        double dArr1[]=new double[N];
        boolean bArr[]=new boolean[N];
        Cls O2=new Cls(), O12=new Cls(), O13=new Cls(), O14=new Cls(), O15=new Cls(), O16=new Cls();

        FuzzerUtils.init(iArr2, -149);
        FuzzerUtils.init(dArr1, -50.68093);
        FuzzerUtils.init(byArr, (byte)-80);
        FuzzerUtils.init(fArr1, -7.426F);
        FuzzerUtils.init(bArr, true);

        i6 = (++Test0004.iFld);
        for (i7 = (int) (119); i7 > 7; i7 -= 2) {
            by1 >>= (byte)((Cls.instanceCount + Integer.reverseBytes(i7)) - iMeth1(Test0004.iFld, f3));
            for (i33 = (int) (27); i33 > 1; i33 -= 3) {
                i8 >>= i6;
                // Resetting String variable to a short value to prevent OOM
                str1 = "";
                str1 += "four";
                Test0004.bFld = Test0004.bFld;
                for (i35 = (int) (4); i35 > 1; i35 -= 2) {
                    for (i37 = (int) (1); i37 < 4; i37 += 3) {
                        Test0004.dFld -= (double)Test0004.instanceCount;
                        switch ((i37 % 1) + 86) {
                            case 86:
                                i39 = 1;
                                do {
                                    i6 *= Test0004.iFld;
                                    i8 <<= i37;
                                    i8 &= i6;
                                    str1 = str1;
                                    // Resetting String variable to a short value to prevent OOM
                                    str1 = "";
                                    str1 += str1;
                                    Test0004.iFld1 *= (int)Cls.instanceCount;
                                    Test0004.fArrFld[i35 - 1] -= (float)-50832L;
                                    Test0004.dFld -= (double)Test0004.iFld;
                                } while ((i39 += 2) < 4);
                                for (i40 = (int) (4); i40 > i37; i40 -= 2) {
                                    Test0004.iFld1 = i35;
                                    Test0004.dFld -= (double)c1;
                                    str1 = "one";
                                    f3 *= (float)Test0004.instanceCount;
                                    Test0004.instanceCount >>= (long)i7;
                                    f3 = (float)Cls.instanceCount;
                                    switch (((Test0004.iFld >>> 1) % 5) + 62) {
                                        case 62:
                                            switch ((i33 % 5) + 107) {
                                                case 107:
                                                    switch (((i37 % 2) * 5) + 3) {
                                                        case 13:
                                                            iArr2 = iArr2;
                                                        case 10:
                                                            i34 = Test0004.iFld1;
                                                            break;
                                                    }
                                                    Test0004.dFld1 -= (double)i38;
                                                    dArr1[i35] = (double)i33;
                                                    byArr[i33 - 1] -= (byte)Test0004.iFld;
                                                    Test0004.dFld += (double)-6519266594270856350L;
                                                    fArr1[i33] += f3;
                                                    synchronized (O16) {
                                                        Cls.instanceCount *= (long)110.16F;
                                                        Test0004.lArrFld[i37] -= 3593L;
                                                        Test0004.strArrFld[i40] = str1;
                                                        if (Test0004.iFld1 != 0) {
                                                            vMeth_check_sum += str1.length() + i6 + i7 + i8 + by1 +
                                                                Float.floatToIntBits(f3) + i33 + i34 + i35 + i36 + i37
                                                                + i38 + i39 + i40 + i41 + (int)c1 + i42 + s1 + l +
                                                                FuzzerUtils.checkSum(iArr2) +
                                                                Double.doubleToLongBits(FuzzerUtils.checkSum(dArr1)) +
                                                                FuzzerUtils.checkSum(byArr) +
                                                                Double.doubleToLongBits(FuzzerUtils.checkSum(fArr1)) +
                                                                FuzzerUtils.checkSum(bArr) + FuzzerUtils.checkSum(O2) +
                                                                FuzzerUtils.checkSum(O12) + FuzzerUtils.checkSum(O13) +
                                                                FuzzerUtils.checkSum(O14) + FuzzerUtils.checkSum(O15) +
                                                                FuzzerUtils.checkSum(O16);
                                                            return;
                                                        }
                                                        i42 = i34;
                                                        s1 += (short)Test0004.dFld1;
                                                        i41 += i36;
                                                        bArr[i7 - 1] = Test0004.bFld;
                                                    }
                                                    break;
                                                case 108:
                                                case 109:
                                                    Test0004.dFld1 *= Test0004.dFld1;
                                                    break;
                                                case 110:
                                                    f3 -= (float)i6;
                                                case 111:
                                                    i42 -= i39;
                                                    break;
                                            }
                                            break;
                                        case 63:
                                            iArr2[i37] = 43304;
                                            break;
                                        case 64:
                                        case 65:
                                            i38 = (int)l;
                                            break;
                                        case 66:
                                            break;
                                        default:
                                            Test0004.instanceCount += (long)f3;
                                    }
                                }
                                break;
                            default:
                        }
                    }
                }
            }
        }
        vMeth_check_sum += str1.length() + i6 + i7 + i8 + by1 + Float.floatToIntBits(f3) + i33 + i34 + i35 + i36 + i37
            + i38 + i39 + i40 + i41 + (int)c1 + i42 + s1 + l + FuzzerUtils.checkSum(iArr2) +
            Double.doubleToLongBits(FuzzerUtils.checkSum(dArr1)) + FuzzerUtils.checkSum(byArr) +
            Double.doubleToLongBits(FuzzerUtils.checkSum(fArr1)) + FuzzerUtils.checkSum(bArr) +
            FuzzerUtils.checkSum(O2) + FuzzerUtils.checkSum(O12) + FuzzerUtils.checkSum(O13) +
            FuzzerUtils.checkSum(O14) + FuzzerUtils.checkSum(O15) + FuzzerUtils.checkSum(O16);
    }

    public static int iMeth(String str, int i, float f) {

        long meth_res = 0;
        int i1=122, i2=-4, i3=29002, i4=103, i5=-22076, i43=77, i44=-243, i45=112, i46=11, i47=-43, i48=90, iArr[]=new
            int[N], iArr3[]=new int[N];
        boolean b1=true;
        Cls O=new Cls(), O1=new Cls(), O17=new Cls(), O18=new Cls(), O19=new Cls();

        FuzzerUtils.init(iArr, -5);
        FuzzerUtils.init(iArr3, -6842);

        f += (float)(((Test0004.iFld * Test0004.iFld) + (i - Test0004.iFld)) >> Test0004.iFld);
        i1 = 1;
        while (++i1 < 117) {
            byte by=-90;
            try {
                Test0004.iFld = (-45 % iArr[i1]);
                Test0004.iFld = (i % 47564);
                i = (i1 / -211);
            } catch (ArithmeticException a_e) {}
            for (i2 = (int) (13); i2 > 1; i2--) {
                for (i4 = (int) (1); i4 < 2; i4++) {
                    vMeth(str, 63);
                    Test0004.strFld = Test0004.strFld;
                    switch (((i2 % 4) * 5) + 25) {
                        case 39:
                            i = i1;
                            synchronized (O17) {
                                Test0004.dFld1 = (double)45594;
                            }
                            Test0004.bFld = b1;
                            Test0004.instanceCount -= (long)Test0004.iFld1;
                            for (i44 = (int) (2); i44 > 1; --i44) {
                            }
                            Test0004.bFld = true;
                            Test0004.iFld2 = (int)f;
                            if (b1) break;
                            break;
                        case 38:
                            try {
                                iArr[i1 - 1] += (int)Test0004.dFld1;
                            }
                            catch (ArrayIndexOutOfBoundsException exc9) {
                                i43 -= i2;
                                iArr[i2] = (int)106.26522;
                                f += (float)Test0004.dFld;
                                Test0004.iFld2 -= i45;
                                i46 = 1;
                                do {
                                    Cls.instanceCount -= (long)-136;
                                    Test0004.cArrFld[i2] = (char)-26490;
                                    Test0004.instanceCount = (long)i2;
                                    Test0004.iFld >>>= -71;
                                    switch ((((13 >>> 1) % 7) * 5) + 119) {
                                        case 150:
                                            f = (float)Cls.instanceCount;
                                            for (i47 = (int) (1); i47 < 1; i47++) {
                                                Test0004.iFld *= (int)Test0004.instanceCount;
                                                i *= 214;
                                                Test0004.strArrFld[i2 + 1] = str;
                                                str = str;
                                                Test0004.dFld -= (double)i5;
                                                Test0004.iFld2 >>= i45;
                                            }
                                            iArr[i4 - 1] = (int)Cls.instanceCount;
                                            if (b1) continue;
                                            Test0004.iFld2 += (int)Test0004.instanceCount;
                                            break;
                                        case 141:
                                            Test0004.iFld >>= i43;
                                            if (i3 != 0) {
                                            }
                                            Test0004.strArrFld[i2 + 1] = Test0004.strFld;
                                            Test0004.lArrFld[i2 - 1] = (long)Test0004.cFld;
                                        case 123:
                                            Test0004.iFld = i;
                                            Test0004.lArrFld[i2 + 1] += (long)i3;
                                            break;
                                        case 131:
                                        case 129:
                                            Test0004.strArrFld = Test0004.strArrFld;
                                            break;
                                        case 136:
                                            i3 <<= 50543;
                                        case 149:
                                            iArr[i1 + 1] = (int)Cls.instanceCount;
                                            break;
                                    }
                                } while (++i46 < 2);
                            }
                            finally {
                            }
                        case 36:
                            Test0004.dArrFld[i1 + 1] -= (double)215;
                        case 45:
                            by *= (byte)i3;
                        default:
                            iArr3 = iArr;
                    }
                }
            }
        }
        meth_res = str.length() + i + Float.floatToIntBits(f) + i1 + i2 + i3 + i4 + i5 + i43 + (b1 ? 1 : 0) + i44 + i45
            + i46 + i47 + i48 + FuzzerUtils.checkSum(iArr) + FuzzerUtils.checkSum(iArr3) + FuzzerUtils.checkSum(O) +
            FuzzerUtils.checkSum(O1) + FuzzerUtils.checkSum(O17) + FuzzerUtils.checkSum(O18) +
            FuzzerUtils.checkSum(O19);
        iMeth_check_sum += meth_res;
        return (int)meth_res;
    }

    public void mainTest0004(String[] strArr1) {

        long meth_res = 0;
        double d1=1.5366;
        int i49=47, i50=-44436, i51=0, i52=-12288, i53=-161, i54=-253, i55=63, i56=-27035, i57=-4, i58=-9, i59=-3,
            i60=29026, i61=11, i62=4, i63=-116, i64=-148, iArr4[]=new int[N];
        byte by3=-55;
        short s2=10043;
        long l1=7806872940464805872L;
        float fArr2[][]=new float[N][N];
        Cls O20=new Cls(), O21=new Cls(), O22=new Cls(), O23=new Cls(), O24=new Cls(), O25=new Cls(), O26=new Cls(),
            O27=new Cls();

        FuzzerUtils.init(iArr4, 0);
        FuzzerUtils.init(fArr2, 1.82F);

        fFld -= (float)(((Test0004.iFld * Test0004.instanceCount) + iMeth(Test0004.strFld, -7, fFld)) - Test0004.iFld1);
        for (d1 = (double) (102); d1 > 5; d1 -= 2) {
            i50 = 101;
            while ((i50 -= 3) > 0) {
                iArr4[i50 + 1] = Test0004.iFld1;
                // Resetting String variable to a short value to prevent OOM
                Test0004.strFld = "";
                Test0004.strFld += "four";
                i51 = 1;
                do {
                    synchronized (O21) {
                        Test0004.instanceCount += (long)i49;
                        Test0004.iFld *= (int)fFld;
                        for (i53 = (int) (2); i53 > 1; i53 -= 2) {
                            switch (((Test0004.iFld1 >>> 1) % 5) + 23) {
                                case 23:
                                    Test0004.dFld1 += (double)Test0004.iFld1;
                                    i52 |= -61074;
                                    Test0004.iFld2 = i53;
                                    Cls.instanceCount += (long)i50;
                                    switch ((i50 % 2) + 44) {
                                        case 44:
                                            Test0004.iFld2 += i52;
                                            Test0004.iFld = Test0004.iFld;
                                            O20 = O20;
                                            Test0004.iFld = i50;
                                            iArr4 = iArr4;
                                            Test0004.dFld = (double)i52;
                                            fFld -= (float)Test0004.dFld;
                                            i54 %= (int)(Cls.instanceCount | 1);
                                            // Resetting String variable to a short value to prevent OOM
                                            Test0004.strFld = "";
                                            Test0004.strFld += Test0004.strFld;
                                        case 45:
                                            switch (((i50 % 2) * 5) + 13) {
                                                case 19:
                                                    Test0004.iFld1 = (int)fFld;
                                                    break;
                                                case 22:
                                                    Test0004.iFld2 |= -68;
                                                    Test0004.iFld2 = i51;
                                                    for (i55 = (int) (1); i55 < 2; ++i55) {
                                                        Cls.instanceCount >>= Cls.instanceCount;
                                                    }
                                                    iArr4[i53 - 1] *= (int)4260261167L;
                                                    iArr4[i53] = Test0004.iFld2;
                                                    Test0004.strArrFld[i51] = Test0004.strFld;
                                            }
                                            Test0004.lArrFld[i53 + 1] += (long)i54;
                                            s2 -= (short)-13;
                                            i56 >>= i56;
                                            for (i57 = (int) (2); i57 > 1; i57--) {
                                                Test0004.cFld = (char)Test0004.iFld1;
                                                Test0004.iFld1 += (int)Test0004.instanceCount;
                                                iArr4[i50 - 1] *= (int)Test0004.instanceCount;
                                                Cls.instanceCount /= ((long)(fFld) | 1);
                                            }
                                            Cls.instanceCount *= (long)s2;
                                            fFld = (float)Cls.instanceCount;
                                            break;
                                        default:
                                            if (Test0004.bFld) break;
                                            Cls.instanceCount = (long)i51;
                                            Test0004.strFld = strFld1;
                                    }
                                case 24:
                                    switch ((((i50 >>> 1) % 5) * 5) + 102) {
                                        case 123:
                                            i54 >>= Test0004.iFld1;
                                            iArr4[(int)(d1 - 1)] *= 38211;
                                            for (i59 = (int) (1); i59 < 2; i59 += 2) {
                                                s2 -= s2;
                                                Test0004.instanceCount -= (long)-1;
                                            }
                                            Test0004.strFld = strFld1;
                                            Test0004.instanceCount -= (long)i58;
                                            Test0004.lArrFld[i53 - 1] -= (long)i58;
                                            for (i61 = (int) (1); i61 < 2; i61 += 2) {
                                                Cls.instanceCount -= (long)Test0004.dFld;
                                                Test0004.lArrFld = Test0004.lArrFld;
                                                fFld = (float)Test0004.dFld;
                                                switch ((int)(((d1 % 6) * 5) + 70)) {
                                                    case 81:
                                                        switch (((i53 % 2) * 5) + 91) {
                                                            case 92:
                                                                i56 -= i49;
                                                            case 95:
                                                                i56 = i53;
                                                                iArr4[i50 + 1] = (int)Test0004.instanceCount;
                                                                break;
                                                        }
                                                        Test0004.lArrFld[i51 - 1] = (long)fFld;
                                                        break;
                                                    case 75:
                                                        switch ((((i51 >>> 1) % 2) * 5) + 44) {
                                                            case 50:
                                                                byArrFld = byArrFld;
                                                                Test0004.iFld2 = i58;
                                                                Test0004.lArrFld = Test0004.lArrFld;
                                                                Test0004.lArrFld[i51] -= (long)Test0004.iFld2;
                                                                break;
                                                            case 52:
                                                                fFld *= fFld;
                                                                strFld1 = strFld1;
                                                                Test0004.lArrFld[i51 - 1] -= l1;
                                                                iArr4[(int)(d1 + 1)] = i53;
                                                                l1 = (long)i60;
                                                                break;
                                                        }
                                                        // Resetting String variable to a short value to prevent OOM
                                                        strFld1 = "";
                                                        strFld1 += Test0004.strFld;
                                                        Test0004.dArrFld[i51] = (double)fFld;
                                                        O20 = O21;
                                                        switch ((i50 % 2) + 71) {
                                                            case 71:
                                                                synchronized (O27) {
                                                                    byArrFld[i61 + 1] >>>= by3;
                                                                }
                                                                fFld += fFld;
                                                                break;
                                                            case 72:
                                                                // Resetting String variable to a short value to
                                                                // prevent OOM
                                                                Test0004.strFld = "";
                                                                Test0004.strFld += strFld1;
                                                                fArr2 = fArr2;
                                                            default:
                                                                Test0004.iFld2 -= -21617;
                                                                Test0004.bFld = Test0004.bFld;
                                                                i58 -= (int)Test0004.instanceCount;
                                                        }
                                                        break;
                                                    case 84:
                                                        fFld *= (float)Test0004.cFld;
                                                        break;
                                                    case 89:
                                                        Test0004.iFld -= (int)fFld;
                                                        break;
                                                    case 93:
                                                        i54 *= (int)Test0004.instanceCount;
                                                        break;
                                                    case 72:
                                                }
                                            }
                                            break;
                                        case 126:
                                            i64 <<= (int)l1;
                                        case 112:
                                            // Resetting String variable to a short value to prevent OOM
                                            Test0004.strFld = "";
                                            Test0004.strFld += strFld1;
                                            break;
                                        case 110:
                                            Test0004.iFld = Test0004.iFld1;
                                            break;
                                        case 116:
                                            i64 = i52;
                                        default:
                                            strFld1 = Test0004.strFld;
                                    }
                                case 25:
                                    Test0004.iFld1 -= i50;
                                    break;
                                case 26:
                                    Test0004.bFld = Test0004.bFld;
                                    break;
                                case 27:
                                    Cls.instanceCount = (long)i56;
                                    break;
                                default:
                                    Test0004.cFld -= (char)i61;
                            }
                        }
                    }
                } while ((i51 += 2) < 16);
            }
        }

        FuzzerUtils.out.println("d1 i49 i50 = " + Double.doubleToLongBits(d1) + "," + i49 + "," + i50);
        FuzzerUtils.out.println("i51 i52 i53 = " + i51 + "," + i52 + "," + i53);
        FuzzerUtils.out.println("i54 by3 i55 = " + i54 + "," + by3 + "," + i55);
        FuzzerUtils.out.println("i56 s2 i57 = " + i56 + "," + s2 + "," + i57);
        FuzzerUtils.out.println("i58 i59 i60 = " + i58 + "," + i59 + "," + i60);
        FuzzerUtils.out.println("i61 i62 l1 = " + i61 + "," + i62 + "," + l1);
        FuzzerUtils.out.println("i63 i64 iArr4 = " + i63 + "," + i64 + "," + FuzzerUtils.checkSum(iArr4));
        FuzzerUtils.out.println("fArr2 O20 O21 = " + Double.doubleToLongBits(FuzzerUtils.checkSum(fArr2)) + "," +
            FuzzerUtils.checkSum(O20) + "," + FuzzerUtils.checkSum(O21));
        FuzzerUtils.out.println("O22 O23 O24 = " + FuzzerUtils.checkSum(O22) + "," + FuzzerUtils.checkSum(O23) + "," +
            FuzzerUtils.checkSum(O24));
        FuzzerUtils.out.println("O25 O26 O27 = " + FuzzerUtils.checkSum(O25) + "," + FuzzerUtils.checkSum(O26) + "," +
            FuzzerUtils.checkSum(O27));
        FuzzerUtils.out.println("Cls = " + Cls.instanceCount);

        FuzzerUtils.out.println("Test0004.instanceCount fFld Test0004.iFld = " + Test0004.instanceCount + "," +
            Float.floatToIntBits(fFld) + "," + Test0004.iFld);
        FuzzerUtils.out.println("Test0004.bFld Test0004.dFld Test0004.iFld1 = " + (Test0004.bFld ? 1 : 0) + "," +
            Double.doubleToLongBits(Test0004.dFld) + "," + Test0004.iFld1);
        FuzzerUtils.out.println("Test0004.dFld1 Test0004.strFld Test0004.iFld2 = " + Double.doubleToLongBits(Test0004.dFld1) + "," +
            Test0004.strFld.length() + "," + Test0004.iFld2);
        FuzzerUtils.out.println("Test0004.cFld strFld1 Test0004.lArrFld = " + (int)Test0004.cFld + "," + strFld1.length() + "," +
            FuzzerUtils.checkSum(Test0004.lArrFld));
        FuzzerUtils.out.println("Test0004.fArrFld Test0004.strArrFld Test0004.cArrFld = " +
            Double.doubleToLongBits(FuzzerUtils.checkSum(Test0004.fArrFld)) + "," + FuzzerUtils.checkSum(Test0004.strArrFld) +
            "," + FuzzerUtils.checkSum(Test0004.cArrFld));
        FuzzerUtils.out.println("Test0004.dArrFld byArrFld Cls = " +
            Double.doubleToLongBits(FuzzerUtils.checkSum(Test0004.dArrFld)) + "," + FuzzerUtils.checkSum(byArrFld) + "," +
            Cls.instanceCount);

        FuzzerUtils.out.println("iMeth1_check_sum: " + iMeth1_check_sum);
        FuzzerUtils.out.println("vMeth_check_sum: " + vMeth_check_sum);
        FuzzerUtils.out.println("iMeth_check_sum: " + iMeth_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test0004 _instance = new Test0004();
            for (int i = 0; i < 10; i++ ) {
                try {
                    _instance.mainTest0004(strArr);
                 } catch (OutOfMemoryError ex) {
                    ex.printStackTrace(FuzzerUtils.err);
                    System.exit(1);
                 } catch (Exception ex) {
                    FuzzerUtils.out.println(ex.getClass().getCanonicalName());
                 }
             }
         } catch (Exception ex) {
            FuzzerUtils.out.println(ex.getClass().getCanonicalName());
         }
    }
}
///////////////////////////////////////////////////////////////////////
class Cls {

    public static final int N = 128;

    public static long instanceCount=-5553L;

}
///////////////////////////////////////////////////////////////////////
class UserDefinedExceptionTest0004 extends RuntimeException {
    public int field;
    public UserDefinedExceptionTest0004() { super("UserDefinedExceptionTest0004"); }
    public UserDefinedExceptionTest0004(String mess) { super(mess); }
}

//DEBUG  Test0004 ->  Test0004
//DEBUG  main ->  main
//DEBUG  mainTest0004 ->  mainTest0004
//DEBUG  iMeth ->  iMeth mainTest0004
//DEBUG  Cls ->  Cls iMeth1 vMeth iMeth mainTest0004
//DEBUG  vMeth ->  vMeth iMeth mainTest0004
//DEBUG  iMeth1 ->  iMeth1 vMeth iMeth mainTest0004
//DEBUG  Depth = 4
//DEBUG  Classes = 2
//DEBUG  static objects = {}
