// Generated by Java* Fuzzer test generator (1.0.001). Sun Mar 29 19:50:44 2026
public class Test0087 {

    public static final int N = 128;

    public static long instanceCount=58338L;
    public static float fFld=0.672F;
    public static float fFld1=46.55F;
    public int iFld=59251;
    public static int iArrFld[]=new int[N];
    public float fArrFld[]=new float[N];

    static {
        FuzzerUtils.init(Test0087.iArrFld, 4);
    }

    public static long vMeth2_check_sum = 0;

    public static void vMeth2(int i6, int i7) {

        long meth_res = 0;
        int i8=-27, i9=-92, i10=-13, i11=7117, i12=-32283, i13=56062, i14=6, i15=105, i16=-21364, i17=30, i18=48666,
            i19=-57923, i20=-66, i21=-11;
        double d=106.33663;
        short s1=-26431, sArr[][]=new short[N][N];
        float f=-1.924F;
        boolean b=false;
        byte by=-78, byArr[]=new byte[N];
        String str="three";
        Cls O2=new Cls(), O3=new Cls(), O4=new Cls(), O5=new Cls(), O6=new Cls(), O7=new Cls();

        FuzzerUtils.init(sArr, (short)11487);
        FuzzerUtils.init(byArr, (byte)-15);

        Test0087.iArrFld[(5 >>> 1) % N] = i6;
        i8 = 110;
        while (--i8 > 0) {
            i6 = i6;
            for (i9 = (int) (1); i9 < 14; ++i9) {
                i10 &= -8;
                for (i11 = (int) (1); i11 < 2; i11++) {
                    for (i13 = (int) (2); i13 > 1; i13--) {
                        for (d = (double) (1); d < 2; d++) {
                            Test0087.iArrFld[(int)(d)] |= i8;
                            i6 *= (int)Cls.instanceCount;
                        }
                        switch ((i9 % 10) + 31) {
                            case 31:
                                i15 >>>= i8;
                                for (i16 = (int) (2); 1 < i16; --i16) {
                                    sArr[i11][i11 + 1] -= (short)46338;
                                    Test0087.instanceCount = (long)i10;
                                    i17 -= (int)Test0087.instanceCount;
                                    Test0087.iArrFld[i11 + 1] = i6;
                                    i15 += (int)Cls.instanceCount;
                                    i6 = (int)Test0087.instanceCount;
                                    Test0087.fFld += (float)i13;
                                    i7 = (int)Test0087.instanceCount;
                                    i6 *= i13;
                                }
                                Test0087.iArrFld[i8 + 1] *= i14;
                                Test0087.fFld = (float)28530;
                                Cls.instanceCount = (long)-16033;
                                i15 = 54843;
                                Test0087.fFld = 103.47F;
                                break;
                            case 32:
                                break;
                            case 33:
                            case 34:
                                i10 = -18871;
                                Test0087.iArrFld[i8 - 1] += (int)Test0087.fFld;
                                break;
                            case 35:
                                for (f = (float) (2); f > 1; --f) {
                                    i17 -= i10;
                                    i6 >>= i15;
                                }
                                break;
                            case 36:
                                byArr[i8] -= (byte)i8;
                                break;
                            case 37:
                                Cls.instanceCount += (long)i15;
                                b = false;
                                i19 = 2;
                                while ((i19 -= 3) > 0) {
                                    Test0087.iArrFld[i19 + 1] -= (int)f;
                                    i10 = (int)by;
                                    Test0087.iArrFld[i19] |= i15;
                                    Test0087.fFld1 += (float)by;
                                    i20 = i11;
                                }
                                break;
                            case 38:
                                Test0087.iArrFld[i11] = i7;
                            case 39:
                                Cls.instanceCount <<= (long)i21;
                                break;
                            case 40:
                                str = str;
                                break;
                        }
                    }
                }
            }
        }
        vMeth2_check_sum += i6 + i7 + i8 + i9 + i10 + i11 + i12 + i13 + i14 + Double.doubleToLongBits(d) + i15 + i16 +
            i17 + s1 + Float.floatToIntBits(f) + i18 + (b ? 1 : 0) + i19 + by + i20 + i21 + str.length() +
            FuzzerUtils.checkSum(sArr) + FuzzerUtils.checkSum(byArr) + FuzzerUtils.checkSum(O2) +
            FuzzerUtils.checkSum(O3) + FuzzerUtils.checkSum(O4) + FuzzerUtils.checkSum(O5) + FuzzerUtils.checkSum(O6) +
            FuzzerUtils.checkSum(O7);
    }

    public void mainTest0087(String[] strArr1) {

        long meth_res = 0;
        int i=-4, i1=-7034, i2=14, i51=113, i52=-6, i53=29962, i54=44738, i55=-200, i56=0, i57=15;
        long l=-3L, l4=-3861916762L;
        short s=-11410, sArr1[]=new short[N];
        String str3="two", strArr2[]=new String[N];
        byte by3=67;
        double d4=0.91519, dArr1[]=new double[N];
        char cArr[]=new char[N];
        Cls O=new Cls(), O1=new Cls(), O24=new Cls(), O25=new Cls(), O26=new Cls();

        FuzzerUtils.init(cArr, (char)62983);
        FuzzerUtils.init(sArr1, (short)5042);
        FuzzerUtils.init(dArr1, -96.27388);
        FuzzerUtils.init(strArr2, "two");

        i = 1;
        while (++i < 116) {
            switch (((((--Test0087.iArrFld[i - 1]) >>> 1) % 7) * 5) + 37) {
                case 59:
                    Test0087.fFld = Test0087.fFld;
                    break;
                case 64:
                    synchronized (O) {
                        for (i1 = (int) (i); 1 < i1; --i1) {
                            Test0087.instanceCount *= (long)(((i1 - 20.98604) - Test0087.instanceCount) * ((s - i1) -
                                (++Cls.instanceCount)));
                            Cls.vMeth(i2, l, i2);
                            i2 = 2;
                            try {
                                Test0087.iArrFld[i1 - 1] = (Test0087.iArrFld[i] / i2);
                                i2 = (i1 / Test0087.iArrFld[i1]);
                                i2 = (i1 / i);
                            } catch (ArithmeticException a_e) {}
                            if (true) continue;
                            i2 = i2;
                        }
                        i51 = i;
                        while ((i51 -= 2) > 0) {
                            i2 <<= i1;
                            iFld &= (int)Test0087.instanceCount;
                            i52 = 2;
                            do {
                                iFld -= (int)Cls.cFld;
                                // Resetting String variable to a short value to prevent OOM
                                str3 = "";
                                str3 += str3;
                                by3 = (byte)i52;
                                switch ((i % 2) + 123) {
                                    case 123:
                                        i2 += (int)Test0087.fFld1;
                                        switch ((i52 % 8) + 120) {
                                            case 120:
                                                i2 = i2;
                                                if (Cls.bFld) {
                                                    Test0087.instanceCount += (long)-47;
                                                    for (i53 = (int) (1); i53 > 1; i53 -= 2) {
                                                        switch ((((i52 >>> 1) % 2) * 5) + 36) {
                                                            case 45:
                                                                Test0087.fFld1 *= (float)Cls.instanceCount;
                                                                iFld = i2;
                                                                // Resetting String variable to a short value to
                                                                // prevent OOM
                                                                str3 = "";
                                                                str3 += str3;
                                                                for (i55 = (int) (1); i55 > i53; i55--) {
                                                                    switch ((((i56 >>> 1) % 1) * 5) + 113) {
                                                                        case 118:
                                                                        default:
                                                                            switch ((i52 % 5) + 45) {
                                                                                case 45:
                                                                                    O25 = O24;
                                                                                    break;
                                                                                case 46:
                                                                                    d4 = (double)iFld;
                                                                                    s = (short)0.67F;
                                                                                    l <<= -2805120030936701454L;
                                                                                    Test0087.iArrFld[i53 - 1] +=
                                                                                        (int)Test0087.fFld1;
                                                                                    O1 = O1;
                                                                                    str3 = str3;
                                                                                    str3 = "four";
                                                                                    break;
                                                                                case 47:
                                                                                    iFld = -59378;
                                                                                    Test0087.fFld =
                                                                                        (float)Test0087.instanceCount;
                                                                                    Test0087.instanceCount = l4;
                                                                                    i2 %= (int)(i2 | 1);
                                                                                    iFld = i52;
                                                                                    switch (i55 % 4) {
                                                                                        case 0:
                                                                                            l -= (long)Test0087.fFld1;
                                                                                            iFld >>>= -27973;
                                                                                            switch (((53693 >>> 1) % 5)
                                                                                                + 56) {
                                                                                                case 56:
                                                                                                    iFld |= i52;
                                                                                                    break;
                                                                                                case 57:
                                                                                                case 58:
                                                                                                    i2 = (int)Test0087.fFld;
                                                                                                    switch ((i52 % 4) +
                                                                                                        49) {
                                                                                                        case 49:
                                                                                                            i56 = iFld;
                                                                                                            iFld =
                                                                                                                (int)Cls.sFld;
                                                                                                            i54 *= iFld;
                                                                                                            switch
                                                                                                                ((i53 %
                                                                                                                2) +
                                                                                                                21) {
  case 21:
      Test0087.instanceCount *= -2839352655L;
      Cls.instanceCount += (long)i56;
      break;
  case 22:
      i56 *= (int)l;
      if (false) continue;
      synchronized (O26) {
          cArr[i52 + 1] -= (char)i55;
          sArr1[i55] += (short)3;
      }
      i2 = i51;
      d4 = (double)i1;
      Test0087.fFld1 *= (float)d4;
      Test0087.iArrFld[i53] += i52;
      break;
                                                                                                            }
                                                                                                            fArrFld[i52
                                                                                                                + 1] +=
                                                                                                                (float)i51;
                                                                                                        case 50:
                                                                                                            d4 +=
                                                                                                                (double)i53;
                                                                                                            d4 =
                                                                                                                (double)54054;
                                                                                                            dArr1[i53 -
                                                                                                                1] =
                                                                                                                (double)i53;
                                                                                                            i54 =
                                                                                                                (int)s;
                                                                                                            switch
                                                                                                                (((i55
                                                                                                                >>> 1)
                                                                                                                % 1) +
                                                                                                                91) {
  case 91:
      iFld = i2;
      i57 %= (int)(i55 | 1);
      Test0087.fFld1 = Test0087.fFld1;
      break;
                                                                                                            }
                                                                                                            //
                                                                                                            // Resetting
                                                                                                            // String
                                                                                                            // variable
                                                                                                            // to a
                                                                                                            // short
                                                                                                            // value to
                                                                                                            // prevent
                                                                                                            // OOM
                                                                                                            str3 = "";
                                                                                                            str3 +=
                                                                                                                str3;
                                                                                                            break;
                                                                                                        case 51:
                                                                                                            O25 = O26;
                                                                                                            str3 = str3;
                                                                                                            i2 = i54;
                                                                                                            i57 -= 13;
                                                                                                           
                                                                                                                Test0087.instanceCount
                                                                                                                &=
                                                                                                                (long)i1;
                                                                                                            Test0087.fFld1
                                                                                                                *=
                                                                                                                -2.892F;
                                                                                                            break;
                                                                                                        case 52:
                                                                                                            i2 >>=
                                                                                                                (int)l;
                                                                                                    }
                                                                                                case 59:
                                                                                                    Cls.instanceCount =
                                                                                                        (long)Cls.sFld;
                                                                                                    break;
                                                                                                case 60:
                                                                                                    i56 =
                                                                                                        (int)Test0087.instanceCount;
                                                                                                default:
                                                                                                    Test0087.instanceCount
                                                                                                        *= (long)i1;
                                                                                            }
                                                                                            break;
                                                                                        case 1:
                                                                                            iFld = i52;
                                                                                            break;
                                                                                        case 2:
                                                                                            iFld = iFld;
                                                                                            break;
                                                                                        case 3:
                                                                                            i56 -= i54;
                                                                                            break;
                                                                                    }
                                                                                    break;
                                                                                case 48:
                                                                                    Test0087.fFld1 = (float)i54;
                                                                                    break;
                                                                                case 49:
                                                                                    i57 -= i57;
                                                                                    break;
                                                                            }
                                                                    }
                                                                }
                                                            case 40:
                                                                Test0087.iArrFld[i52] = i53;
                                                                break;
                                                            default:
                                                                Test0087.instanceCount = (long)i55;
                                                        }
                                                    }
                                                } else if (Cls.bFld) {
                                                    l4 -= (long)-59.220F;
                                                }
                                                break;
                                            case 121:
                                                d4 -= (double)Cls.sFld;
                                            case 122:
                                                try {
                                                    iFld = (Test0087.iArrFld[i52 - 1] % -1941454979);
                                                    i54 = (163 / i57);
                                                    Test0087.iArrFld[i51] = (i2 % Test0087.iArrFld[i]);
                                                } catch (ArithmeticException a_e) {}
                                                break;
                                            case 123:
                                            case 124:
                                            case 125:
                                                by3 *= (byte)i55;
                                            case 126:
                                                Test0087.fFld = (float)i57;
                                            case 127:
                                                strArr2[i - 1] = str3;
                                                break;
                                        }
                                        break;
                                    case 124:
                                        i54 = i;
                                }
                            } while (--i52 > 0);
                        }
                    }
                    break;
                case 68:
                    i57 -= -10;
                    break;
                case 53:
                    i56 += (int)l4;
                    break;
                case 40:
                    fArrFld[i + 1] += Test0087.fFld;
                case 52:
                    O26 = O1;
                case 61:
                    d4 -= (double)i56;
                    break;
            }
        }

        FuzzerUtils.out.println("i l i1 = " + i + "," + l + "," + i1);
        FuzzerUtils.out.println("i2 s i51 = " + i2 + "," + s + "," + i51);
        FuzzerUtils.out.println("l4 i52 str3 = " + l4 + "," + i52 + "," + str3.length());
        FuzzerUtils.out.println("by3 i53 i54 = " + by3 + "," + i53 + "," + i54);
        FuzzerUtils.out.println("i55 i56 d4 = " + i55 + "," + i56 + "," + Double.doubleToLongBits(d4));
        FuzzerUtils.out.println("i57 cArr sArr1 = " + i57 + "," + FuzzerUtils.checkSum(cArr) + "," +
            FuzzerUtils.checkSum(sArr1));
        FuzzerUtils.out.println("dArr1 strArr2 O = " + Double.doubleToLongBits(FuzzerUtils.checkSum(dArr1)) + "," +
            FuzzerUtils.checkSum(strArr2) + "," + FuzzerUtils.checkSum(O));
        FuzzerUtils.out.println("O1 O24 O25 = " + FuzzerUtils.checkSum(O1) + "," + FuzzerUtils.checkSum(O24) + "," +
            FuzzerUtils.checkSum(O25));
        FuzzerUtils.out.println("O26 Cls = " + FuzzerUtils.checkSum(O26) + "," + Cls.instanceCount);

        FuzzerUtils.out.println("Test0087.instanceCount Test0087.fFld Test0087.fFld1 = " + Test0087.instanceCount + "," +
            Float.floatToIntBits(Test0087.fFld) + "," + Float.floatToIntBits(Test0087.fFld1));
        FuzzerUtils.out.println("iFld Test0087.iArrFld fArrFld = " + iFld + "," + FuzzerUtils.checkSum(Test0087.iArrFld) + ","
            + Double.doubleToLongBits(FuzzerUtils.checkSum(fArrFld)));
        FuzzerUtils.out.println("Cls = " + Cls.instanceCount);

        FuzzerUtils.out.println("vMeth2_check_sum: " + vMeth2_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test0087 _instance = new Test0087();
            for (int i = 0; i < 10; i++ ) {
                try {
                    _instance.mainTest0087(strArr);
                 } catch (OutOfMemoryError ex) {
                    ex.printStackTrace(FuzzerUtils.err);
                    System.exit(1);
                 } catch (Exception ex) {
                    FuzzerUtils.out.println(ex.getClass().getCanonicalName());
                 }
             }
         } catch (Exception ex) {
            FuzzerUtils.out.println(ex.getClass().getCanonicalName());
         }
    }
}
///////////////////////////////////////////////////////////////////////
class Cls {

    public static final int N = 128;

    public static long instanceCount=-1844036383L;
    public static volatile short sFld=-32544;
    public static char cFld=31282;
    public static boolean bFld=false;
    public static String strArrFld[]=new String[N];
    public static int iArrFld1[]=new int[N];

    static {
        FuzzerUtils.init(Cls.strArrFld, "three");
        FuzzerUtils.init(Cls.iArrFld1, 0);
    }

    public static long vMeth_check_sum = 0;
    public static long vMeth1_check_sum = 0;

    public static void vMeth1(int i5) {

        long meth_res = 0;
        long l2=-1935107691151290735L, lArr[]=new long[N];
        int i22=165, i23=-11, i24=7, i25=-7, i26=206, i27=5, i28=12, i29=-7, i30=-19041, i31=-246, i32=-8, i33=-46229,
            i34=145, i35=-181, i36=150;
        String str1="one";
        double d1=0.120279, d2=-1.106232, dArr[]=new double[N];
        byte by1=-42;
        boolean b1=false;
        Object OArr[]=new Object[23];
        Cls O8=new Cls(), O9=new Cls(), O10=new Cls(), O11=new Cls(), O12=new Cls(), O13=new Cls(), O14=new Cls(),
            O15=new Cls(), O16=new Cls();

        FuzzerUtils.init(lArr, -252L);
        FuzzerUtils.init(dArr, -55.112863);
        FuzzerUtils.init(OArr, new Test0087());

        Test0087.vMeth2(i5, i5);
        for (l2 = (long) (6); l2 < 113; l2 += 2) {
            Cls.strArrFld[(int)(l2)] += str1;
            for (i23 = (int) (1); i23 < 29; i23++) {
                Test0087.fFld += (float)i24;
            }
            str1 = str1;
            i5 = i22;
            synchronized (O10) {
                for (d1 = (double) (29); d1 > 1; --d1) {
                    // Resetting String variable to a short value to prevent OOM
                    str1 = "";
                    str1 += "three";
                    for (i27 = (int) (2); i27 > 1; i27 -= 3) {
                        lArr[(int)(d1)] = Test0087.instanceCount;
                        i29 = 2;
                        while ((i29 -= 3) > 0) {
                            Test0087.fFld += (float)i24;
                        }
                        for (i30 = (int) (i27); i30 < 2; i30 += 3) {
                            O11 = O8;
                            d2 -= (double)i28;
                            Cls.iArrFld1[i30 + 1] -= i5;
                            Cls.iArrFld1 = Cls.iArrFld1;
                            Test0087.fFld1 -= (float)i23;
                            synchronized (O14) {
                                i28 += -133;
                                Cls.instanceCount *= Test0087.instanceCount;
                            }
                            i26 -= (int)Test0087.instanceCount;
                        }
                        i5 = i25;
                        i25 <<= (int)l2;
                    }
                    i32 = i26;
                    i26 -= i23;
                    // Resetting String variable to a short value to prevent OOM
                    str1 = "";
                    str1 += str1;
                    Cls.iArrFld1[(int)(d1)] += i24;
                    switch ((int)((l2 % 10) + 71)) {
                        case 71:
                            dArr[(int)(l2 - 1)] += (double)i28;
                            i5 = (int)l2;
                            Test0087.instanceCount = (long)i29;
                            Cls.iArrFld1[(int)(d1 - 1)] += -87;
                            switch ((int)((l2 % 3) + 115)) {
                                case 115:
                                    Cls.instanceCount *= (long)i32;
                                    Cls.iArrFld1[(int)(l2 + 1)] = i28;
                                    Cls.instanceCount *= (long)i25;
                                    for (i33 = (int) (1); i33 < 2; i33 += 3) {
                                        d2 = (double)Test0087.fFld;
                                        i25 = i24;
                                        for (i35 = (int) (1); i35 < 2; ++i35) {
                                            if (i22 != 0) {
                                                vMeth1_check_sum += i5 + l2 + i22 + str1.length() + i23 + i24 + i25 +
                                                    Double.doubleToLongBits(d1) + i26 + i27 + i28 + i29 + i30 + i31 +
                                                    by1 + Double.doubleToLongBits(d2) + i32 + i33 + i34 + i35 + i36 +
                                                    (b1 ? 1 : 0) + FuzzerUtils.checkSum(lArr) +
                                                    Double.doubleToLongBits(FuzzerUtils.checkSum(dArr)) +
                                                    FuzzerUtils.checkSum(OArr) + FuzzerUtils.checkSum(O8) +
                                                    FuzzerUtils.checkSum(O9) + FuzzerUtils.checkSum(O10) +
                                                    FuzzerUtils.checkSum(O11) + FuzzerUtils.checkSum(O12) +
                                                    FuzzerUtils.checkSum(O13) + FuzzerUtils.checkSum(O14) +
                                                    FuzzerUtils.checkSum(O15) + FuzzerUtils.checkSum(O16);
                                                return;
                                            }
                                            str1 = str1;
                                        }
                                    }
                                    break;
                                case 116:
                                    str1 = "two";
                                    break;
                                case 117:
                                default:
                                    Cls.sFld = Cls.sFld;
                            }
                        case 72:
                            i36 += i34;
                            break;
                        case 73:
                        case 74:
                            Cls.iArrFld1[(int)(l2 + 1)] -= (int)d2;
                            break;
                        case 75:
                            by1 = (byte)i34;
                        case 76:
                            b1 = b1;
                        case 77:
                            i5 = (int)-146L;
                            break;
                        case 78:
                            OArr = OArr;
                            break;
                        case 79:
                            by1 += (byte)8L;
                            break;
                        case 80:
                            Cls.cFld = (char)i24;
                            break;
                    }
                }
            }
        }
        vMeth1_check_sum += i5 + l2 + i22 + str1.length() + i23 + i24 + i25 + Double.doubleToLongBits(d1) + i26 + i27 +
            i28 + i29 + i30 + i31 + by1 + Double.doubleToLongBits(d2) + i32 + i33 + i34 + i35 + i36 + (b1 ? 1 : 0) +
            FuzzerUtils.checkSum(lArr) + Double.doubleToLongBits(FuzzerUtils.checkSum(dArr)) +
            FuzzerUtils.checkSum(OArr) + FuzzerUtils.checkSum(O8) + FuzzerUtils.checkSum(O9) +
            FuzzerUtils.checkSum(O10) + FuzzerUtils.checkSum(O11) + FuzzerUtils.checkSum(O12) +
            FuzzerUtils.checkSum(O13) + FuzzerUtils.checkSum(O14) + FuzzerUtils.checkSum(O15) +
            FuzzerUtils.checkSum(O16);
    }

    public static void vMeth(int i3, long l1, int i4) {

        long meth_res = 0;
        long l3=-182L;
        int i37=168, i38=-7, i39=-12, i40=-1, i41=9, i42=-3, i43=-6, i44=59239, i45=-20092, i46=142, i47=8, i48=47,
            i49=10, i50=-38810;
        float f1=0.514F, fArr[][]=new float[N][N];
        byte by2=-112;
        double d3=1.22723;
        Cls O17=new Cls(), O18=new Cls(), O19=new Cls(), O20=new Cls(), O21=new Cls(), O22=new Cls(), O23=new Cls();

        FuzzerUtils.init(fArr, 0.141F);

        Cls.instanceCount *= (long)i3;
        vMeth1(i4);
        for (l3 = (long) (120); l3 > 6; l3--) {
            i4 += (int)Cls.cFld;
            i37 = (int)Cls.cFld;
            switch (((i3 >>> 1) % 5) + 52) {
                case 52:
                    i4 *= i4;
                    break;
                case 53:
                    for (i38 = (int) (14); i38 > l3; i38--) {
                    }
                    synchronized (O19) {
                        i41 = 14;
                        while ((i41 -= 3) > 0) {
                            String str2="one";
                            i40 = i4;
                            i40 = -36236;
                            str2 = str2;
                            synchronized (O20) {
                                O20 = O20;
                                for (i42 = (int) (1); i42 < 3; i42 += 2) {
                                }
                                synchronized (O22) {
                                    for (i45 = (int) (1); i45 < 3; i45++) {
                                        if (Cls.bFld) break;
                                        i40 += i46;
                                        str2 = str2;
                                        i44 += (int)Cls.cFld;
                                    }
                                    fArr[(int)(l3 - 1)][i41 + 1] += (float)-37204L;
                                    i39 = i42;
                                }
                                switch ((int)((l3 % 3) + 40)) {
                                    case 40:
                                        i47 = 3;
                                        while ((i47 -= 3) > 0) {
                                            try {
                                                i37 = (i47 % -1704);
                                                i39 = (9648 % i43);
                                                i44 = (i46 % -65384);
                                            } catch (ArithmeticException a_e) {}
                                            Test0087.instanceCount *= (long)i3;
                                            f1 += (float)i45;
                                            i48 = 3;
                                            while ((i48 -= 2) > 0) {
                                                by2 += (byte)Cls.cFld;
                                                fArr[(int)(l3)] = fArr[i48 + 1];
                                                i43 = (int)Test0087.fFld1;
                                                if (Cls.bFld) break;
                                                i4 = (int)Cls.instanceCount;
                                                Cls.iArrFld1[i41 - 1] <<= i3;
                                                Cls.sFld = (short)i42;
                                            }
                                            Test0087.instanceCount = (long)i48;
                                            i44 >>= (int)by2;
                                            d3 -= d3;
                                        }
                                        str2 = str2;
                                        break;
                                    case 41:
                                        if (false) continue;
                                        break;
                                    case 42:
                                        i4 >>>= i45;
                                }
                            }
                        }
                    }
                    break;
                case 54:
                    f1 += (float)i49;
                    break;
                case 55:
                    Cls.sFld ^= (short)i50;
                case 56:
                    Test0087.instanceCount += (long)Test0087.fFld;
                    break;
                default:
                    Cls.iArrFld1 = Cls.iArrFld1;
            }
        }
        vMeth_check_sum += i3 + l1 + i4 + l3 + i37 + i38 + i39 + i40 + i41 + Float.floatToIntBits(f1) + i42 + i43 + i44
            + i45 + i46 + i47 + i48 + by2 + Double.doubleToLongBits(d3) + i49 + i50 +
            Double.doubleToLongBits(FuzzerUtils.checkSum(fArr)) + FuzzerUtils.checkSum(O17) + FuzzerUtils.checkSum(O18)
            + FuzzerUtils.checkSum(O19) + FuzzerUtils.checkSum(O20) + FuzzerUtils.checkSum(O21) +
            FuzzerUtils.checkSum(O22) + FuzzerUtils.checkSum(O23);
    }

}
///////////////////////////////////////////////////////////////////////
//DEBUG  Test0087 ->  Test0087
//DEBUG  main ->  main
//DEBUG  mainTest0087 ->  mainTest0087
//DEBUG  Cls ->  Cls vMeth2 vMeth1 vMeth mainTest0087
//DEBUG  vMeth ->  vMeth mainTest0087
//DEBUG  vMeth1 ->  vMeth1 vMeth mainTest0087
//DEBUG  vMeth2 ->  vMeth2 vMeth1 vMeth mainTest0087
//DEBUG  Depth = 4
//DEBUG  Classes = 2
//DEBUG  static objects = {}
