// 2025-10-22 14:11:36
// This file is generated by LLM based on the context (project/cbt/statement/4.txt) below:
//     How to use the 'indexOf' in Java programs 

public class Mutator22 {
    public static int $priority = 50;
    
    public static void $mut1(int $lval1, String $lval2, int $expr3) {
        $lval1 = $lval2.indexOf($expr3);
    }

    public static void $mut1(int $lval1, String $lval2, int $expr3, int $expr4) {
        $lval1 = $lval2.indexOf($expr3,$expr4);
    }
}