// 2025-10-22 14:11:26
// This file is generated by LLM based on the context (project/cbt/statement/2.txt) below:
//     How to use the length function (The length function of an array) in Java programs

public class Mutator15 {
    public static int $priority = 50;
    public static void $mut1(int $lval1, Object[] $lval2) {
        $lval1 = $lval2.length;
    }
}