// 2025-10-22 14:11:03
// This file is generated by LLM based on the context (project/cbt/statement/5.txt) below:
//     How to use the Arrays.fill in Java programs 

import java.util.Arrays;

public class Mutator3 {
    public static int $priority = 95;    

    public static void $mut10(int[] $lval1, int $expr2, int $expr3, int $expr4) {
        Arrays.fill($lval1, $expr2, $expr3, $expr4);
    }

    public static void $mut11(long[] $lval1, int $expr2, int $expr3, long $expr4) {
        Arrays.fill($lval1, $expr2, $expr3, $expr4);
    }

    public static void $mut12(float[] $lval1, int $expr2, int $expr3, float $expr4) {
        Arrays.fill($lval1, $expr2, $expr3, $expr4);
    }

    public static void $mut13(double[] $lval1, int $expr2, int $expr3, double $expr4) {
        Arrays.fill($lval1, $expr2, $expr3, $expr4);
    }

    public static void $mut14(char[] $lval1, int $expr2, int $expr3, char $expr4) {
        Arrays.fill($lval1, $expr2, $expr3, $expr4);
    }

    public static void $mut15(byte[] $lval1, int $expr2, int $expr3, byte $expr4) {
        Arrays.fill($lval1, $expr2, $expr3, $expr4);
    }

    public static void $mut16(short[] $lval1, int $expr2, int $expr3, short $expr4) {
        Arrays.fill($lval1, $expr2, $expr3, $expr4);
    }

    public static void $mut17(boolean[] $lval1, int $expr2, int $expr3, boolean $expr4) {
        Arrays.fill($lval1, $expr2, $expr3, $expr4);
    }

    public static void $mut18(Object[] $lval1, int $expr2, int $expr3, Object $expr4) {
        Arrays.fill($lval1, $expr2, $expr3, $expr4);
    }


}