// Generated by Java* Fuzzer test generator (1.0.001). Sun Mar 29 19:37:00 2026
public class Test0014 {

    public static final int N = 128;

    public static long instanceCount=2L;
    public static short sFld=-18898;
    public static double dFld=-1.47105;
    public static byte byFld=-72;
    public static long lFld=-91L;
    public static boolean bFld=true;
    public static String strFld="three";
    public static int iFld=23242;
    public static char cFld=12081;
    public static float fFld=-73.953F;
    public static int iFld1=-12;
    public int iFld2=928;
    public static float fArrFld[]=new float[N];
    public static double dArrFld[]=new double[N];
    public static String strArrFld[]=new String[N];
    public int iArrFld[]=new int[N];
    public static char cArrFld[]=new char[N];

    static {
        FuzzerUtils.init(Test0014.fArrFld, 2.299F);
        FuzzerUtils.init(Test0014.dArrFld, 46.78561);
        FuzzerUtils.init(Test0014.strArrFld, "four");
        FuzzerUtils.init(Test0014.cArrFld, (char)13028);
    }

    public static long vMeth_check_sum = 0;
    public static long iMeth_check_sum = 0;
    public static long iMeth1_check_sum = 0;

    public static int iMeth1(long l2) {

        long meth_res = 0;
        int i5=44761, i6=-62478, i7=187, i8=-15442, i9=-94, i10=-115, i11=-10, i12=10, i13=-10, i14=-39, i15=-15143,
            i16=-48, i17=-36693, i18=17835, i19=0, i20=-7, i21=1, i22=-3, i23=-51547, i24=-23385, i25=-228, iArr2[]=new
            int[N];
        float f1=0.542F;
        char c=37405, cArr[]=new char[N];
        boolean b=true;
        String str1="four";
        long lArr[]=new long[N];
        Object OArr[]=new Object[91];
        Cls O=new Cls(), O1=new Cls(), O2=new Cls(), O3=new Cls(), O4=new Cls(), O5=new Cls(), O6=new Cls(), O7=new
            Cls(), O8=new Cls();

        FuzzerUtils.init(iArr2, -138);
        FuzzerUtils.init(lArr, 225L);
        FuzzerUtils.init(OArr, new Cls());
        FuzzerUtils.init(cArr, (char)5095);

        synchronized (O) {
            switch (((i5 >>> 1) % 9) + 110) {
                case 110:
                case 111:
                    i6 = 126;
                    while ((i6 -= 3) > 0) {
                        i5 = i5;
                        i5 -= i5;
                        i7 = 1;
                        while ((i7 += 2) < 36) {
                            switch (((i8 >>> 1) % 2) + 114) {
                                case 114:
                                    switch (((i7 >>> 1) % 5) + 88) {
                                        case 88:
                                        case 89:
                                            for (i9 = (int) (2); i9 > 1; i9 -= 2) {
                                                i5 -= i10;
                                                i8 ^= i7;
                                                for (i11 = (int) (2); 1 < i11; i11 -= 2) {
                                                    iArr2[i6 - 1] = (int)Test0014.dFld;
                                                }
                                                lArr[i6] += (long)i7;
                                            }
                                            for (i13 = (int) (2); 1 < i13; i13--) {
                                                f1 -= (float)14L;
                                                c -= (char)Test0014.sFld;
                                                for (i15 = (int) (1); i15 < 2; i15++) {
                                                    l2 *= (long)-178;
                                                    Cls.instanceCount = (long)Test0014.byFld;
                                                }
                                                b = b;
                                            }
                                            try {
                                                for (i17 = (int) (2); i17 > 1; --i17) {
                                                    for (i19 = (int) (2); i19 > 1; --i19) {
                                                        f1 -= (float)i20;
                                                        i8 -= (int)l2;
                                                        for (i21 = (int) (2); i21 > 1; i21 -= 3) {
                                                            if (false) break;
                                                            i10 = (int)f1;
                                                        }
                                                        switch ((((i15 >>> 1) % 4) * 5) + 88) {
                                                            case 106:
                                                                Cls.instanceCount -= (long)i15;
                                                                iArr2[i6 + 1] *= i5;
                                                                Test0014.dFld = (double)l2;
                                                                f1 *= (float)l2;
                                                                i12 -= i14;
                                                                i10 *= 193;
                                                                lArr[i7] -= l2;
                                                                break;
                                                            case 93:
                                                                if (i13 != 0) {
                                                                }
                                                                OArr[(i8 >>> 1) % 91] = new Cls();
                                                                for (i23 = (int) (2); i23 > 1; i23 -= 3) {
                                                                    Test0014.instanceCount = l2;
                                                                    Test0014.instanceCount = Cls.instanceCount;
                                                                    i24 += i5;
                                                                    i20 *= -65243;
                                                                    if (true) continue;
                                                                    str1 = str1;
                                                                }
                                                            case 92:
                                                                // Resetting String variable to a short value to
                                                                // prevent OOM
                                                                str1 = "";
                                                                str1 += str1;
                                                                break;
                                                            case 90:
                                                                i12 >>= i16;
                                                            default:
                                                                if (i5 != 0) {
                                                                }
                                                        }
                                                    }
                                                }
                                            }
                                            catch (ArithmeticException exc22) {
                                                f1 *= (float)-8;
                                            }
                                            break;
                                        case 90:
                                            l2 = (long)14;
                                            break;
                                        case 91:
                                            i8 *= (int)Test0014.lFld;
                                        case 92:
                                            i18 >>>= (int)l2;
                                            break;
                                        default:
                                            cArr[i7 - 1] = (char)i24;
                                    }
                                    break;
                                case 115:
                                    iArr2 = iArr2;
                            }
                        }
                    }
                    break;
                case 112:
                    i12 *= 25470;
                    break;
                case 113:
                    Test0014.dFld += (double)i25;
                case 114:
                    i18 = (int)Test0014.instanceCount;
                case 115:
                    i5 += (int)f1;
                    break;
                case 116:
                    i18 = -12;
                    break;
                case 117:
                    iArr2[(i13 >>> 1) % N] += i18;
                    break;
                case 118:
                    str1 = str1;
                    break;
            }
        }
        meth_res = l2 + i5 + i6 + i7 + i8 + i9 + i10 + i11 + i12 + i13 + i14 + Float.floatToIntBits(f1) + (int)c + i15
            + i16 + (b ? 1 : 0) + i17 + i18 + i19 + i20 + i21 + i22 + i23 + i24 + str1.length() + i25 +
            FuzzerUtils.checkSum(iArr2) + FuzzerUtils.checkSum(lArr) + FuzzerUtils.checkSum(OArr) +
            FuzzerUtils.checkSum(cArr) + FuzzerUtils.checkSum(O) + FuzzerUtils.checkSum(O1) + FuzzerUtils.checkSum(O2)
            + FuzzerUtils.checkSum(O3) + FuzzerUtils.checkSum(O4) + FuzzerUtils.checkSum(O5) + FuzzerUtils.checkSum(O6)
            + FuzzerUtils.checkSum(O7) + FuzzerUtils.checkSum(O8);
        iMeth1_check_sum += meth_res;
        return (int)meth_res;
    }

    public static int iMeth(int i3, long l1) {

        long meth_res = 0;
        int i4=4, i26=208, i27=48649, i28=-1213, i29=10, i30=-172, i31=-120, iArr1[]=new int[N];
        float f2=59.535F, f3=-4.449F;
        long lArr1[]=new long[N];
        Cls O9=new Cls(), O10=new Cls(), O11=new Cls();

        FuzzerUtils.init(iArr1, 4534);
        FuzzerUtils.init(lArr1, 198L);

        i4 = 1;
        while (++i4 < 118) {
            iArr1[i4] *= (-iMeth1(l1));
            Test0014.dFld = (double)19845L;
            if (Test0014.bFld) continue;
            f2 = 1;
            do {
                i3 = i3;
                lArr1[(int)(f2 + 1)] = (long)i3;
                for (i26 = (int) (1); i26 > 1; --i26) {
                    iArr1[i4] /= (int)(i3 | 1);
                    for (i28 = (int) (1); 1 < i28; i28 -= 3) {
                        for (i30 = (int) (1); 1 < i30; i30 -= 3) {
                            int i32=11;
                            Test0014.dArrFld[i4 - 1] += (double)i31;
                            switch ((i26 % 9) + 107) {
                                case 107:
                                    i31 <<= 41;
                                    Test0014.instanceCount = (long)Test0014.dFld;
                                    Test0014.strFld = Test0014.strFld;
                                    f3 = (float)i4;
                                    i3 -= (int)39.22609;
                                    i27 >>= i30;
                                    if (Test0014.bFld) break;
                                    break;
                                case 108:
                                    Test0014.sFld = (short)i30;
                                    switch (((i26 % 2) * 5) + 33) {
                                        case 34:
                                            i27 = i26;
                                            i3 += (int)Cls.instanceCount;
                                            i31 = (int)Cls.instanceCount;
                                            break;
                                        case 38:
                                            l1 <<= (long)-120;
                                            Test0014.strFld = "three";
                                            switch ((i30 % 4) + 102) {
                                                case 102:
                                                    Test0014.sFld -= (short)i29;
                                                    break;
                                                case 103:
                                                    break;
                                                case 104:
                                                    i29 = (int)Test0014.instanceCount;
                                                    l1 = (long)Test0014.sFld;
                                                    l1 = (long)i29;
                                                    f3 = (float)i27;
                                                    f3 += (float)i4;
                                                    Test0014.bFld = Test0014.bFld;
                                                    lArr1[i30] += (long)f3;
                                                    i31 -= 43816;
                                                    break;
                                                case 105:
                                                    switch (((i30 >>> 1) % 4) + 62) {
                                                        case 62:
                                                            i31 += i29;
                                                            // Resetting String variable to a short value to prevent OOM
                                                            Test0014.strFld = "";
                                                            Test0014.strFld += Test0014.strFld;
                                                            Test0014.dFld += (double)65348;
                                                        case 63:
                                                            Test0014.dFld = (double)i30;
                                                            break;
                                                        case 64:
                                                            Test0014.instanceCount <<= Test0014.lFld;
                                                            break;
                                                        case 65:
                                                            Test0014.lFld ^= (long)0;
                                                            break;
                                                    }
                                                    break;
                                                default:
                                                    i3 -= Test0014.iFld;
                                            }
                                            break;
                                    }
                                case 109:
                                    Test0014.dFld += (double)-4;
                                    break;
                                case 110:
                                    i3 >>= Test0014.iFld;
                                    break;
                                case 111:
                                    Test0014.strArrFld[i26] = Test0014.strFld;
                                    break;
                                case 112:
                                    Test0014.fArrFld[i4 - 1] = (float)i28;
                                    break;
                                case 113:
                                    lArr1[i4] += (long)Test0014.iFld;
                                case 114:
                                    iArr1[i4] += (int)Test0014.byFld;
                                    break;
                                case 115:
                                    break;
                            }
                        }
                    }
                }
            } while (++f2 < 13);
        }
        meth_res = i3 + l1 + i4 + Float.floatToIntBits(f2) + i26 + i27 + i28 + i29 + i30 + i31 +
            Float.floatToIntBits(f3) + FuzzerUtils.checkSum(iArr1) + FuzzerUtils.checkSum(lArr1) +
            FuzzerUtils.checkSum(O9) + FuzzerUtils.checkSum(O10) + FuzzerUtils.checkSum(O11);
        iMeth_check_sum += meth_res;
        return (int)meth_res;
    }

    public static void vMeth(int i, int i1, long l) {

        long meth_res = 0;
        int i2=-157, i33=-238, i34=2, i35=217, i36=3, i37=-18, i38=248, i39=62248, i40=64800, i41=-11, i42=-164, i43=6,
            i44=-24791, iArr[]=new int[N];
        long l3=-2L, lArr2[][]=new long[N][N];
        float f4=0.544F;
        char c2=21899;
        Cls O12=new Cls(), O13=new Cls();

        FuzzerUtils.init(iArr, 4);
        FuzzerUtils.init(lArr2, -3203556471L);

        for (float f : Test0014.fArrFld) {
            try {
                iArr[(i >>> 1) % N] = (i % i);
                i1 = (17104 % i);
                i = (-725264638 % i1);
            } catch (ArithmeticException a_e) {}
            i |= (((i1++) + Test0014.sFld) * (iArr[(i1 >>> 1) % N] - i));
            i2 = 12;
            while (--i2 > 0) {
                String str="four";
                i1 = (int)((f + Test0014.instanceCount) - (-12 + (i1 + i2)));
                str = (str += str);
                // Resetting String variable to a short value to prevent OOM
                str = "hhhh";
                str += str;
            }
            Test0014.dFld *= (double)((i -= iMeth(46598, l3)) - i2);
            f += (float)i2;
        }
        i33 = 1;
        while (++i33 < 122) {
            for (i34 = (int) (1); i34 < 13; ++i34) {
                Test0014.iFld = Test0014.iFld;
                Test0014.iFld += (int)l3;
                i35 -= Test0014.iFld;
                switch ((i33 % 7) + 47) {
                    case 47:
                        i36 = 1;
                        while (++i36 < 2) {
                            l = (long)i2;
                            Test0014.lFld -= (long)9869;
                            Test0014.iFld = (int)4L;
                        }
                        try {
                            i37 = 1;
                            do {
                                for (i38 = (int) ((long)1 + (long)128); i38 > i37; i38--) {
                                    Test0014.cFld = (char)86;
                                }
                                i1 >>= (int)Test0014.lFld;
                                iArr = FuzzerUtils.int1array(N, (int)-27);
                                f4 = (float)i38;
                                try {
                                    i35 = (i35 % -160);
                                    Test0014.iFld = (i38 / i40);
                                    i = (10375 / i1);
                                } catch (ArithmeticException a_e) {}
                                i39 += -39;
                                if (Test0014.bFld) {
                                    lArr2[i37 + 1][i37 + 1] >>= (long)i33;
                                    try {
                                        i41 = 1;
                                        do {
                                            i35 = 201;
                                            Test0014.dArrFld = Test0014.dArrFld;
                                            Test0014.strArrFld[i33] += Test0014.strFld;
                                            switch ((i33 % 6) + 2) {
                                                case 2:
                                                    i42 = 1;
                                                    do {
                                                        i += i43;
                                                        Test0014.instanceCount *= (long)Test0014.dFld;
                                                    } while (++i42 < 1);
                                                    Test0014.bFld = Test0014.bFld;
                                                    i44 = 1;
                                                    while (--i44 > 0) {
                                                        if (Test0014.bFld) break;
                                                    }
                                                    break;
                                                case 3:
                                                    // Resetting String variable to a short value to prevent OOM
                                                    Test0014.strFld = "";
                                                    Test0014.strFld += "three";
                                                    break;
                                                case 4:
                                                    break;
                                                case 5:
                                                    i1 -= Test0014.iFld;
                                                    break;
                                                case 6:
                                                    i1 *= (int)Test0014.instanceCount;
                                                    break;
                                                case 7:
                                                    break;
                                                default:
                                                    Test0014.bFld = false;
                                            }
                                        } while (--i41 > 0);
                                    }
                                    catch (NullPointerException exc23) {
                                        i39 = -57657;
                                    }
                                } else {
                                    Test0014.strArrFld[(i1 >>> 1) % N] = Test0014.strFld;
                                }
                            } while (++i37 < 2);
                        }
                        catch (ArrayIndexOutOfBoundsException exc24) {
                            i35 = (int)l3;
                        }
                        catch (NullPointerException exc25) {
                            f4 = (float)-4;
                        }
                        finally {
                            c2 = (char)Test0014.iFld;
                        }
                        break;
                    case 48:
                        f4 = (float)-6088;
                        break;
                    case 49:
                        break;
                    case 50:
                        l3 >>>= Test0014.lFld;
                        break;
                    case 51:
                    case 52:
                        i35 = (int)Test0014.instanceCount;
                        break;
                    case 53:
                        Test0014.dFld -= (double)Test0014.iFld;
                    default:
                        lArr2[i33][i33 + 1] *= Test0014.lFld;
                }
            }
        }
        vMeth_check_sum += i + i1 + l + i2 + l3 + i33 + i34 + i35 + i36 + i37 + i38 + i39 + Float.floatToIntBits(f4) +
            i40 + i41 + i42 + i43 + i44 + (int)c2 + FuzzerUtils.checkSum(iArr) + FuzzerUtils.checkSum(lArr2) +
            FuzzerUtils.checkSum(O12) + FuzzerUtils.checkSum(O13);
    }

    public void mainTest0014(String[] strArr1) {

        long meth_res = 0;
        int i45=-7, i46=38381, i47=-60262, i48=-31951, i49=-64, i50=-39993, i51=-20541, i52=222, i53=22, i54=87,
            i55=-37374, i56=13, i57=0, i58=-9, i59=-9021, i60=-56102, i61=-209, i62=-7;
        long l4=4L, lArr3[][]=new long[N][N];
        float f5=-2.39F;
        Cls O14=new Cls(), O15=new Cls(), O16=new Cls(), O17=new Cls(), O18=new Cls(), O19=new Cls(), O20=new Cls(),
            O21=new Cls(), O22=new Cls();

        FuzzerUtils.init(lArr3, -28500L);

        vMeth(Test0014.iFld, Test0014.iFld, Cls.instanceCount);
        for (i45 = (int) (90); i45 > 5; i45 -= 3) {
            iArrFld[i45 + 1] = i46;
            for (l4 = (long) (5); l4 < 126; l4 += 3) {
                for (i48 = (int) (1); 23 > i48; ++i48) {
                    i46 = (int)-10L;
                    synchronized (O17) {
                        f5 *= (float)i50;
                        iArrFld[(int)(l4 + 1)] >>>= (int)Cls.instanceCount;
                        i46 <<= (int)Test0014.sFld;
                        Cls.instanceCount = (long)i45;
                        i46 *= (int)Test0014.byFld;
                        for (i51 = (int) (1); i51 < 2; i51 += 2) {
                            i46 = i51;
                            Test0014.strArrFld[i51] = "four";
                            if (true) continue;
                            Test0014.instanceCount -= (long)i50;
                            i47 *= (int)-91.708F;
                            f5 *= (float)i45;
                        }
                        i49 *= (int)Test0014.lFld;
                    }
                    switch ((int)(((l4 % 10) * 5) + 6)) {
                        case 53:
                            i46 = i52;
                            switch ((int)(((l4 % 6) * 5) + 26)) {
                                case 44:
                                    iArrFld[i48] += i50;
                                    Test0014.sFld *= (short)i48;
                                    synchronized (O19) {
                                        Test0014.byFld *= (byte)Test0014.dFld;
                                        iArrFld[(i49 >>> 1) % N] += Test0014.iFld;
                                        iArrFld[i45 + 1] = -9;
                                        i54 = 2;
                                        do {
                                            switch (((i54 >>> 1) % 8) + 77) {
                                                case 77:
                                                    for (i55 = (int) (1); i55 < 1; i55 += 2) {
                                                        Test0014.iFld = 2;
                                                        iArrFld[i48 + 1] <<= 13;
                                                    }
                                                    iArrFld[i48 - 1] *= i55;
                                                    i52 = (int)f5;
                                                    for (i57 = (int) (1); i57 > 1; i57--) {
                                                        i50 |= i59;
                                                        Test0014.dArrFld[i45 + 1] -= (double)56610;
                                                        Test0014.dFld -= (double)i58;
                                                    }
                                                    Test0014.cFld -= (char)i51;
                                                    Cls.instanceCount = (long)i47;
                                                    synchronized (O22) {
                                                        i61 = 1;
                                                        while (--i61 > 0) {
                                                            switch ((int)(((l4 % 5) * 5) + 88)) {
                                                                case 92:
                                                                    switch ((i45 % 6) + 116) {
                                                                        case 116:
                                                                            Test0014.iFld = (int)1.26F;
                                                                            i53 &= 62783;
                                                                            Test0014.strArrFld[i61] = Test0014.strFld;
                                                                            i47 &= i47;
                                                                            Test0014.bFld = Test0014.bFld;
                                                                            i53 = 77;
                                                                            break;
                                                                        case 117:
                                                                            Test0014.instanceCount = (long)i57;
                                                                            f5 *= (float)i48;
                                                                            i59 = (int)0.55534;
                                                                            lArr3[i45 + 1][i48 - 1] ^= (long)i58;
                                                                            break;
                                                                        case 118:
                                                                            i46 *= (int)Test0014.cFld;
                                                                            if (Test0014.bFld) continue;
                                                                            Test0014.strArrFld[i54 - 1] = Test0014.strFld;
                                                                            break;
                                                                        case 119:
                                                                            Test0014.instanceCount = (long)i50;
                                                                            break;
                                                                        case 120:
                                                                            switch ((i45 % 8) + 13) {
                                                                                case 13:
                                                                                    i56 >>= (int)Test0014.instanceCount;
                                                                                    iArrFld[i61] = i54;
                                                                                    // Resetting String variable to a
                                                                                    // short value to prevent OOM
                                                                                    Test0014.strFld = "";
                                                                                    Test0014.strFld += Test0014.strFld;
                                                                                    i59 *= (int)f5;
                                                                                    Test0014.byFld -= (byte)i54;
                                                                                    Test0014.iFld &= (int)Test0014.lFld;
                                                                                case 14:
                                                                                    i60 = i53;
                                                                                    Test0014.instanceCount = (long)-2;
                                                                                    i56 ^= -5235;
                                                                                    Test0014.cArrFld[i54 + 1] *=
                                                                                        (char)-4019805267L;
                                                                                    Test0014.byFld -= (byte)f5;
                                                                                    break;
                                                                                case 15:
                                                                                    iArrFld[i45] =
                                                                                        (int)Cls.instanceCount;
                                                                                    i59 += i48;
                                                                                    i49 <<= i48;
                                                                                    break;
                                                                                case 16:
                                                                                    switch (((i45 % 2) * 5) + 23) {
                                                                                        case 28:
                                                                                            Test0014.iFld += 14;
                                                                                            Cls.instanceCount =
                                                                                                Test0014.lFld;
                                                                                            lArr3 = lArr3;
                                                                                            break;
                                                                                        case 25:
                                                                                            Test0014.iFld = (int)l4;
                                                                                            switch (((i61 % 8) * 5) +
                                                                                                116) {
                                                                                                case 123:
                                                                                                    i46 = Test0014.iFld;
                                                                                                    break;
                                                                                                case 155:
                                                                                                    Test0014.instanceCount
                                                                                                        &= (long)-178;
                                                                                                    iArrFld[i48 + 1] -=
                                                                                                        (int)f5;
                                                                                                    iArrFld = iArrFld;
                                                                                                    i60 +=
                                                                                                        (int)Test0014.fFld;
                                                                                                    break;
                                                                                                case 130:
                                                                                                    lArr3[(int)(l4 -
                                                                                                        1)][i61 - 1] =
                                                                                                        Test0014.instanceCount;
                                                                                                    break;
                                                                                                case 126:
                                                                                                case 154:
                                                                                                    break;
                                                                                                case 141:
                                                                                                    i60 = Test0014.iFld1;
                                                                                                    break;
                                                                                                case 149:
                                                                                                    i47 *= i55;
                                                                                                    break;
                                                                                                case 151:
                                                                                                    iArrFld[i54] |= i62;
                                                                                                    break;
                                                                                            }
                                                                                            break;
                                                                                        default:
                                                                                            i49 &= (int)Test0014.lFld;
                                                                                    }
                                                                                case 17:
                                                                                    if (Test0014.bFld) break;
                                                                                    break;
                                                                                case 18:
                                                                                    i56 = 174;
                                                                                    break;
                                                                                case 19:
                                                                                    i58 += i62;
                                                                                case 20:
                                                                                    Test0014.iFld *= -19556;
                                                                                    break;
                                                                                default:
                                                                                    Cls.instanceCount = (long)i62;
                                                                            }
                                                                            break;
                                                                        case 121:
                                                                            break;
                                                                    }
                                                                case 108:
                                                                case 89:
                                                                    i46 += i53;
                                                                    break;
                                                                case 94:
                                                                case 111:
                                                                    iArrFld = iArrFld;
                                                                    break;
                                                            }
                                                        }
                                                    }
                                                case 78:
                                                    lArr3[i45 - 1][i45 - 1] -= (long)i59;
                                                case 79:
                                                    // Resetting String variable to a short value to prevent OOM
                                                    Test0014.strFld = "";
                                                    Test0014.strFld += Test0014.strFld;
                                                case 80:
                                                    iArrFld[(int)(l4)] = (int)Test0014.byFld;
                                                    break;
                                                case 81:
                                                    if (Test0014.bFld) break;
                                                    break;
                                                case 82:
                                                    i46 = i46;
                                                    break;
                                                case 83:
                                                    if (Test0014.bFld) continue;
                                                    break;
                                                case 84:
                                                    Test0014.cFld &= (char)i54;
                                                default:
                                                    O14 = O22;
                                            }
                                        } while (--i54 > 0);
                                    }
                                    break;
                                case 40:
                                    Test0014.strFld = Test0014.strFld;
                                case 54:
                                    Test0014.sFld >>= (short)Test0014.iFld;
                                case 32:
                                    Test0014.cFld += (char)i46;
                                case 33:
                                case 29:
                                    i60 = (int)Test0014.lFld;
                                    break;
                            }
                        case 35:
                            i58 -= -112;
                            break;
                        case 18:
                            i52 -= i53;
                            break;
                        case 46:
                            i59 += i53;
                            break;
                        case 49:
                            Cls.instanceCount *= (long)i48;
                            break;
                        case 34:
                            iArrFld = iArrFld;
                            break;
                        case 17:
                            i52 -= i49;
                            break;
                        case 36:
                            i58 -= i53;
                            break;
                        case 11:
                        case 27:
                            Cls.instanceCount = (long)Test0014.sFld;
                            break;
                        default:
                            Test0014.dFld *= (double)iFld2;
                    }
                }
            }
        }

        FuzzerUtils.out.println("i45 i46 l4 = " + i45 + "," + i46 + "," + l4);
        FuzzerUtils.out.println("i47 i48 i49 = " + i47 + "," + i48 + "," + i49);
        FuzzerUtils.out.println("i50 f5 i51 = " + i50 + "," + Float.floatToIntBits(f5) + "," + i51);
        FuzzerUtils.out.println("i52 i53 i54 = " + i52 + "," + i53 + "," + i54);
        FuzzerUtils.out.println("i55 i56 i57 = " + i55 + "," + i56 + "," + i57);
        FuzzerUtils.out.println("i58 i59 i60 = " + i58 + "," + i59 + "," + i60);
        FuzzerUtils.out.println("i61 i62 lArr3 = " + i61 + "," + i62 + "," + FuzzerUtils.checkSum(lArr3));
        FuzzerUtils.out.println("O14 O15 O16 = " + FuzzerUtils.checkSum(O14) + "," + FuzzerUtils.checkSum(O15) + "," +
            FuzzerUtils.checkSum(O16));
        FuzzerUtils.out.println("O17 O18 O19 = " + FuzzerUtils.checkSum(O17) + "," + FuzzerUtils.checkSum(O18) + "," +
            FuzzerUtils.checkSum(O19));
        FuzzerUtils.out.println("O20 O21 O22 = " + FuzzerUtils.checkSum(O20) + "," + FuzzerUtils.checkSum(O21) + "," +
            FuzzerUtils.checkSum(O22));
        FuzzerUtils.out.println("Cls = " + Cls.instanceCount);

        FuzzerUtils.out.println("Test0014.instanceCount Test0014.sFld Test0014.dFld = " + Test0014.instanceCount + "," + Test0014.sFld +
            "," + Double.doubleToLongBits(Test0014.dFld));
        FuzzerUtils.out.println("Test0014.byFld Test0014.lFld Test0014.bFld = " + Test0014.byFld + "," + Test0014.lFld + "," + (Test0014.bFld ?
            1 : 0));
        FuzzerUtils.out.println("Test0014.strFld Test0014.iFld Test0014.cFld = " + Test0014.strFld.length() + "," + Test0014.iFld + "," +
            (int)Test0014.cFld);
        FuzzerUtils.out.println("Test0014.fFld Test0014.iFld1 iFld2 = " + Float.floatToIntBits(Test0014.fFld) + "," + Test0014.iFld1 +
            "," + iFld2);
        FuzzerUtils.out.println("Test0014.fArrFld Test0014.dArrFld Test0014.strArrFld = " +
            Double.doubleToLongBits(FuzzerUtils.checkSum(Test0014.fArrFld)) + "," +
            Double.doubleToLongBits(FuzzerUtils.checkSum(Test0014.dArrFld)) + "," + FuzzerUtils.checkSum(Test0014.strArrFld));
        FuzzerUtils.out.println("iArrFld Test0014.cArrFld Cls = " + FuzzerUtils.checkSum(iArrFld) + "," +
            FuzzerUtils.checkSum(Test0014.cArrFld) + "," + Cls.instanceCount);

        FuzzerUtils.out.println("iMeth1_check_sum: " + iMeth1_check_sum);
        FuzzerUtils.out.println("iMeth_check_sum: " + iMeth_check_sum);
        FuzzerUtils.out.println("vMeth_check_sum: " + vMeth_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test0014 _instance = new Test0014();
            for (int i = 0; i < 10; i++ ) {
                try {
                    _instance.mainTest0014(strArr);
                 } catch (OutOfMemoryError ex) {
                    ex.printStackTrace(FuzzerUtils.err);
                    System.exit(1);
                 } catch (Exception ex) {
                    FuzzerUtils.out.println(ex.getClass().getCanonicalName());
                 }
             }
         } catch (Exception ex) {
            FuzzerUtils.out.println(ex.getClass().getCanonicalName());
         }
    }
}
///////////////////////////////////////////////////////////////////////
class Cls {

    public static final int N = 128;

    public static long instanceCount=29438L;

}
///////////////////////////////////////////////////////////////////////
//DEBUG  Test0014 ->  Test0014
//DEBUG  main ->  main
//DEBUG  mainTest0014 ->  mainTest0014
//DEBUG  vMeth ->  vMeth mainTest0014
//DEBUG  iMeth ->  iMeth vMeth mainTest0014
//DEBUG  iMeth1 ->  iMeth1 iMeth vMeth mainTest0014
//DEBUG  Cls ->  Cls iMeth1 iMeth vMeth mainTest0014
//DEBUG  Depth = 4
//DEBUG  Classes = 2
//DEBUG  static objects = {}
