import java.util.LinkedHashSet;
import java.util.Set;
import java.util.Map;
import java.util.TreeMap;
import java.util.HashSet;
import java.util.concurrent.ConcurrentSkipListMap;
import java.util.LinkedHashMap;
import java.util.TreeSet;
import java.util.HashMap;

public class TplClass2756 {

    private static final void method() throws Throwable {
        Map map = new HashMap();
        map.put("foo", "bar");
        map.clear();
        map.containsKey("foo");
        map.containsValue("foo");
        map.entrySet();
        map.equals(map);
        map.hashCode();
        map.isEmpty();
        map.keySet();
        map.putAll(map);
        map.remove("foo");
        map.size();
        map.put("bar", "foo");
        map.values();
        map = new LinkedHashMap();
        map.put("foo", "bar");
        map.clear();
        map.containsKey("foo");
        map.containsValue("foo");
        map.entrySet();
        map.equals(map);
        map.hashCode();
        map.isEmpty();
        map.keySet();
        map.putAll(map);
        map.remove("foo");
        map.size();
        map.put("bar", "foo");
        map.values();
        map = new TreeMap();
        map.put("foo", "bar");
        map.clear();
        map.containsKey("foo");
        map.containsValue("foo");
        map.entrySet();
        map.equals(map);
        map.hashCode();
        map.isEmpty();
        map.keySet();
        map.putAll(map);
        map.remove("foo");
        map.size();
        map.put("bar", "foo");
        map.values();
        map = new ConcurrentSkipListMap();
        map.put("foo", "bar");
        map.clear();
        map.containsKey("foo");
        map.containsValue("foo");
        map.entrySet();
        map.equals(map);
        map.hashCode();
        map.isEmpty();
        map.keySet();
        map.putAll(map);
        map.remove("foo");
        map.size();
        map.put("bar", "foo");
        map.values();
        Set set = new HashSet();
        set.add("foo");
        set.addAll(set);
        set.clear();
        set.contains("foo");
        set.containsAll(set);
        set.equals(set);
        set.hashCode();
        set.isEmpty();
        set.iterator();
        set.remove("foo");
        set.removeAll(set);
        set.retainAll(set);
        set.size();
        set.add("foo");
        set.toArray();
        set = new LinkedHashSet();
        set.add("foo");
        set.addAll(set);
        set.clear();
        set.contains("foo");
        set.containsAll(set);
        set.equals(set);
        set.hashCode();
        set.isEmpty();
        set.iterator();
        set.remove("foo");
        set.removeAll(set);
        set.retainAll(set);
        set.size();
        set.add("foo");
        set.toArray();
        set = new TreeSet();
        set.add("foo");
        set.addAll(set);
        set.clear();
        set.contains("foo");
        set.containsAll(set);
        set.equals(set);
        set.hashCode();
        set.isEmpty();
        set.iterator();
        set.remove("foo");
        set.removeAll(set);
        set.retainAll(set);
        set.size();
        set.add("foo");
        set.toArray();
    }
}

