import re
import os
from abc import ABC, abstractmethod
from collections import OrderedDict
from typing import List, Dict

from utils.fs import *
from utils.custom_template import *
from utils.log import *
from utils.llm import LLMClient

class MutGenerator(ABC):
    @abstractmethod
    def generate(self, output_folder: str) -> List[str]:
        pass


def generate_codebricks_from_template(input_ctx: str, output_folder: str, llm_client: LLMClient, src: str, full_ask: str | None = None) -> List[str]:
    """
    Generate code bricks from LLM outputs in the specified input folder and save them to the output folder.
    """
    res = llm_client.call_llm(_gen_cbt_template_.safe_substitute(context=input_ctx))
    if res is None:
        logging("WARNING", f"Warning: LLM returned None for file `{input_ctx}`, skipping.")
        return []
    
    comments_prefix = f"// {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    if full_ask:
        comments_prefix += f"// Full LLM prompt used:\n"
        for line in full_ask.splitlines():
            comments_prefix += f"//     {line}\n"
        comments_prefix += "\n"
    comments_prefix += f"// \"{input_ctx}\"\n"
    comments_prefix += f"\n// The following Statement block is generated by LLM according to the above context {src}:\n"
        
    # use Statement spilt res into multiple files, keep Statement.
    input_text_s = []
    for part in res.split("Statement:"):
        if part.strip().startswith("**Batch ") or \
            part.strip() == "" or part == "":
            continue
        statement_part = "Statement:" + part
        comments = comments_prefix
        for stmt_line in statement_part.splitlines():
            comments += "//     " + stmt_line + "\n"
        comments += "\n"
        input_text_s.append({
            "comment": comments,
            "content": statement_part
        })
    if len(input_text_s) == 0:
        logging("WARNING", "No output from LLM")
        return []
    ensure_dir(output_folder)
    id = 1
    # for input_text in str_form_llm:
    class_name = "Mutator" + str(id)
    output_path = os.path.join(output_folder, f"{class_name}.java")
    id += 1
    ret = []
    try:   
        for input_text in input_text_s:         
            # Ensure unique class_name and output_path if file exists            
            while os.path.exists(output_path):
                id += 1
                class_name = "Mutator" + str(id)
                output_path = os.path.join(output_folder, f"{class_name}.java")
            generate_java = _generate_java(input_text, class_name=class_name)
            if not generate_java:
                logging("WARNING", f"Skipping generation for {class_name} due to missing Statement block.")
                continue
            write_text(output_path, generate_java)
            log_info(f"Generated {output_path}")
            ret.append(output_path)
        return ret
    except Exception as e:
        logging("ERROR", f"Error processing {class_name}: {e}")
        return []

def _strip_comments(text: str) -> str:
    """
    Remove lines starting with '//' from the input text.
    """
    lines = []
    for line in text.splitlines():
        if line.lstrip().startswith("//"):
            continue
        lines.append(line)
    return "\n".join(lines)

def _parse_blocks(text: str):
    """
    Parse the code brick template text and extract statement, variable IDs, type blocks, and priority.
    """
    text = _strip_comments(text)
    
    # Extract Priority
    pri_matches = re.findall(r'(?mi)^\s*Priority:\s*(-?\d+)\s*$', text, re.M)
    if len(pri_matches) > 1:
        logging("WARNING", "Multiple Priority lines found; using the first one.")
    try:
        priority = int(pri_matches[0]) if pri_matches else 50
    except (ValueError, TypeError):
        logging("WARNING", "Invalid Priority value; defaulting to 50.")
        priority = 50
        
    # Extract Statement
    m_stmt = re.search(r'(?mi)^Statement:\s*(.*?)^(?:Var:|Type:|Priority:|Imports:|\Z)', text, re.S | re.M)
    if not m_stmt:
        logging("WARNING", f"No Statement block found in \"{text}\", cannot generate code brick. Skipping.")
        return None
    stmt_block = m_stmt.group(1).strip()
    statement = "\n".join(s.strip() for s in stmt_block.splitlines() if s.strip())
    
    # Extract Var (used to determine parameter order)
    m_var = re.search(r'(?mi)^Var:\s*(.*?)^(?:Type:|Priority:|Imports:|\Z)', text, re.S | re.M)
    var_block = m_var.group(1) if m_var else ""
    var_ids = re.findall(r'\$(\d+)', var_block)
    if not var_ids:
        # If Var is missing, deduplicate by order of appearance in statement
        var_ids = re.findall(r'\$(\d+)', statement)
    var_ids = list(OrderedDict((v, None) for v in var_ids).keys())

    # Extract Type section
    m_types = re.search(r'(?mi)^Type:\s*(.*?)(?=^Priority:|Imports:|\Z)', text, re.S | re.M)
    types_section = m_types.group(1) if m_types else ""
    type_blocks = []
    for m in re.finditer(r'(?mi)^Type(\d+):\s*(.*?)(?=^Type\d+:|\Z)', types_section, re.S | re.M):
        type_idx = int(m.group(1))
        block_text = m.group(2)
        entries = {}
        for line in block_text.splitlines():
            line = line.strip()
            if not line:
                continue
            # Format: $1: boolean, 2
            mm = re.match(r'^\$(\d+)\s*:\s*([A-Za-z_][\w<>\[\]\.? ,]*)\s*,\s*([123])\s*$', line)
            if mm:
                vid, jtype, kind = mm.group(1), mm.group(2).strip(), int(mm.group(3))
                entries[vid] = (jtype, kind)
        if entries:
            type_blocks.append((type_idx, entries))
    
    # Extract Imports
    m_imports = re.search(r'(?mi)^Imports:\s*(.*?)(?=^Priority:|\Z)', text, re.S | re.M)
    imports = ""
    if m_imports:
        imports_block = m_imports.group(1).strip()
        for s in imports_block.splitlines():
            if s.strip():
                imports += f"import {s.strip()};\n"

    if not type_blocks:
        logging("ERROR", "No Type blocks found")
        raise ValueError("No Type blocks found")

    return imports, statement, var_ids, sorted(type_blocks, key=lambda x: x[0]), priority

def _replace_placeholders(statement: str, id_to_name: dict) -> str:
    """
    Replace variable placeholders in the statement with actual variable names.
    """
    def repl(m):
        vid = m.group(1)
        return id_to_name.get(vid, f"${vid}")
    return re.sub(r'\$(\d+)', repl, statement)

def _generate_java(text: Dict[str, str], class_name: str = "tmp") -> str | None:
    """
    Generate Java code for a code brick from the template text.
    """
    parse_res = _parse_blocks(text["content"])
    if not parse_res:
        return None
    imports, statement, var_ids, type_blocks, priority = parse_res

    lines = []
    if imports:
        lines.append(imports)
    lines.append(f"public class {class_name} {{\n")
    lines.append(f"    public static int $priority = {priority};\n")

    for idx, entries in type_blocks:
        # Construct parameter names like $expr/$lval/$const
        params = []
        id_to_name = {}
        for vid in var_ids:
            if vid not in entries:
                logging("ERROR", f"Type{idx} missing declaration for ${vid}")
                raise ValueError("ERROR", f"Type{idx} missing declaration for ${vid}")
            jtype, kind = entries[vid]
            prefix = {1: "$expr", 2: "$lval", 3: "$const"}[kind]
            name = f"{prefix}{vid}"
            id_to_name[vid] = name
            params.append(f"{jtype} {name}")

        stmt_java = _replace_placeholders(statement, id_to_name)

        lines.append(f"    public static void $mut{idx}({', '.join(params)}) {{")
        for sline in stmt_java.splitlines():
            lines.append(f"        {sline}")
        lines.append("    }\n")

    lines.append("}")
    return text["comment"] + "\n\n" + "\n".join(lines)

_gen_cbt_template_ = CustomTemplate(
    f"Answer based on the knowledge: \n"
    f"``` \n"
    f"%%context \n"
    f"``` \n"
    f"Example format (the following explains how to use the startsWith function in Java):\n"
    f"``` \n"
    f"    Statement: $1 = $2.startsWith($3,$4); \n"
    f"    Var: $1,$2,$3,$4 \n"
    f"    Type: \n"
    f"        Type1: \n"
    f"            $1:boolean,2 \n"
    f"            $2:String,2 \n"
    f"            $3:String,1 \n"
    f"            $4:int,1 \n"
    f"    Imports: \n"
    f"        java.util.Arrays \n\n"
    f"    // 1: variable or constant | 2: variable only | 3: constant only (e.g. 1,2,\"hello\") \n"
    f"``` \n"
    f"Requirements:"
    f"   1. ANSWER DIRECTLY IN PURE TEXT WITHOUT ADDITIONAL DETAILS. \n"
    f"   2. INCLUDE \"Imports\" IF REQUIRED, otherwise omit. \n"
    f"   3. Multiple valid types: output as Type1, Type2, etc. \n"
    f"   4. Use actual Java types (int, int[], String), not generics like 'array'. \n"
    f"   5. Multiple statement forms: output each completely with variables and types. \n"
    f"   6. For Object type: consider primitives (int, string) and constants. \n"
    f"   7. n-dimensional arrays: use \"new <T>[d1]...[dn]\" format, $1 as T[][]..., $2..$n+1 as int,1."
    f"         For \"multianewarray\": single new with all dimensions. (e.g., $1 = new String[$2][$3][$4][$5][$6];) \n"
    f"   8. Void methods: no return value needed. \n"
    f"   9. Loop/conditional structures: use $stmt(); for inner statements. \n"
)