// Generated by Java* Fuzzer test generator (1.0.001). Sun Mar 29 19:32:09 2026
public class Test0007 {

    public static final int N = 128;

    public static long instanceCount=41839L;
    public int iFld=145;
    public static double dFld=-2.48788;
    public volatile float fFld=1.652F;
    public static short sFld=-8193;
    public static char cFld1=62135;
    public static String strArrFld[]=new String[N];
    public static int iArrFld[][]=new int[N][N];

    static {
        FuzzerUtils.init(Test0007.strArrFld, "two");
        FuzzerUtils.init(Test0007.iArrFld, -19920);
    }

    public static long vMeth1_check_sum = 0;

    public static void vMeth1(int i5, int i6, float f1) {

        long meth_res = 0;
        String str="two";
        int i7=2, i8=101, i9=111, i10=2773, i11=22551, i12=-32, i13=128, i14=12, i15=208, i16=40349, iArr[]=new int[N];
        boolean b=true;
        byte by1=16;
        double d1=83.45742;
        char c=16418;
        short s=-4515;
        Cls O1=new Cls(), O2=new Cls(), O3=new Cls(), O4=new Cls();

        FuzzerUtils.init(iArr, 6);

        // Resetting String variable to a short value to prevent OOM
        str = "";
        str += "one";
        iArr[(-462 >>> 1) % N] >>= i5;
        for (i7 = (int) (4); i7 < 120; i7 += 3) {
            if (b) continue;
            if (false) {
                for (i9 = (int) (40); i9 > 1; i9--) {
                    d1 = 2;
                    while (--d1 > 0) {
                        i11 = 1;
                        while (--i11 > 0) {
                            Test0007.strArrFld[(int)(d1)] = str;
                            for (i12 = (int) (1); i12 < 1; i12++) {
                                i6 -= -97;
                                switch ((int)(((d1 % 1) * 5) + 31)) {
                                    case 36:
                                        // Resetting String variable to a short value to prevent OOM
                                        str = "";
                                        str += str;
                                }
                                i8 -= i5;
                            }
                            switch (((i6 >>> 1) % 2) + 87) {
                                case 87:
                                    i13 &= 28;
                                    switch ((i9 % 9) + 9) {
                                        case 9:
                                            break;
                                        case 10:
                                            i10 *= (int)Cls.instanceCount;
                                        case 11:
                                            i5 = 12495;
                                            Test0007.instanceCount += Cls.instanceCount;
                                            c <<= (char)i8;
                                            str = str;
                                            Test0007.instanceCount = (long)i8;
                                            iArr[i9 - 1] >>>= i8;
                                            i8 = (int)f1;
                                            iArr = iArr;
                                            break;
                                        case 12:
                                            s = (short)i13;
                                            i14 = 1;
                                            do {
                                                i6 >>>= i14;
                                                if (b) break;
                                                i6 >>= i8;
                                                Test0007.strArrFld[i11 - 1] = "three";
                                                i10 = (int)d1;
                                                iArr[(int)(d1 + 1)] += -28493;
                                            } while (--i14 > 0);
                                            i6 |= i10;
                                            for (i15 = (int) (1); i15 > i9; i15 -= 2) {
                                                i6 = i13;
                                                // Resetting String variable to a short value to prevent OOM
                                                str = "";
                                                str += str;
                                            }
                                            Test0007.instanceCount &= (long)i15;
                                            switch (((64774 >>> 1) % 2) + 66) {
                                                case 66:
                                                    i8 = (int)Cls.instanceCount;
                                                    switch ((int)(((d1 % 7) * 5) + 86)) {
                                                        case 101:
                                                            switch ((((-5885 >>> 1) % 3) * 5) + 79) {
                                                                case 82:
                                                                    i16 += (int)Test0007.instanceCount;
                                                                    i10 *= -17364;
                                                                    break;
                                                                case 94:
                                                                    i6 *= (int)Cls.instanceCount;
                                                                case 83:
                                                                    i16 = (int)c;
                                                                    break;
                                                                default:
                                                                    i16 *= i12;
                                                            }
                                                            break;
                                                        case 121:
                                                            by1 = (byte)-42010;
                                                            break;
                                                        case 87:
                                                            break;
                                                        case 109:
                                                            iArr[i11 - 1] += i14;
                                                        case 117:
                                                        case 102:
                                                            iArr[(int)(d1 - 1)] >>>= -45960;
                                                            break;
                                                        case 118:
                                                            Test0007.strArrFld[i11] += str;
                                                    }
                                                    break;
                                                case 67:
                                                default:
                                                    i10 |= 167;
                                            }
                                            break;
                                        case 13:
                                            i10 = (int)Cls.instanceCount;
                                            break;
                                        case 14:
                                        case 15:
                                            i13 += (int)Test0007.instanceCount;
                                            break;
                                        case 16:
                                            if (b) continue;
                                            break;
                                        case 17:
                                            i10 -= -64100;
                                            break;
                                    }
                                    break;
                                case 88:
                                    break;
                                default:
                            }
                        }
                    }
                }
            } else if (b) {
                if (true) break;
            } else if (b) {
                i5 >>= (int)Test0007.instanceCount;
            } else {
                Test0007.dFld -= (double)i13;
            }
        }
        vMeth1_check_sum += i5 + i6 + Float.floatToIntBits(f1) + str.length() + i7 + i8 + (b ? 1 : 0) + by1 + i9 + i10
            + Double.doubleToLongBits(d1) + i11 + i12 + i13 + (int)c + s + i14 + i15 + i16 + FuzzerUtils.checkSum(iArr)
            + FuzzerUtils.checkSum(O1) + FuzzerUtils.checkSum(O2) + FuzzerUtils.checkSum(O3) + FuzzerUtils.checkSum(O4);
    }

    public void mainTest0007(String[] strArr1) {

        long meth_res = 0;
        int i=10, i1=253, i2=2, i3=-38, i49=63248, i50=-40895, i51=-13, i52=104, i53=30670, i54=-251, i55=5, i56=-188;
        double d=121.16596, dArr[]=new double[N], dArr1[][]=new double[N][N];
        byte by4=107;
        float f4=25.127F;
        long lArr[][]=new long[N][N];
        Cls O=new Cls(), O20=new Cls(), O21=new Cls(), O22=new Cls(), O23=new Cls();

        FuzzerUtils.init(lArr, 0L);
        FuzzerUtils.init(dArr, -122.37644);
        FuzzerUtils.init(dArr1, -2.3123);

        i = 94;
        while (--i > 0) {
            iFld = i;
            if ((Test0007.instanceCount++) != i1) break;
            d /= (double)(((-lArr[i - 1][i + 1]) + (-(202 - (Test0007.instanceCount++)))) | 1);
        }
        for (i2 = (int) (5); 111 > i2; i2++) {
            Test0007.instanceCount -= (long)Cls.iMeth(i1);
            try {
                Test0007.iArrFld[i2 - 1] = Test0007.iArrFld[i2 + 1];
                if (Cls.bFld) {
                    Test0007.iArrFld[i2 - 1][(iFld >>> 1) % N] >>= (int)-7972568778559174503L;
                    try {
                        i49 = 124;
                        do {
                            i50 = 1;
                            while ((i50 += 3) < 2) {
                                i1 -= iFld;
                                for (i51 = (int) (1); ((long)2 + (long)128) > i51; i51 += 2) {
                                    O = new Cls();
                                    switch ((i50 % 2) + 118) {
                                        case 118:
                                            i3 >>>= iFld;
                                            for (i53 = (int) (1); i53 < ((long)1 + (long)128); i53++) {
                                                by4 *= (byte)i2;
                                                iFld = i;
                                                lArr[i2 + 1][i49 - 1] |= (long)11;
                                                switch (((i51 % 9) * 5) + 121) {
                                                    case 156:
                                                        if (Cls.bFld) break;
                                                        i1 += (int)Cls.cFld;
                                                        i1 <<= i;
                                                        synchronized (O22) {
                                                            switch ((i51 % 1) + 98) {
                                                                case 98:
                                                                    Test0007.strArrFld[i49 - 1] += Cls.strFld;
                                                                    break;
                                                            }
                                                            Test0007.iArrFld[i51][i50 + 1] = i54;
                                                            Cls.cFld = (char)Cls.instanceCount;
                                                        }
                                                        Cls.lFld -= (long)i54;
                                                        Test0007.iArrFld[i51 - 1][i51 + 1] -= (int)Cls.cFld;
                                                        fFld = (float)i3;
                                                    case 128:
                                                        i3 ^= i1;
                                                        // Resetting String variable to a short value to prevent OOM
                                                        Cls.strFld = "";
                                                        Cls.strFld += Cls.strFld;
                                                        break;
                                                    case 148:
                                                        iFld *= i49;
                                                        Test0007.dFld = (double)i55;
                                                        switch ((i50 % 1) + 54) {
                                                            case 54:
                                                                i54 = -31676;
                                                                lArr[i51 - 1] = lArr[i50 - 1];
                                                                switch (((i50 % 4) * 5) + 59) {
                                                                    case 65:
                                                                        synchronized (O23) {
                                                                        }
                                                                    case 78:
                                                                        i55 *= (int)Cls.cFld;
                                                                        i3 = (int)Cls.instanceCount;
                                                                        i3 += 117;
                                                                        dArr[i2] = (double)by4;
                                                                        iFld = i51;
                                                                        d = (double)i;
                                                                        Test0007.iArrFld[i49 + 1][i51] = (int)Test0007.dFld;
                                                                        Test0007.instanceCount = (long)i3;
                                                                        break;
                                                                    case 62:
                                                                        i1 = (int)-23592L;
                                                                        Test0007.iArrFld[i50 - 1][i51 + 1] =
                                                                            (int)Cls.instanceCount;
                                                                        iFld *= i54;
                                                                        d = (double)-12;
                                                                        break;
                                                                    case 72:
                                                                        Cls.cFld = (char)i56;
                                                                        Cls.strFld = "one";
                                                                        Test0007.dFld *= (double)Cls.lFld;
                                                                        i56 += Cls.iFld1;
                                                                }
                                                                Test0007.cFld1 >>= (char)Cls.lFld;
                                                                dArr1 = dArr1;
                                                                Cls.iFld1 *= i52;
                                                                switch ((i53 % 2) + 66) {
                                                                    case 66:
                                                                        O22 = O22;
                                                                        Cls.strFld = Cls.strFld;
                                                                        i3 = (int)19407L;
                                                                        i54 >>= (int)Cls.instanceCount;
                                                                        if (true) break;
                                                                    case 67:
                                                                        Cls.lFld += Cls.lFld;
                                                                        Cls.iFld1 -= (int)Test0007.instanceCount;
                                                                        f4 += (float)iFld;
                                                                        if (Cls.bFld) continue;
                                                                        // Resetting String variable to a short value
                                                                        // to prevent OOM
                                                                        Cls.strFld = "hhhh";
                                                                        Cls.strFld += "three";
                                                                        break;
                                                                }
                                                                break;
                                                        }
                                                        switch ((i49 % 1) + 74) {
                                                            case 74:
                                                                Test0007.iArrFld[i51 - 1][i49] = i;
                                                                break;
                                                            default:
                                                                Test0007.iArrFld[i51][i51 - 1] = (int)Cls.instanceCount;
                                                                i1 += -5;
                                                                i52 &= i52;
                                                                i54 += (int)f4;
                                                                // Resetting String variable to a short value to
                                                                // prevent OOM
                                                                Cls.strFld = "";
                                                                Cls.strFld += Cls.strFld;
                                                                Test0007.iArrFld[i50 - 1][i49 - 1] +=
                                                                    (int)Test0007.instanceCount;
                                                        }
                                                        break;
                                                    case 123:
                                                        if (Cls.bFld) continue;
                                                    case 149:
                                                        Test0007.dFld += (double)iFld;
                                                        break;
                                                    case 165:
                                                        Test0007.strArrFld = Test0007.strArrFld;
                                                        break;
                                                    case 141:
                                                    case 147:
                                                        Cls.strFld = Cls.strFld;
                                                        break;
                                                    case 129:
                                                        Cls.lFld += (long)i54;
                                                    default:
                                                        Test0007.instanceCount *= Cls.lFld;
                                                }
                                            }
                                        case 119:
                                            Test0007.iArrFld[i2 - 1][i51] = i50;
                                        default:
                                    }
                                }
                            }
                        } while (--i49 > 0);
                    }
                    catch (ArrayIndexOutOfBoundsException exc6) {
                        i52 = i54;
                    }
                } else if (Cls.bFld) {
                    Test0007.iArrFld[i2][i2 - 1] -= i;
                }
            }
            catch (ArrayIndexOutOfBoundsException exc7) {
            }
        }

        FuzzerUtils.out.println("i i1 d = " + i + "," + i1 + "," + Double.doubleToLongBits(d));
        FuzzerUtils.out.println("i2 i3 i49 = " + i2 + "," + i3 + "," + i49);
        FuzzerUtils.out.println("i50 i51 i52 = " + i50 + "," + i51 + "," + i52);
        FuzzerUtils.out.println("i53 i54 by4 = " + i53 + "," + i54 + "," + by4);
        FuzzerUtils.out.println("i55 i56 f4 = " + i55 + "," + i56 + "," + Float.floatToIntBits(f4));
        FuzzerUtils.out.println("lArr dArr dArr1 = " + FuzzerUtils.checkSum(lArr) + "," +
            Double.doubleToLongBits(FuzzerUtils.checkSum(dArr)) + "," +
            Double.doubleToLongBits(FuzzerUtils.checkSum(dArr1)));
        FuzzerUtils.out.println("O O20 O21 = " + FuzzerUtils.checkSum(O) + "," + FuzzerUtils.checkSum(O20) + "," +
            FuzzerUtils.checkSum(O21));
        FuzzerUtils.out.println("O22 O23 Cls = " + FuzzerUtils.checkSum(O22) + "," + FuzzerUtils.checkSum(O23) + "," +
            Cls.instanceCount);

        FuzzerUtils.out.println("Test0007.instanceCount iFld Test0007.dFld = " + Test0007.instanceCount + "," + iFld + "," +
            Double.doubleToLongBits(Test0007.dFld));
        FuzzerUtils.out.println("fFld Test0007.sFld Test0007.cFld1 = " + Float.floatToIntBits(fFld) + "," + Test0007.sFld + "," +
            (int)Test0007.cFld1);
        FuzzerUtils.out.println("Test0007.strArrFld Test0007.iArrFld Cls = " + FuzzerUtils.checkSum(Test0007.strArrFld) + "," +
            FuzzerUtils.checkSum(Test0007.iArrFld) + "," + Cls.instanceCount);

        FuzzerUtils.out.println("vMeth1_check_sum: " + vMeth1_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test0007 _instance = new Test0007();
            for (int i = 0; i < 10; i++ ) {
                try {
                    _instance.mainTest0007(strArr);
                 } catch (OutOfMemoryError ex) {
                    ex.printStackTrace(FuzzerUtils.err);
                    System.exit(1);
                 } catch (Exception ex) {
                    FuzzerUtils.out.println(ex.getClass().getCanonicalName());
                 }
             }
         } catch (Exception ex) {
            FuzzerUtils.out.println(ex.getClass().getCanonicalName());
         }
    }
}
///////////////////////////////////////////////////////////////////////
class Cls {

    public static final int N = 128;

    public static long instanceCount=-149L;
    public static int iFld1=-9;
    public static volatile boolean bFld=true;
    public static String strFld="one";
    public static char cFld=10859;
    public static long lFld=1867919436L;

    public static long iMeth_check_sum = 0;
    public static long vMeth_check_sum = 0;

    public static void vMeth(byte by, float f) {

        long meth_res = 0;
        int i17=-144, i18=231, i19=-39221, i20=10526, i21=51, i22=-8, i23=43574, i24=-13, i25=7805, i26=-12501,
            i27=163, i28=208, i29=240, i30=-22671, i31=47, i32=16795, i33=63584, i34=-4015, iArr1[]=new int[N];
        short s1=-11577;
        float f2=95.883F, fArr[]=new float[N];
        long lArr1[]=new long[N];
        boolean bArr[]=new boolean[N];
        Cls O5=new Cls(), O6=new Cls(), O7=new Cls(), O8=new Cls(), O9=new Cls(), O10=new Cls(), O11=new Cls(), O12=new
            Cls(), O13=new Cls();

        FuzzerUtils.init(lArr1, -217L);
        FuzzerUtils.init(fArr, 113.190F);
        FuzzerUtils.init(bArr, false);
        FuzzerUtils.init(iArr1, 200);

        Test0007.vMeth1(Cls.iFld1, Cls.iFld1, f);
        O5 = new Cls();
        switch ((((Cls.iFld1 >>> 1) % 6) * 5) + 28) {
            case 39:
                for (i17 = (int) (6); 121 > i17; i17++) {
                    i18 = (int)f;
                    if (Cls.bFld) break;
                }
                synchronized (O7) {
                    i20 = 118;
                    do {
                        synchronized (O8) {
                            i22 = 38;
                            while (--i22 > 0) {
                                synchronized (O9) {
                                    switch ((i22 % 1) + 81) {
                                        case 81:
                                            i21 = i21;
                                            break;
                                        default:
                                            for (i24 = (int) (1); i24 > 1; i24 -= 2) {
                                                i26 = 1;
                                                do {
                                                    lArr1[i22 + 1] &= (long)i20;
                                                } while (++i26 < 1);
                                            }
                                            if (Cls.bFld) break;
                                            // Resetting String variable to a short value to prevent OOM
                                            Cls.strFld = "";
                                            Cls.strFld += Cls.strFld;
                                            Cls.instanceCount = (long)i17;
                                            for (i27 = (int) (1); i27 > 1; i27 -= 3) {
                                                switch (((i22 % 7) * 5) + 45) {
                                                    case 58:
                                                        if (Cls.iFld1 != 0) {
                                                            vMeth_check_sum += by + Float.floatToIntBits(f) + i17 + i18
                                                                + s1 + i19 + i20 + i21 + i22 + i23 + i24 + i25 + i26 +
                                                                i27 + i28 + i29 + i30 + i31 + Float.floatToIntBits(f2)
                                                                + i32 + i33 + i34 + FuzzerUtils.checkSum(lArr1) +
                                                                Double.doubleToLongBits(FuzzerUtils.checkSum(fArr)) +
                                                                FuzzerUtils.checkSum(bArr) +
                                                                FuzzerUtils.checkSum(iArr1) + FuzzerUtils.checkSum(O5)
                                                                + FuzzerUtils.checkSum(O6) + FuzzerUtils.checkSum(O7) +
                                                                FuzzerUtils.checkSum(O8) + FuzzerUtils.checkSum(O9) +
                                                                FuzzerUtils.checkSum(O10) + FuzzerUtils.checkSum(O11) +
                                                                FuzzerUtils.checkSum(O12) + FuzzerUtils.checkSum(O13);
                                                            return;
                                                        }
                                                        Cls.strFld = Cls.strFld;
                                                        Cls.bFld = Cls.bFld;
                                                        for (i29 = (int) (1); i29 < 1; ++i29) {
                                                        }
                                                        fArr[i27 - 1] -= f;
                                                        i31 = 1;
                                                        do {
                                                            for (f2 = (float) (1); 1 < f2; f2 -= 2) {
                                                                bArr[i31 + 1] = true;
                                                            }
                                                            s1 >>= (short)i32;
                                                            O7 = new Cls();
                                                            Cls.cFld = (char)-194;
                                                            switch ((i20 % 5) + 54) {
                                                                case 54:
                                                                    lArr1[i31 - 1] = (long)58;
                                                                    i33 += (int)Cls.instanceCount;
                                                                    i34 = 1;
                                                                    while (--i34 > 0) {
                                                                        Cls.cFld += (char)i19;
                                                                        i32 >>= -26165;
                                                                        Test0007.instanceCount *= (long)0.645F;
                                                                    }
                                                                    switch ((i31 % 1) + 112) {
                                                                        case 112:
                                                                            f = (float)i26;
                                                                            iArr1[i22 + 1] += i25;
                                                                            Cls.instanceCount -= (long)33;
                                                                        default:
                                                                            i19 = i22;
                                                                    }
                                                                    break;
                                                                case 55:
                                                                    Test0007.dFld = (double)i24;
                                                                    break;
                                                                case 56:
                                                                    Test0007.instanceCount = (long)i18;
                                                                    break;
                                                                case 57:
                                                                    iArr1[i20 + 1] = i27;
                                                                case 58:
                                                                    i19 += (int)Cls.instanceCount;
                                                                    break;
                                                                default:
                                                                    if (Cls.bFld) continue;
                                                            }
                                                        } while ((i31 -= 3) > 0);
                                                        break;
                                                    case 80:
                                                        Test0007.dFld = Test0007.dFld;
                                                        break;
                                                    case 54:
                                                        break;
                                                    case 69:
                                                        s1 ^= (short)i32;
                                                    case 46:
                                                        O7 = O8;
                                                    case 57:
                                                        f = (float)i28;
                                                        break;
                                                    case 56:
                                                    default:
                                                        by >>>= by;
                                                }
                                            }
                                    }
                                }
                            }
                        }
                    } while ((i20 -= 3) > 0);
                }
                break;
            case 57:
                Test0007.instanceCount += (long)-102.27302;
                break;
            case 45:
                i33 %= (int)(Cls.iFld1 | 1);
                break;
            case 55:
                by = (byte)-34.253F;
                break;
            case 50:
                Test0007.instanceCount -= (long)i28;
            case 36:
                i23 >>= i33;
                break;
        }
        vMeth_check_sum += by + Float.floatToIntBits(f) + i17 + i18 + s1 + i19 + i20 + i21 + i22 + i23 + i24 + i25 +
            i26 + i27 + i28 + i29 + i30 + i31 + Float.floatToIntBits(f2) + i32 + i33 + i34 +
            FuzzerUtils.checkSum(lArr1) + Double.doubleToLongBits(FuzzerUtils.checkSum(fArr)) +
            FuzzerUtils.checkSum(bArr) + FuzzerUtils.checkSum(iArr1) + FuzzerUtils.checkSum(O5) +
            FuzzerUtils.checkSum(O6) + FuzzerUtils.checkSum(O7) + FuzzerUtils.checkSum(O8) + FuzzerUtils.checkSum(O9) +
            FuzzerUtils.checkSum(O10) + FuzzerUtils.checkSum(O11) + FuzzerUtils.checkSum(O12) +
            FuzzerUtils.checkSum(O13);
    }

    public static int iMeth(int i4) {

        long meth_res = 0;
        byte by2=-45, by3=-8, byArr[]=new byte[N];
        float f3=-1.495F, fArr1[]=new float[N];
        int i35=4, i36=54360, i37=-1, i38=-48460, i39=-42, i40=-54, i41=47001, i42=-12, i43=43306, i44=-192, i45=60958,
            i46=-7, i47=-9, i48=-49758, iArr2[][]=new int[N][N];
        short s2=-28838;
        long lArr2[]=new long[N];
        Cls O14=new Cls(), O15=new Cls(), O16=new Cls(), O17=new Cls(), O18=new Cls(), O19=new Cls();

        FuzzerUtils.init(lArr2, -8L);
        FuzzerUtils.init(iArr2, 42);
        FuzzerUtils.init(byArr, (byte)-127);
        FuzzerUtils.init(fArr1, 1.907F);

        vMeth((byte)(by2), f3);
        lArr2[(i4 >>> 1) % N] >>= (long)i4;
        for (i35 = (int) (94); 5 < i35; i35--) {
            i37 = 1;
            do {
                iArr2[i37][(i37 >>> 1) % N] &= i37;
                for (i38 = (int) (4); i38 > i37; --i38) {
                    Cls.instanceCount = (long)i38;
                    switch ((i38 % 8) + 9) {
                        case 9:
                            switch ((i38 % 3) + 122) {
                                case 122:
                                    switch ((((10 >>> 1) % 2) * 5) + 76) {
                                        case 83:
                                            i36 += i4;
                                            switch ((i37 % 7) + 107) {
                                                case 107:
                                                    i40 = 1;
                                                    do {
                                                        for (i41 = (int) (1); i41 < 1; i41++) {
                                                            Cls.lFld = (long)i38;
                                                        }
                                                        Cls.iFld1 = i39;
                                                        switch ((i35 % 2) + 122) {
                                                            case 122:
                                                                by2 += (byte)i37;
                                                                Cls.lFld *= (long)i4;
                                                                byArr[i35] *= (byte)f3;
                                                                i39 = i42;
                                                                i36 += i37;
                                                                i42 *= i4;
                                                                for (i43 = (int) (1); 1 > i43; i43 += 2) {
                                                                    Cls.instanceCount = (long)i4;
                                                                    lArr2[i40] += (long)i37;
                                                                    Cls.instanceCount += (long)i38;
                                                                    Cls.instanceCount += (long)f3;
                                                                    f3 -= -89.873F;
                                                                    Cls.bFld = Cls.bFld;
                                                                    s2 >>>= (short)Cls.instanceCount;
                                                                }
                                                                i42 = (int)Test0007.instanceCount;
                                                                Cls.instanceCount = (long)i39;
                                                            case 123:
                                                                i42 *= i40;
                                                                iArr2[i37 + 1][i37] = i36;
                                                                Test0007.instanceCount = (long)Test0007.dFld;
                                                                for (i45 = (int) (1); i45 > 1; i45 -= 3) {
                                                                    f3 = (float)1091931341L;
                                                                }
                                                                break;
                                                            default:
                                                                switch ((((i37 >>> 1) % 10) * 5) + 17) {
                                                                    case 32:
                                                                        for (i47 = (int) (i37); i47 < 1; ++i47) {
                                                                            iArr2[i37 - 1][i47 - 1] ^= i38;
                                                                            fArr1[i37 - 1] = f3;
                                                                            lArr2[i38 + 1] -= (long)i41;
                                                                            lArr2[i40 - 1] = Cls.lFld;
                                                                        }
                                                                        break;
                                                                    case 26:
                                                                        if (Cls.bFld) break;
                                                                        break;
                                                                    case 27:
                                                                        Cls.instanceCount = (long)-1;
                                                                    case 42:
                                                                        byArr = byArr;
                                                                        break;
                                                                    case 39:
                                                                        iArr2[(i46 >>> 1) % N][i40 - 1] %= (int)-128L;
                                                                        break;
                                                                    case 41:
                                                                        // Resetting String variable to a short value
                                                                        // to prevent OOM
                                                                        Cls.strFld = "";
                                                                        Cls.strFld += Cls.strFld;
                                                                    case 62:
                                                                    case 59:
                                                                        Cls.lFld >>= (long)19830;
                                                                    case 45:
                                                                        i42 = Cls.iFld1;
                                                                        break;
                                                                    case 55:
                                                                        Cls.bFld = Cls.bFld;
                                                                        break;
                                                                }
                                                        }
                                                    } while ((i40 += 2) < 1);
                                                    break;
                                                case 108:
                                                    fArr1[i35 + 1] = (float)14;
                                                    break;
                                                case 109:
                                                    // Resetting String variable to a short value to prevent OOM
                                                    Cls.strFld = "hhhh";
                                                    Cls.strFld += Cls.strFld;
                                                    break;
                                                case 110:
                                                    Cls.lFld = (long)i41;
                                                    break;
                                                case 111:
                                                    i42 >>= (int)s2;
                                                    break;
                                                case 112:
                                                    if (Cls.bFld) break;
                                                case 113:
                                                    by2 = (byte)Cls.instanceCount;
                                                    break;
                                                default:
                                                    Cls.strFld = Cls.strFld;
                                            }
                                            break;
                                        case 80:
                                        default:
                                    }
                                    break;
                                case 123:
                                    i4 = -36958;
                                    break;
                                case 124:
                                    i36 = (int)by3;
                                    break;
                            }
                            break;
                        case 10:
                            Cls.strFld = Cls.strFld;
                            break;
                        case 11:
                        case 12:
                            if (Cls.bFld) break;
                            break;
                        case 13:
                            iArr2[i38][i37 - 1] = i40;
                            break;
                        case 14:
                            // Resetting String variable to a short value to prevent OOM
                            Cls.strFld = "";
                            Cls.strFld += "three";
                        case 15:
                            i48 <<= (int)Cls.lFld;
                            break;
                        case 16:
                            i48 = i38;
                            break;
                    }
                }
            } while ((i37 += 3) < 17);
        }
        meth_res = i4 + by2 + Float.floatToIntBits(f3) + i35 + i36 + i37 + i38 + i39 + i40 + i41 + i42 + i43 + i44 + s2
            + i45 + i46 + i47 + i48 + by3 + FuzzerUtils.checkSum(lArr2) + FuzzerUtils.checkSum(iArr2) +
            FuzzerUtils.checkSum(byArr) + Double.doubleToLongBits(FuzzerUtils.checkSum(fArr1)) +
            FuzzerUtils.checkSum(O14) + FuzzerUtils.checkSum(O15) + FuzzerUtils.checkSum(O16) +
            FuzzerUtils.checkSum(O17) + FuzzerUtils.checkSum(O18) + FuzzerUtils.checkSum(O19);
        iMeth_check_sum += meth_res;
        return (int)meth_res;
    }

}
///////////////////////////////////////////////////////////////////////
//DEBUG  Test0007 ->  Test0007
//DEBUG  main ->  main
//DEBUG  mainTest0007 ->  mainTest0007
//DEBUG  Cls ->  Cls vMeth iMeth mainTest0007 vMeth1
//DEBUG  iMeth ->  iMeth mainTest0007
//DEBUG  vMeth ->  vMeth iMeth mainTest0007
//DEBUG  vMeth1 ->  vMeth1 vMeth iMeth mainTest0007
//DEBUG  Depth = 4
//DEBUG  Classes = 2
//DEBUG  static objects = {}
