// Generated by Java* Fuzzer test generator (1.0.001). Sun Mar 29 19:34:11 2026
public class Test0010 {

    public static final int N = 128;

    public static long instanceCount=-2020801584L;
    public static double dFld=0.79135;
    public static float fFld=-37.920F;
    public static int iFld=-13;
    public static char cFld=37917;
    public static boolean bFld=false;
    public int iFld1=17717;
    public static int iArrFld[]=new int[N];

    static {
        FuzzerUtils.init(Test0010.iArrFld, 249);
    }

    public static long vMeth1_check_sum = 0;

    public static void vMeth1() {

        long meth_res = 0;
        int i15=48143, i16=-6, i17=56441, i18=-47429, i19=798, i20=34, i21=-29293, i22=-8, i23=-10, i24=-6;
        long l2=42L, lArr2[]=new long[N];
        String str1="two", strArr2[]=new String[N];
        char c=61644;
        boolean b=true;
        short s1=-19298, sArr[]=new short[N];
        double dArr[]=new double[N];
        Cls1 O5=new Cls1(), O6=new Cls1(), O7=new Cls1(), O8=new Cls1();

        FuzzerUtils.init(lArr2, 3529626086357303409L);
        FuzzerUtils.init(dArr, -2.67617);
        FuzzerUtils.init(sArr, (short)12406);
        FuzzerUtils.init(strArr2, "one");

        for (i15 = (int) (121); 7 < i15; i15 -= 2) {
            for (i17 = (int) (1); i17 < 27; i17 += 2) {
                for (i19 = (int) (i15); i19 < 3; i19 += 2) {
                }
                try {
                    i20 = (i19 / i20);
                    i20 = (i19 % Test0010.iArrFld[i15 - 1]);
                    Test0010.iArrFld[i15 + 1] = (i18 / i17);
                } catch (ArithmeticException a_e) {}
                for (i21 = (int) (1); i21 < 3; i21 += 3) {
                    boolean b1=false;
                    i18 += (int)Test0010.dFld;
                    i20 -= (int)Test0010.instanceCount;
                    try {
                        try {
                            switch (((i15 % 9) * 5) + 110) {
                                case 133:
                                case 118:
                                    i22 += (int)Cls1.instanceCount;
                                    switch ((((i18 >>> 1) % 2) * 5) + 99) {
                                        case 107:
                                        case 104:
                                            i23 = 3;
                                            do {
                                                O5 = O7;
                                                switch ((((i18 >>> 1) % 3) * 5) + 93) {
                                                    case 104:
                                                        str1 = str1;
                                                        l2 -= (long)i21;
                                                        // Resetting String variable to a short value to prevent OOM
                                                        str1 = "";
                                                        str1 += str1;
                                                        Cls1.instanceCount = (long)Test0010.fFld;
                                                        i20 -= (int)c;
                                                        lArr2 = lArr2;
                                                        i24 = 1;
                                                        while (++i24 < 1) {
                                                            short s=-19904;
                                                            if (i20 != 0) {
                                                                vMeth1_check_sum += i15 + i16 + i17 + i18 + i19 + i20 +
                                                                    i21 + i22 + i23 + l2 + str1.length() + (int)c + i24
                                                                    + (b ? 1 : 0) + s1 + FuzzerUtils.checkSum(lArr2) +
                                                                    Double.doubleToLongBits(FuzzerUtils.checkSum(dArr))
                                                                    + FuzzerUtils.checkSum(sArr) +
                                                                    FuzzerUtils.checkSum(strArr2) +
                                                                    FuzzerUtils.checkSum(O5) + FuzzerUtils.checkSum(O6)
                                                                    + FuzzerUtils.checkSum(O7) +
                                                                    FuzzerUtils.checkSum(O8);
                                                                return;
                                                            }
                                                            i22 *= (int)s;
                                                            switch (((i15 % 4) * 5) + 122) {
                                                                case 136:
                                                                    l2 = (long)i22;
                                                                    if (true) break;
                                                                    O6 = O6;
                                                                    lArr2 = lArr2;
                                                                    Test0010.dFld += Test0010.dFld;
                                                                    i20 <<= (int)l2;
                                                                    break;
                                                                case 139:
                                                                    Test0010.iArrFld[i15 - 1] <<= (int)l2;
                                                                    switch (((i17 % 9) * 5) + 43) {
                                                                        case 81:
                                                                            Test0010.instanceCount *= (long)i21;
                                                                            i18 = i24;
                                                                            break;
                                                                        case 48:
                                                                            Test0010.fFld = (float)s;
                                                                            dArr[i15] += (double)c;
                                                                            i22 = (int)113.370F;
                                                                            if (b) continue;
                                                                            if (i22 != 0) {
                                                                                vMeth1_check_sum += i15 + i16 + i17 +
                                                                                    i18 + i19 + i20 + i21 + i22 + i23 +
                                                                                    l2 + str1.length() + (int)c + i24 +
                                                                                    (b ? 1 : 0) + s1 +
                                                                                    FuzzerUtils.checkSum(lArr2) +
                                                                                    Double.doubleToLongBits(FuzzerUtils.checkSum(dArr))
                                                                                    + FuzzerUtils.checkSum(sArr) +
                                                                                    FuzzerUtils.checkSum(strArr2) +
                                                                                    FuzzerUtils.checkSum(O5) +
                                                                                    FuzzerUtils.checkSum(O6) +
                                                                                    FuzzerUtils.checkSum(O7) +
                                                                                    FuzzerUtils.checkSum(O8);
                                                                                return;
                                                                            }
                                                                            i16 -= i15;
                                                                            str1 = str1;
                                                                            break;
                                                                        case 83:
                                                                            l2 += Test0010.instanceCount;
                                                                            Test0010.dFld *= (double)i16;
                                                                            break;
                                                                        case 88:
                                                                            Test0010.dFld = (double)i19;
                                                                            break;
                                                                        case 72:
                                                                            str1 = str1;
                                                                            break;
                                                                        case 82:
                                                                            str1 = str1;
                                                                            break;
                                                                        case 52:
                                                                            Test0010.iFld += (int)Test0010.fFld;
                                                                            break;
                                                                        case 87:
                                                                            i20 -= i24;
                                                                            break;
                                                                        case 53:
                                                                            if (false) break;
                                                                        default:
                                                                            if (b) break;
                                                                    }
                                                                    break;
                                                                case 126:
                                                                    if (b) continue;
                                                                case 134:
                                                                    Test0010.instanceCount %= (long)Test0010.dFld;
                                                                    break;
                                                            }
                                                        }
                                                        break;
                                                    case 102:
                                                        i18 -= (int)s1;
                                                        break;
                                                    case 98:
                                                        if (b) continue;
                                                        break;
                                                    default:
                                                        sArr[i15] = s1;
                                                }
                                            } while (--i23 > 0);
                                            break;
                                    }
                                case 124:
                                    break;
                                case 129:
                                    strArr2[i15] = "four";
                                    break;
                                case 114:
                                    // Resetting String variable to a short value to prevent OOM
                                    str1 = "hhhh";
                                    str1 += str1;
                                    break;
                                case 142:
                                case 153:
                                    if (b1) continue;
                                    break;
                                case 126:
                                    str1 = str1;
                                case 136:
                                    Test0010.iFld += i22;
                                    break;
                            }
                        }
                        catch (ArithmeticException exc10) {
                            i22 += Test0010.iFld;
                        }
                        finally {
                            try {
                                i16 = (i23 % Test0010.iArrFld[i15]);
                                i16 = (i21 % -216);
                                i16 = (i21 / -63723);
                            } catch (ArithmeticException a_e) {}
                        }
                    }
                    catch (NullPointerException exc11) {
                        b = b;
                    }
                }
            }
        }
        vMeth1_check_sum += i15 + i16 + i17 + i18 + i19 + i20 + i21 + i22 + i23 + l2 + str1.length() + (int)c + i24 +
            (b ? 1 : 0) + s1 + FuzzerUtils.checkSum(lArr2) + Double.doubleToLongBits(FuzzerUtils.checkSum(dArr)) +
            FuzzerUtils.checkSum(sArr) + FuzzerUtils.checkSum(strArr2) + FuzzerUtils.checkSum(O5) +
            FuzzerUtils.checkSum(O6) + FuzzerUtils.checkSum(O7) + FuzzerUtils.checkSum(O8);
    }

    public void mainTest0010(String[] strArr1) {

        long meth_res = 0;
        int i=-8, i61=-1, i62=139, i63=-3, i64=-55, i65=-48774, i66=-46144, i67=10, i68=211, i69=5935, i70=-13, i71=0,
            i73=-187;
        String str5="one", str6="four", strArr3[]=new String[N];
        byte by3=36;
        char cArr[]=new char[N];
        short sArr1[]=new short[N];
        long lArr3[]=new long[N];
        Cls O24=new Cls(), O26=new Cls(), O27=new Cls(), O28=new Cls(), O29=new Cls(), O30=new Cls();
        Cls1 O25=new Cls1(), O31=new Cls1();

        FuzzerUtils.init(strArr3, "two");
        FuzzerUtils.init(cArr, (char)1517);
        FuzzerUtils.init(sArr1, (short)-24218);
        FuzzerUtils.init(lArr3, -6L);

        for (i = (int) (2); i < 103; ++i) {
            strArr3[i - 1] = str5;
            synchronized (O25) {
                for (i63 = (int) (106); i63 > 4; i63 -= 2) {
                    by3 += (byte)i63;
                    switch ((i % 4) + 91) {
                        case 91:
                            Test0010.fFld = (float)Test0010.dFld;
                            Test0010.fFld += (float)i62;
                            for (i65 = (int) (1); i65 < 5; i65 += 2) {
                                Test0010.iFld -= (int)202L;
                                if (Test0010.bFld) {
                                    Test0010.fFld -= Test0010.fFld;
                                    Test0010.iArrFld[i63 - 1] += -63570;
                                    Test0010.cFld <<= (char)-8541;
                                    i64 -= 3;
                                    i62 = Test0010.iFld;
                                    switch (i % 1) {
                                        case 0:
                                            str5 = str5;
                                            for (i67 = (int) (1); i67 < 3; ++i67) {
                                                for (i69 = (int) (1); 2 > i69; i69++) {
                                                    i62 = (int)42117;
                                                    switch (((i % 2) * 5) + 66) {
                                                        case 73:
                                                            i62 += 13;
                                                            i62 = (int)Test0010.instanceCount;
                                                            Test0010.instanceCount ^= (long)-21244;
                                                            i66 *= (int)by3;
                                                            Test0010.fFld *= (float)i63;
                                                            switch (((i67 % 3) * 5) + 61) {
                                                                case 65:
                                                                    Test0010.instanceCount &= (long)11982;
                                                                    cArr[i69 - 1] = (char)Cls1.instanceCount;
                                                                    O26 = O24;
                                                                    Test0010.iFld -= i70;
                                                                    // Resetting String variable to a short value to
                                                                    // prevent OOM
                                                                    str5 = "";
                                                                    str5 += str5;
                                                                    break;
                                                                case 74:
                                                                    Test0010.instanceCount *= (long)i69;
                                                                    break;
                                                                case 66:
                                                                    i70 -= (int)Cls1.instanceCount;
                                                                    Test0010.iArrFld = Test0010.iArrFld;
                                                                    Cls.instanceCount -= Cls1.instanceCount;
                                                                    i68 -= (int)Test0010.fFld;
                                                                    i66 = Test0010.iFld;
                                                                    synchronized (O30) {
                                                                        int i72=0;
                                                                        i62 *= (int)Test0010.instanceCount;
                                                                        Test0010.iArrFld[i67] = (int)Cls1.instanceCount;
                                                                        i72 = Test0010.iFld;
                                                                        i62 = (int)Test0010.fFld;
                                                                        if (Test0010.bFld) continue;
                                                                        i68 *= i61;
                                                                        str5 = str5;
                                                                    }
                                                                    i62 -= (int)Test0010.fFld;
                                                                    switch (((i71 >>> 1) % 8) * 5) {
                                                                        case 3:
                                                                            Test0010.iArrFld = Test0010.iArrFld;
                                                                            i61 = (int)Test0010.instanceCount;
                                                                            break;
                                                                        case 9:
                                                                        case 15:
                                                                            Test0010.cFld -= (char)i67;
                                                                            i70 >>= i70;
                                                                            i71 += i;
                                                                            Test0010.dFld /= (double)70;
                                                                            if (Test0010.bFld) continue;
                                                                            i64 += i64;
                                                                            sArr1[i67 + 1] *= (short)-685;
                                                                            break;
                                                                        case 1:
                                                                            strArr3[i65] += str5;
                                                                            Test0010.iArrFld[i63 + 1] >>>= i69;
                                                                            synchronized (O31) {
                                                                                i66 ^= 0;
                                                                            }
                                                                            Cls.instanceCount <<= Test0010.instanceCount;
                                                                            i73 *= -79;
                                                                            break;
                                                                        case 13:
                                                                            i71 >>>= i66;
                                                                            by3 += (byte)Test0010.iFld;
                                                                            by3 += (byte)Test0010.fFld;
                                                                            iFld1 *= i67;
                                                                            i61 *= -19545;
                                                                            iFld1 >>= (int)Cls.instanceCount;
                                                                            Test0010.dFld += (double)183;
                                                                            switch ((i % 7) + 46) {
                                                                                case 46:
                                                                                    lArr3[i63] += (long)i61;
                                                                                    Cls.instanceCount -= (long)by3;
                                                                                    lArr3[i69 - 1] >>>= (long)i71;
                                                                                    break;
                                                                                case 47:
                                                                                    Cls1.instanceCount -= (long)by3;
                                                                                    Test0010.iFld =
                                                                                        (int)2323433640153668126L;
                                                                                    i70 ^= i71;
                                                                                    Test0010.fFld += (float)9;
                                                                                    // Resetting String variable to a
                                                                                    // short value to prevent OOM
                                                                                    str6 = "";
                                                                                    str6 += str6;
                                                                                    Test0010.fFld *= (float)i;
                                                                                    break;
                                                                                case 48:
                                                                                case 49:
                                                                                    strArr3[i65 + 1] = str5;
                                                                                    str5 = str5;
                                                                                    Test0010.fFld = (float)-32025;
                                                                                    Cls.instanceCount = (long)9;
                                                                                    i61 += i61;
                                                                                    i71 += 12;
                                                                                    i64 <<= i64;
                                                                                    break;
                                                                                case 50:
                                                                                    Test0010.iArrFld[(i64 >>> 1) % N] <<=
                                                                                        i61;
                                                                                    break;
                                                                                case 51:
                                                                                    i62 -= i71;
                                                                                case 52:
                                                                                    i66 = i66;
                                                                            }
                                                                            break;
                                                                        case 38:
                                                                            Test0010.iArrFld[i65 - 1] = Test0010.iFld;
                                                                            break;
                                                                        case 33:
                                                                            i62 -= -58;
                                                                            break;
                                                                        case 40:
                                                                            Test0010.dFld = (double)Cls.instanceCount;
                                                                            break;
                                                                    }
                                                                    break;
                                                                default:
                                                                    O30 = O30;
                                                            }
                                                            break;
                                                        case 70:
                                                            Cls.instanceCount = (long)Test0010.dFld;
                                                    }
                                                }
                                            }
                                            break;
                                    }
                                } else {
                                    by3 = (byte)469;
                                }
                            }
                            break;
                        case 92:
                            Test0010.bFld = Test0010.bFld;
                            break;
                        case 93:
                            str5 = "two";
                            break;
                        case 94:
                            Cls1.instanceCount -= (long)i;
                            break;
                    }
                }
            }
        }

        FuzzerUtils.out.println("i i61 str5 = " + i + "," + i61 + "," + str5.length());
        FuzzerUtils.out.println("i62 i63 i64 = " + i62 + "," + i63 + "," + i64);
        FuzzerUtils.out.println("by3 i65 i66 = " + by3 + "," + i65 + "," + i66);
        FuzzerUtils.out.println("i67 i68 i69 = " + i67 + "," + i68 + "," + i69);
        FuzzerUtils.out.println("i70 i71 i73 = " + i70 + "," + i71 + "," + i73);
        FuzzerUtils.out.println("str6 strArr3 cArr = " + str6.length() + "," + FuzzerUtils.checkSum(strArr3) + "," +
            FuzzerUtils.checkSum(cArr));
        FuzzerUtils.out.println("sArr1 lArr3 O24 = " + FuzzerUtils.checkSum(sArr1) + "," + FuzzerUtils.checkSum(lArr3)
            + "," + FuzzerUtils.checkSum(O24));
        FuzzerUtils.out.println("O26 O27 O28 = " + FuzzerUtils.checkSum(O26) + "," + FuzzerUtils.checkSum(O27) + "," +
            FuzzerUtils.checkSum(O28));
        FuzzerUtils.out.println("O29 O30 O25 = " + FuzzerUtils.checkSum(O29) + "," + FuzzerUtils.checkSum(O30) + "," +
            FuzzerUtils.checkSum(O25));
        FuzzerUtils.out.println("O31 Cls Cls1 = " + FuzzerUtils.checkSum(O31) + "," + Cls.instanceCount + "," +
            Cls1.instanceCount);

        FuzzerUtils.out.println("Test0010.instanceCount Test0010.dFld Test0010.fFld = " + Test0010.instanceCount + "," +
            Double.doubleToLongBits(Test0010.dFld) + "," + Float.floatToIntBits(Test0010.fFld));
        FuzzerUtils.out.println("Test0010.iFld Test0010.cFld Test0010.bFld = " + Test0010.iFld + "," + (int)Test0010.cFld + "," +
            (Test0010.bFld ? 1 : 0));
        FuzzerUtils.out.println("iFld1 Test0010.iArrFld Cls = " + iFld1 + "," + FuzzerUtils.checkSum(Test0010.iArrFld) + "," +
            Cls.instanceCount);
        FuzzerUtils.out.println("Cls1 = " + Cls1.instanceCount);

        FuzzerUtils.out.println("vMeth1_check_sum: " + vMeth1_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test0010 _instance = new Test0010();
            for (int i = 0; i < 10; i++ ) {
                try {
                    _instance.mainTest0010(strArr);
                 } catch (OutOfMemoryError ex) {
                    ex.printStackTrace(FuzzerUtils.err);
                    System.exit(1);
                 } catch (Exception ex) {
                    FuzzerUtils.out.println(ex.getClass().getCanonicalName());
                 }
             }
         } catch (Exception ex) {
            FuzzerUtils.out.println(ex.getClass().getCanonicalName());
         }
    }
}
///////////////////////////////////////////////////////////////////////
class Cls {

    public static final int N = 128;

    public static long instanceCount=8441587380835863779L;
    public static short sFld=-30381;
    public static String strArrFld[]=new String[N];

    static {
        FuzzerUtils.init(Cls.strArrFld, "one");
    }

    public static long Cls_check_sum = 0;
    public static long iMeth_check_sum = 0;
    public static long vMeth_check_sum = 0;

    public static void vMeth(int i10, String str, long l1) {

        long meth_res = 0;
        int i11=9, i12=1, i13=-61996, i14=-98, i25=-13, i26=-238, i27=-12, i28=2, i29=-2674, i30=-7, i31=-43173,
            i32=-7, i33=-54744, i34=-6, i35=44940, i36=-4, iArr1[]=new int[N];
        boolean b2=true;
        char c1=52373;
        byte by1=96;
        double dArr1[]=new double[N];
        Cls1 O3=new Cls1(), O4=new Cls1(), O9=new Cls1(), O10=new Cls1(), O11=new Cls1(), O12=new Cls1(), O13=new
            Cls1();

        FuzzerUtils.init(dArr1, 23.47504);
        FuzzerUtils.init(iArr1, 155);

        for (i11 = (int) (95); i11 > 1; --i11) {
            for (i13 = (int) (16); i13 > 1; i13 -= 3) {
                Test0010.vMeth1();
                switch (((i11 % 2) * 5) + 5) {
                    case 7:
                        for (i25 = (int) (4); i25 > 1; i25 -= 3) {
                            i10 -= (int)0.129038;
                            dArr1[i25] = (double)204;
                            for (i27 = (int) (1); i27 < 4; i27 += 2) {
                                Cls.sFld = (short)i12;
                                iArr1 = iArr1;
                            }
                            i29 = 4;
                            do {
                                Test0010.fFld = (float)i11;
                                iArr1[i25 + 1] -= (int)l1;
                                if (b2) break;
                                Test0010.dFld = (double)i29;
                                i26 -= i27;
                            } while (--i29 > 0);
                            iArr1 = iArr1;
                            b2 = b2;
                        }
                        i30 = 4;
                        while ((i30 -= 3) > 0) {
                            i12 <<= i14;
                            Test0010.iFld += (int)Cls1.instanceCount;
                            switch (((Test0010.iFld >>> 1) % 2) + 100) {
                                case 100:
                                    iArr1[i30] &= i27;
                                    Cls.strArrFld[i11 + 1] = str;
                                    iArr1[i30] = i11;
                                    c1 = (char)Cls.instanceCount;
                                    if (b2) {
                                        for (i31 = (int) (2); i31 > 1; --i31) {
                                            if (b2) break;
                                            i14 -= i29;
                                            i14 -= (int)Test0010.fFld;
                                            i14 -= i27;
                                            i32 = (int)Cls.instanceCount;
                                            for (i33 = (int) (2); i33 > i31; i33 -= 3) {
                                                Cls.sFld >>= (short)228;
                                                Test0010.iFld <<= i28;
                                                Test0010.fFld += (float)Cls.sFld;
                                                i14 |= Test0010.iFld;
                                                if (true) break;
                                                i10 += 195;
                                                Cls.instanceCount -= (long)0.276F;
                                                Test0010.fFld -= (float)Test0010.dFld;
                                            }
                                        }
                                        for (i35 = (int) (1); i35 < 2; i35++) {
                                            i36 = Test0010.iFld;
                                            Test0010.fFld += (float)170;
                                        }
                                    } else if (b2) {
                                        Test0010.fFld += (float)-14;
                                    } else {
                                        if (Test0010.iFld != 0) {
                                            vMeth_check_sum += i10 + str.length() + l1 + i11 + i12 + i13 + i14 + i25 +
                                                i26 + i27 + i28 + i29 + (b2 ? 1 : 0) + i30 + (int)c1 + i31 + i32 + i33
                                                + i34 + by1 + i35 + i36 +
                                                Double.doubleToLongBits(FuzzerUtils.checkSum(dArr1)) +
                                                FuzzerUtils.checkSum(iArr1) + FuzzerUtils.checkSum(O3) +
                                                FuzzerUtils.checkSum(O4) + FuzzerUtils.checkSum(O9) +
                                                FuzzerUtils.checkSum(O10) + FuzzerUtils.checkSum(O11) +
                                                FuzzerUtils.checkSum(O12) + FuzzerUtils.checkSum(O13);
                                            return;
                                        }
                                    }
                                case 101:
                                    i26 <<= i28;
                                    break;
                            }
                        }
                    case 11:
                        Cls1.instanceCount = l1;
                        break;
                }
            }
        }
        vMeth_check_sum += i10 + str.length() + l1 + i11 + i12 + i13 + i14 + i25 + i26 + i27 + i28 + i29 + (b2 ? 1 : 0)
            + i30 + (int)c1 + i31 + i32 + i33 + i34 + by1 + i35 + i36 +
            Double.doubleToLongBits(FuzzerUtils.checkSum(dArr1)) + FuzzerUtils.checkSum(iArr1) +
            FuzzerUtils.checkSum(O3) + FuzzerUtils.checkSum(O4) + FuzzerUtils.checkSum(O9) + FuzzerUtils.checkSum(O10)
            + FuzzerUtils.checkSum(O11) + FuzzerUtils.checkSum(O12) + FuzzerUtils.checkSum(O13);
    }

    public static int iMeth(long l, int i6) {

        long meth_res = 0;
        int i7=119, i8=33563, i9=12, i37=152, i38=0, i39=-126, i40=18748, i41=-209, i42=-6, i43=-248, i44=-6, i45=2,
            i46=7, i47=-38370, i48=-176, iArr2[]=new int[N];
        double d=0.43358, d1=-1.44684, d2=-2.7078;
        String str2="one", str3="three";
        byte by2=-92;
        char c2=61156;
        boolean b3=true;
        long lArr1[]=new long[N];
        float fArr[]=new float[N];
        Cls1 O2=new Cls1(), O14=new Cls1(), O15=new Cls1(), O16=new Cls1(), O17=new Cls1(), O18=new Cls1(), O19=new
            Cls1();

        FuzzerUtils.init(lArr1, 164L);
        FuzzerUtils.init(iArr2, -44908);
        FuzzerUtils.init(fArr, 2.680F);

        i7 = 1;
        while ((i7 += 2) < 124) {
            d *= (double)(++lArr1[i7]);
            for (i8 = (int) (1); i8 < 25; i8++) {
                vMeth(4, str2, Test0010.instanceCount);
                for (d1 = (double) (1); d1 < 2; d1 += 2) {
                    Cls1.instanceCount = (long)i7;
                    str2 = str2;
                    Test0010.dFld += (double)Cls.sFld;
                    i9 >>= 27;
                    i9 *= 31;
                    i38 = 1;
                    while (++i38 < 2) {
                        str2 = str2;
                        i37 = i8;
                    }
                    for (d2 = (double) (1); d2 < 2; d2 += 2) {
                        i9 += i38;
                        i37 = i7;
                    }
                }
                iArr2[i7 - 1] = (int)Test0010.instanceCount;
            }
            i40 = 1;
            do {
                i41 = 1;
                do {
                    i6 *= i9;
                    i6 -= i9;
                } while ((i41 -= 3) > 0);
                str3 = str2;
                lArr1 = lArr1;
                synchronized (O16) {
                    Test0010.iFld = i38;
                    c2 -= (char)Cls.instanceCount;
                    for (i43 = (int) (1); i43 > 1; i43 -= 3) {
                        i42 ^= (int)-39539L;
                        i45 = 1;
                        while (++i45 < 1) {
                            iArr2[i43 + 1] = (int)Test0010.fFld;
                            i9 = i40;
                            if (b3) continue;
                            for (i46 = (int) (1); i46 > 1; i46 -= 2) {
                                Cls.strArrFld[i40 + 1] += str2;
                                synchronized (O19) {
                                    i47 &= (int)Cls1.instanceCount;
                                    iArr2 = FuzzerUtils.int1array(N, (int)-231);
                                    // Resetting String variable to a short value to prevent OOM
                                    str2 = "";
                                    str2 += "four";
                                    iArr2[i46] -= i43;
                                    fArr[i46] -= (float)i38;
                                    lArr1[i43] = (long)Test0010.dFld;
                                    lArr1 = lArr1;
                                }
                            }
                            Test0010.fFld *= (float)Cls.sFld;
                            Cls.instanceCount <<= (long)i45;
                            i42 *= -12544;
                        }
                    }
                }
            } while (++i40 < 25);
        }
        meth_res = l + i6 + i7 + Double.doubleToLongBits(d) + i8 + i9 + str2.length() + Double.doubleToLongBits(d1) +
            i37 + i38 + Double.doubleToLongBits(d2) + i39 + by2 + i40 + i41 + str3.length() + i42 + (int)c2 + i43 + i44
            + i45 + (b3 ? 1 : 0) + i46 + i47 + i48 + FuzzerUtils.checkSum(lArr1) + FuzzerUtils.checkSum(iArr2) +
            Double.doubleToLongBits(FuzzerUtils.checkSum(fArr)) + FuzzerUtils.checkSum(O2) + FuzzerUtils.checkSum(O14)
            + FuzzerUtils.checkSum(O15) + FuzzerUtils.checkSum(O16) + FuzzerUtils.checkSum(O17) +
            FuzzerUtils.checkSum(O18) + FuzzerUtils.checkSum(O19);
        iMeth_check_sum += meth_res;
        return (int)meth_res;
    }

    public  Cls() {

        instanceCount++;
        long meth_res = 0;
        int i1=36, i2=-2, i3=1, i4=-26107, i5=-13104, i49=189, i50=-134, i51=-1, i52=-19556, i53=0, i54=13, i55=-58566,
            i56=-63694, i57=-46428, i58=-187, i59=10, iArr[]=new int[N], iArr3[]=new int[N];
        float f=70.318F;
        byte by=121;
        String str4="one";
        boolean b4=false;
        long lArr[]=new long[N];
        Cls1 O=new Cls1(), O1=new Cls1(), O20=new Cls1(), O21=new Cls1(), O22=new Cls1(), O23=new Cls1();

        FuzzerUtils.init(iArr, -84);
        FuzzerUtils.init(lArr, -192L);
        FuzzerUtils.init(iArr3, -93);

        try {
            for (i1 = (int) (115); i1 > 7; i1--) {
                switch (((i1 % 8) * 5) + 1) {
                    case 14:
                        switch ((i1 % 2) + 34) {
                            case 34:
                                synchronized (O1) {
                                    i4 = 1;
                                    do {
                                        i5 = 1;
                                        do {
                                            Cls1.instanceCount = (long)f;
                                            iArr[i5] += i1;
                                            i2 -= (int)(-(lArr[i5]++));
                                        } while (++i5 < 1);
                                    } while (++i4 < 14);
                                    iArr[i1] += (int)(iMeth(Cls.instanceCount, i1) - Cls.instanceCount);
                                    // Resetting String variable to a short value to prevent OOM
                                    str4 = "";
                                    str4 += str4;
                                    Cls.instanceCount = (long)i5;
                                    i2 = (int)Test0010.instanceCount;
                                }
                                Test0010.fFld += (float)Test0010.instanceCount;
                                for (i49 = (int) (1); i49 < 14; i49 += 3) {
                                    switch ((i49 % 5) + 101) {
                                        case 101:
                                            if (i51 != 0) {
                                                return;
                                            }
                                            if (b4) continue;
                                            i52 = 4;
                                            while ((i52 -= 2) > 0) {
                                                for (i53 = (int) (i49); i53 < 2; i53++) {
                                                    i2 |= i1;
                                                    i3 -= (int)-1.10161;
                                                    Test0010.fFld = (float)by;
                                                }
                                            }
                                            switch (((i55 >>> 1) % 2) + 120) {
                                                case 120:
                                                    i55 *= i49;
                                                    switch (((i2 >>> 1) % 5) + 83) {
                                                        case 83:
                                                            iArr[i1] *= i51;
                                                            f = (float)-25380;
                                                            Test0010.dFld *= (double)i51;
                                                            Cls.instanceCount = (long)Test0010.iFld;
                                                            i50 -= (int)Test0010.instanceCount;
                                                        case 84:
                                                            i3 &= Test0010.iFld;
                                                            i54 *= i1;
                                                            Test0010.iFld += (int)-422904572L;
                                                        case 85:
                                                            switch ((i1 % 2) + 76) {
                                                                case 76:
                                                                    for (i56 = (int) (1); i56 < 4; i56++) {
                                                                        str4 = str4;
                                                                        switch ((i49 % 5) + 98) {
                                                                            case 98:
                                                                                for (i58 = (int) (1); i58 < 2; i58 +=
                                                                                    3) {
                                                                                    i55 = i59;
                                                                                    str4 = str4;
                                                                                }
                                                                            case 99:
                                                                                iArr[i56] = i50;
                                                                            case 100:
                                                                                i3 >>= i56;
                                                                                break;
                                                                            case 101:
                                                                                i54 = i56;
                                                                                break;
                                                                            case 102:
                                                                                i2 = (int)Cls.instanceCount;
                                                                                break;
                                                                        }
                                                                    }
                                                                    break;
                                                                case 77:
                                                                    str4 = "three";
                                                                    break;
                                                                default:
                                                            }
                                                            break;
                                                        case 86:
                                                            Test0010.instanceCount = (long)i55;
                                                            break;
                                                        case 87:
                                                            Cls.instanceCount -= (long)i58;
                                                            break;
                                                    }
                                                    break;
                                                case 121:
                                                    break;
                                            }
                                        case 102:
                                            Test0010.dFld = (double)i5;
                                            break;
                                        case 103:
                                            // Resetting String variable to a short value to prevent OOM
                                            str4 = "hhhh";
                                            str4 += str4;
                                            break;
                                        case 104:
                                            Cls.strArrFld[i1] += str4;
                                        case 105:
                                            Cls1.instanceCount = (long)i56;
                                            break;
                                    }
                                }
                            case 35:
                                iArr[i1 - 1] += i49;
                                break;
                            default:
                        }
                        break;
                    case 29:
                        if (i51 != 0) {
                            return;
                        }
                    case 40:
                        if (b4) continue;
                        break;
                    case 30:
                        iArr3[i1] -= (int)Test0010.instanceCount;
                        break;
                    case 16:
                        break;
                    case 41:
                        break;
                    case 24:
                        Test0010.instanceCount = (long)i50;
                        break;
                    case 36:
                        b4 = b4;
                        break;
                }
            }
        }
        catch (NullPointerException exc12) {
            iArr[(Test0010.iFld >>> 1) % N] -= -16039;
        }
        finally {
            i51 = i53;
        }
        meth_res = i1 + i2 + i3 + i4 + i5 + Float.floatToIntBits(f) + by + str4.length() + i49 + i50 + i51 + (b4 ? 1 :
            0) + i52 + i53 + i54 + i55 + i56 + i57 + i58 + i59 + FuzzerUtils.checkSum(iArr) +
            FuzzerUtils.checkSum(lArr) + FuzzerUtils.checkSum(iArr3) + FuzzerUtils.checkSum(O) +
            FuzzerUtils.checkSum(O1) + FuzzerUtils.checkSum(O20) + FuzzerUtils.checkSum(O21) +
            FuzzerUtils.checkSum(O22) + FuzzerUtils.checkSum(O23);
        Cls_check_sum += meth_res;
        return;
    }

}
///////////////////////////////////////////////////////////////////////
class Cls1 {

    public static final int N = 128;

    public static long instanceCount=-1L;

}
///////////////////////////////////////////////////////////////////////
//DEBUG  Test0010 ->  Test0010
//DEBUG  main ->  main
//DEBUG  mainTest0010 ->  mainTest0010
//DEBUG  Cls ->  Cls mainTest0010
//DEBUG  Cls1 ->  Cls1 vMeth1 vMeth iMeth Cls mainTest0010
//DEBUG  iMeth ->  iMeth Cls mainTest0010
//DEBUG  vMeth ->  vMeth iMeth Cls mainTest0010
//DEBUG  vMeth1 ->  vMeth1 vMeth iMeth Cls mainTest0010
//DEBUG  Depth = 5
//DEBUG  Classes = 3
//DEBUG  static objects = {}
