// Generated by Java* Fuzzer test generator (1.0.001). Sun Mar 29 19:41:29 2026
public class Test0032 {

    public static final int N = 128;

    public static long instanceCount=3758194537L;
    public static volatile char cFld=50209;
    public static double dFld=-1.280;
    public static volatile boolean bFld=false;
    public static byte byFld=43;
    public static String strFld="two";
    public static String strFld1="four";
    public static int iFld=-6;
    public String strFld2="four";
    public long lFld=-8572L;
    public int iFld1=-65;
    public static boolean bArrFld[]=new boolean[N];
    public static int iArrFld[]=new int[N];
    public static double dArrFld[]=new double[N];
    public static long lArrFld[]=new long[N];
    public static volatile short sArrFld[]=new short[N];

    static {
        FuzzerUtils.init(Test0032.bArrFld, false);
        FuzzerUtils.init(Test0032.iArrFld, -10);
        FuzzerUtils.init(Test0032.dArrFld, 0.78323);
        FuzzerUtils.init(Test0032.lArrFld, -1720705866937426682L);
        FuzzerUtils.init(Test0032.sArrFld, (short)-14699);
    }

    public static long vMeth_check_sum = 0;
    public static long vMeth1_check_sum = 0;
    public static long vMeth2_check_sum = 0;

    public static void vMeth2() {

        long meth_res = 0;
        int i6=5, i7=152, i8=2, i9=0, i10=-54028, i11=177, i12=59237, i13=847, i14=-209, i15=-191, i16=32476, i17=38320;
        byte by=-72;
        long l1=15544L, l2=7L;
        short s1=-598;
        float f3=-115.63F;
        String str1="three", strArr2[]=new String[N];
        Cls O4=new Cls(), O5=new Cls(), O6=new Cls(), O7=new Cls(), O8=new Cls();

        FuzzerUtils.init(strArr2, "four");

        i6 = 1;
        do {
            by -= (byte)Test0032.instanceCount;
            Test0032.instanceCount = Test0032.instanceCount;
            try {
                i7 = (i6 % i6);
                i7 = (i7 % 33430);
                i8 = (Test0032.iArrFld[i6] % 17402);
            } catch (ArithmeticException a_e) {}
            for (l1 = (long) (14); l1 > 1; --l1) {
                s1 |= (short)55380;
                i9 <<= i6;
                by >>>= (byte)i8;
                Test0032.instanceCount = (long)f3;
                synchronized (O5) {
                    for (i11 = (int) (2); i11 > 1; i11 -= 2) {
                        str1 = str1;
                        i9 &= i10;
                        i9 *= (int)f3;
                        i12 -= 6;
                        O6 = O6;
                        i7 += (int)-40L;
                        strArr2 = strArr2;
                        switch ((int)((l1 % 3) + 4)) {
                            case 4:
                                i9 = 229;
                                i12 = i7;
                                Test0032.instanceCount = (long)i9;
                                break;
                            case 5:
                                i10 &= -3;
                                if (true) continue;
                                switch ((i6 % 6) + 123) {
                                    case 123:
                                        Test0032.iArrFld[(int)(l1 + 1)] -= i12;
                                        break;
                                    case 124:
                                        strArr2[(int)(l1 + 1)] += str1;
                                        for (i13 = (int) (l1); i13 < 2; i13 += 3) {
                                            for (i15 = (int) (1); i15 < 1; ++i15) {
                                                if (i6 != 0) {
                                                    vMeth2_check_sum += i6 + by + i7 + i8 + l1 + i9 + s1 +
                                                        Float.floatToIntBits(f3) + i10 + i11 + i12 + str1.length() +
                                                        i13 + i14 + i15 + i16 + i17 + l2 +
                                                        FuzzerUtils.checkSum(strArr2) + FuzzerUtils.checkSum(O4) +
                                                        FuzzerUtils.checkSum(O5) + FuzzerUtils.checkSum(O6) +
                                                        FuzzerUtils.checkSum(O7) + FuzzerUtils.checkSum(O8);
                                                    return;
                                                }
                                                i12 = i9;
                                                Test0032.iArrFld = Test0032.iArrFld;
                                                i10 |= i10;
                                            }
                                            if (i8 != 0) {
                                                vMeth2_check_sum += i6 + by + i7 + i8 + l1 + i9 + s1 +
                                                    Float.floatToIntBits(f3) + i10 + i11 + i12 + str1.length() + i13 +
                                                    i14 + i15 + i16 + i17 + l2 + FuzzerUtils.checkSum(strArr2) +
                                                    FuzzerUtils.checkSum(O4) + FuzzerUtils.checkSum(O5) +
                                                    FuzzerUtils.checkSum(O6) + FuzzerUtils.checkSum(O7) +
                                                    FuzzerUtils.checkSum(O8);
                                                return;
                                            }
                                            i16 *= i10;
                                        }
                                        switch (((i16 >>> 1) % 1) + 20) {
                                            case 20:
                                                str1 = str1;
                                                if (true) break;
                                                l2 = 2;
                                                do {
                                                    switch ((((i14 >>> 1) % 7) * 5) + 110) {
                                                        case 114:
                                                            Test0032.instanceCount = (long)i7;
                                                            i14 -= (int)l1;
                                                            i12 -= i14;
                                                            i17 *= (int)0L;
                                                            break;
                                                        case 137:
                                                            if (Test0032.bFld) continue;
                                                            Test0032.dFld = (double)i9;
                                                            break;
                                                        case 112:
                                                            i7 -= i16;
                                                            break;
                                                        case 142:
                                                            i9 += (int)-1.632F;
                                                        case 121:
                                                            break;
                                                        case 111:
                                                            Test0032.dArrFld[(int)(l2)] -= (double)Cls.instanceCount;
                                                            break;
                                                        case 126:
                                                            str1 = str1;
                                                            break;
                                                        default:
                                                    }
                                                } while ((l2 -= 2) > 0);
                                            default:
                                                i14 >>= i17;
                                        }
                                        break;
                                    case 125:
                                        break;
                                    case 126:
                                        i8 += (int)s1;
                                        break;
                                    case 127:
                                        i16 &= i12;
                                        break;
                                    case 128:
                                        try {
                                            i16 = (-1161244001 / i16);
                                            i14 = (i17 % i6);
                                            i8 = (i8 / Test0032.iArrFld[i11]);
                                        } catch (ArithmeticException a_e) {}
                                        break;
                                }
                            case 6:
                        }
                    }
                }
            }
        } while (++i6 < 110);
        vMeth2_check_sum += i6 + by + i7 + i8 + l1 + i9 + s1 + Float.floatToIntBits(f3) + i10 + i11 + i12 +
            str1.length() + i13 + i14 + i15 + i16 + i17 + l2 + FuzzerUtils.checkSum(strArr2) + FuzzerUtils.checkSum(O4)
            + FuzzerUtils.checkSum(O5) + FuzzerUtils.checkSum(O6) + FuzzerUtils.checkSum(O7) + FuzzerUtils.checkSum(O8);
    }

    public static void vMeth1(float f1) {

        long meth_res = 0;
        float f2=-1.38F, fArr[]=new float[N];
        int i5=13, i18=-17418, i19=-59937, i20=-61719, i21=12, i22=-105, i23=-46896, i24=0, i25=-5, i26=54487, i27=-10,
            i28=-47445, i29=-24144, i30=-5, i31=-121, i32=-116;
        short s2=545;
        double d=-114.61920;
        String strArr3[]=new String[N];
        Cls O3=new Cls(), O9=new Cls(), O10=new Cls(), O11=new Cls(), O12=new Cls(), O13=new Cls(), O14=new Cls(),
            O15=new Cls();

        FuzzerUtils.init(strArr3, "two");
        FuzzerUtils.init(fArr, 1.973F);

        for (f2 = (float) (109); f2 > 2; --f2) {
            if (((Test0032.dArrFld[(int)(f2 + 1)] * Test0032.iArrFld[(int)(f2 + 1)]) != Math.abs(--i5)) | true) continue;
            i5 -= (int)(Test0032.dFld++);
            vMeth2();
            synchronized (O9) {
                i19 = 1;
                do {
                    Test0032.bArrFld[i19 - 1] = true;
                    i18 = (int)Cls.instanceCount;
                    for (i20 = (int) (1); i20 < 1; i20 += 2) {
                        Test0032.iArrFld[i19 + 1] += (int)f2;
                        f1 = (float)i5;
                        i18 = i18;
                    }
                    for (i22 = (int) (1); i22 < 1; i22++) {
                        synchronized (O12) {
                            Test0032.iArrFld[(int)(f2 + 1)] += -171;
                            i25 = 1;
                            do {
                                Test0032.iArrFld = Test0032.iArrFld;
                                i5 += (int)Test0032.dFld;
                                Cls.instanceCount <<= (long)Test0032.byFld;
                                Test0032.dFld *= (double)i23;
                                Test0032.cFld -= (char)Test0032.byFld;
                                s2 = (short)Test0032.byFld;
                                Test0032.strFld = Test0032.strFld;
                                for (i26 = (int) (1); i26 > 1; i26--) {
                                    // Resetting String variable to a short value to prevent OOM
                                    Test0032.strFld = "";
                                    Test0032.strFld += Test0032.strFld;
                                    Test0032.lArrFld[i22 + 1] = Cls.instanceCount;
                                }
                                i23 -= (int)f1;
                            } while ((i25 += 3) < 1);
                            strArr3[i19] += Test0032.strFld;
                        }
                        Test0032.bFld = Test0032.bFld;
                        i18 >>= i27;
                        fArr[(int)(f2)] -= (float)Test0032.instanceCount;
                        i23 += (int)Test0032.instanceCount;
                        Test0032.iArrFld[(int)(f2 + 1)] = (int)f2;
                        d = 1;
                        do {
                            switch ((((i23 >>> 1) % 9) * 5) + 7) {
                                case 46:
                                    for (i28 = (int) (1); 1 > i28; i28 += 3) {
                                        i5 *= i19;
                                        if (Test0032.bFld) continue;
                                        f1 += f1;
                                        i27 >>= (int)-98L;
                                    }
                                    break;
                                case 38:
                                    // Resetting String variable to a short value to prevent OOM
                                    Test0032.strFld = "";
                                    Test0032.strFld += "four";
                                    for (i30 = (int) (1); i30 < 1; i30 += 3) {
                                        i24 &= i31;
                                        if (i5 != 0) {
                                            vMeth1_check_sum += Float.floatToIntBits(f1) + Float.floatToIntBits(f2) +
                                                i5 + i18 + i19 + i20 + i21 + i22 + i23 + i24 + i25 + s2 + i26 + i27 +
                                                Double.doubleToLongBits(d) + i28 + i29 + i30 + i31 + i32 +
                                                FuzzerUtils.checkSum(strArr3) +
                                                Double.doubleToLongBits(FuzzerUtils.checkSum(fArr)) +
                                                FuzzerUtils.checkSum(O3) + FuzzerUtils.checkSum(O9) +
                                                FuzzerUtils.checkSum(O10) + FuzzerUtils.checkSum(O11) +
                                                FuzzerUtils.checkSum(O12) + FuzzerUtils.checkSum(O13) +
                                                FuzzerUtils.checkSum(O14) + FuzzerUtils.checkSum(O15);
                                            return;
                                        }
                                        // Resetting String variable to a short value to prevent OOM
                                        Test0032.strFld = "";
                                        Test0032.strFld += Test0032.strFld;
                                    }
                                    break;
                                case 21:
                                    Test0032.lArrFld[(int)(d + 1)] <<= (long)i19;
                                    break;
                                case 27:
                                    i5 = i18;
                                    break;
                                case 34:
                                    Cls.instanceCount = Cls.instanceCount;
                                    break;
                                case 50:
                                    f1 -= (float)Test0032.instanceCount;
                                    break;
                                case 48:
                                    i18 = (int)Test0032.byFld;
                                    break;
                                case 29:
                                    i21 = (int)s2;
                                    break;
                                case 37:
                                    i27 >>= i32;
                            }
                        } while (--d > 0);
                    }
                } while (++i19 < 15);
            }
        }
        vMeth1_check_sum += Float.floatToIntBits(f1) + Float.floatToIntBits(f2) + i5 + i18 + i19 + i20 + i21 + i22 +
            i23 + i24 + i25 + s2 + i26 + i27 + Double.doubleToLongBits(d) + i28 + i29 + i30 + i31 + i32 +
            FuzzerUtils.checkSum(strArr3) + Double.doubleToLongBits(FuzzerUtils.checkSum(fArr)) +
            FuzzerUtils.checkSum(O3) + FuzzerUtils.checkSum(O9) + FuzzerUtils.checkSum(O10) + FuzzerUtils.checkSum(O11)
            + FuzzerUtils.checkSum(O12) + FuzzerUtils.checkSum(O13) + FuzzerUtils.checkSum(O14) +
            FuzzerUtils.checkSum(O15);
    }

    public static void vMeth(String str, long l) {

        long meth_res = 0;
        int i2=14, i3=-28, i4=44292, i33=61773, i34=0, i35=-150, i36=21649, i37=174, i38=-6, i39=42014, i40=-115,
            i41=-182;
        float f4=1.999F;
        short s3=-20482;
        long l3=3050535666934886494L;
        double d1=-2.111631;
        String strArr4[][]=new String[N][N];
        Cls O1=new Cls(), O2=new Cls(), O16=new Cls(), O17=new Cls(), O18=new Cls(), O19=new Cls();

        FuzzerUtils.init(strArr4, "one");

        try {
            for (i2 = (int) (121); i2 > (4 - 128); i2 -= 3) {
                if (Test0032.bFld) {
                    synchronized (O2) {
                        try {
                            vMeth1(f4);
                            i4 = i4;
                        }
                        catch (ArrayIndexOutOfBoundsException exc13) {
                            switch (((i2 % 1) * 5) + 18) {
                                case 21:
                                    i4 -= i4;
                                    break;
                                default:
                                    try {
                                        i33 = 1;
                                        while (++i33 < 12) {
                                            // Resetting String variable to a short value to prevent OOM
                                            str = "";
                                            str += str;
                                        }
                                        l |= (long)i2;
                                        if (true) {
                                            Cls.instanceCount += (long)f4;
                                            for (i34 = (int) (1 - 128); i34 < 12; i34 += 3) {
                                                i3 <<= (int)l;
                                                Test0032.cFld = (char)i2;
                                                Test0032.lArrFld[i2 - 1] *= (long)i2;
                                                O1 = O2;
                                                Test0032.instanceCount *= (long)118;
                                                for (i36 = (int) (1); i36 > i2; --i36) {
                                                    i3 -= (int)Cls.instanceCount;
                                                    l3 = 1;
                                                    do {
                                                        synchronized (O18) {
                                                            i4 -= i38;
                                                            Cls.instanceCount = (long)i37;
                                                            Test0032.lArrFld[i36] += (long)i39;
                                                        }
                                                        i39 -= -14;
                                                        i4 += i4;
                                                        Test0032.iArrFld[i34 + 1] >>= 0;
                                                    } while (++l3 < 1);
                                                    i39 += i38;
                                                    O2 = new Cls();
                                                    Cls.instanceCount = (long)i33;
                                                    f4 *= f4;
                                                    switch ((i34 % 2) + 83) {
                                                        case 83:
                                                            Test0032.dArrFld = Test0032.dArrFld;
                                                            for (d1 = (double) ((long)1 + (long)128); d1 > 1; d1 -= 2) {
                                                                i35 >>= (int)l3;
                                                                Test0032.dFld += (double)56863L;
                                                                switch (((i36 >>> 1) % 6) + 67) {
                                                                    case 67:
                                                                    case 68:
                                                                        i4 |= (int)s3;
                                                                        strArr4[(int)(d1 - 1)][i2 - 1] = Test0032.strFld1;
                                                                        if (Test0032.bFld) break;
                                                                        Cls.instanceCount -= Cls.instanceCount;
                                                                    case 69:
                                                                        i38 <<= (int)Test0032.byFld;
                                                                        break;
                                                                    case 70:
                                                                        i39 >>= i36;
                                                                    case 71:
                                                                        break;
                                                                    case 72:
                                                                        break;
                                                                }
                                                            }
                                                            break;
                                                        case 84:
                                                    }
                                                }
                                            }
                                        } else {
                                            i41 = i39;
                                        }
                                    }
                                    catch (UserDefinedExceptionTest0032 exc14) {
                                        Test0032.instanceCount = (long)i37;
                                    }
                            }
                        }
                    }
                } else {
                    l %= (long)5;
                }
            }
        }
        catch (ArrayIndexOutOfBoundsException exc15) {
            strArr4[(Test0032.iFld >>> 1) % N][(i39 >>> 1) % N] += str;
        }
        vMeth_check_sum += str.length() + l + i2 + i3 + i4 + Float.floatToIntBits(f4) + s3 + i33 + i34 + i35 + i36 +
            i37 + l3 + i38 + i39 + Double.doubleToLongBits(d1) + i40 + i41 + FuzzerUtils.checkSum(strArr4) +
            FuzzerUtils.checkSum(O1) + FuzzerUtils.checkSum(O2) + FuzzerUtils.checkSum(O16) + FuzzerUtils.checkSum(O17)
            + FuzzerUtils.checkSum(O18) + FuzzerUtils.checkSum(O19);
    }

    public void mainTest0032(String[] strArr1) {

        long meth_res = 0;
        int i=-48187, i1=-12, i42=-62073, i43=252, i44=-98, i45=-13, i46=2, i47=-13, i48=-91, i49=-13, i50=174,
            i51=17982, i52=10831, i53=-163, i54=8, i55=-69, i56=7;
        float f=-18.870F, fArr1[]=new float[N], fArr2[][]=new float[N][N];
        boolean b=true, b1=true;
        long lArr[]=new long[N];
        char cArr[]=new char[N];
        Object OArr[]=new Object[64];
        byte byArr[]=new byte[N];
        Cls O=new Cls(), O20=new Cls(), O21=new Cls(), O22=new Cls(), O23=new Cls();

        FuzzerUtils.init(lArr, 14L);
        FuzzerUtils.init(cArr, (char)39139);
        FuzzerUtils.init(OArr, new Cls());
        FuzzerUtils.init(fArr1, -73.63F);
        FuzzerUtils.init(byArr, (byte)77);
        FuzzerUtils.init(fArr2, -2.564F);

        i *= (int)((lArr[(i >>> 1) % N] - (i + i)) * (f--));
        synchronized (O) {
            short s=16997;
            i = (int)Math.abs(f);
            Test0032.cFld = (char)(++i);
            switch ((((i % (s | 1)) >>> 1) % 4) + 100) {
                case 100:
                    Test0032.bArrFld[(i >>> 1) % N] = (Test0032.bArrFld[(-11 >>> 1) % N] = (b || (0.924F < (Cls.instanceCount -
                        f))));
                    i += (Test0032.iArrFld[(i >>> 1) % N]--);
                    i -= (int)((10973 - (2315 - (++Test0032.dArrFld[(i >>> 1) % N]))) + Cls.instanceCount);
                    Test0032.iArrFld[(i >>> 1) % N] -= Integer.reverseBytes((int)((-42 * (i ^ Cls.instanceCount)) - i));
                    vMeth(Test0032.strFld1, Test0032.instanceCount);
                    i42 = 115;
                    while (--i42 > 0) {
                        Cls.instanceCount >>>= (long)-8;
                        Test0032.iFld = (int)Test0032.cFld;
                    }
                    i43 = 105;
                    while (--i43 > 0) {
                        Test0032.iFld = (int)s;
                        for (i44 = (int) (i43); 1 < i44; i44--) {
                            Test0032.instanceCount -= (long)s;
                            for (i46 = (int) (1); 2 > i46; ++i46) {
                                switch ((i46 % 3) + 33) {
                                    case 33:
                                        f += (float)-3;
                                        cArr = FuzzerUtils.char1array(N, (char)34041);
                                        switch (((i42 >>> 1) % 1) + 56) {
                                            case 56:
                                                f += (float)Test0032.iFld;
                                                break;
                                            default:
                                                for (i48 = (int) (1); i48 < 2; i48++) {
                                                    O21 = O;
                                                    Test0032.bArrFld[i48] = false;
                                                    switch (((i48 % 10) * 5) + 123) {
                                                        case 145:
                                                            Test0032.lArrFld[i44 - 1] += (long)i48;
                                                            Test0032.dFld += (double)Test0032.cFld;
                                                            Test0032.dArrFld[i43] += Test0032.dFld;
                                                            break;
                                                        case 156:
                                                            Test0032.instanceCount <<= (long)i43;
                                                            Test0032.instanceCount -= (long)Test0032.byFld;
                                                            i45 = (int)Test0032.cFld;
                                                            Test0032.iArrFld[i43 + 1] *= (int)60L;
                                                            i50 = 1;
                                                            while ((i50 += 2) < 2) {
                                                                O22 = O21;
                                                                if (Test0032.bFld) break;
                                                                Test0032.byFld = (byte)-52617;
                                                                Test0032.bArrFld[i46 - 1] = b;
                                                                switch (((i49 >>> 1) % 2) + 9) {
                                                                    case 9:
                                                                        break;
                                                                    case 10:
                                                                        O21 = new Cls();
                                                                        Test0032.strFld = Test0032.strFld1;
                                                                        s -= (short)i48;
                                                                }
                                                            }
                                                            Cls.instanceCount >>= Cls.instanceCount;
                                                            switch (((i44 % 6) * 5) + 59) {
                                                                case 84:
                                                                    for (i51 = (int) (2); 1 < i51; --i51) {
                                                                        Test0032.iFld = (int)3391316534L;
                                                                        s = (short)i51;
                                                                        i49 -= (int)1.8866;
                                                                        Cls.instanceCount += -1L;
                                                                        Test0032.cFld *= (char)Test0032.iFld;
                                                                        f -= (float)i44;
                                                                        i45 = (int)Cls.instanceCount;
                                                                        switch (((i45 >>> 1) % 4) + 7) {
                                                                            case 7:
                                                                                i45 = i48;
                                                                                OArr[(i44 >>> 1) % 64] = O22;
                                                                                i47 += (int)s;
                                                                                i47 += (int)Cls.instanceCount;
                                                                                i49 = i1;
                                                                                break;
                                                                            case 8:
                                                                                i *= -6;
                                                                                Test0032.iArrFld[(i >>> 1) % N] /=
                                                                                    (int)(i52 | 1);
                                                                                break;
                                                                            case 9:
                                                                                i45 ^= -16;
                                                                                Test0032.dFld += (double)230;
                                                                                break;
                                                                            case 10:
                                                                                Test0032.cFld -= (char)f;
                                                                                switch ((((i49 >>> 1) % 5) * 5) + 98) {
                                                                                    case 115:
                                                                                        O23 = O20;
                                                                                        Test0032.iArrFld = Test0032.iArrFld;
                                                                                        switch (((i46 % 8) * 5) + 98) {
                                                                                            case 101:
                                                                                            case 128:
                                                                                                i49 *= (int)f;
                                                                                                fArr1[i44] *=
                                                                                                    (float)i50;
                                                                                                Test0032.sArrFld[i44 - 1]
                                                                                                    += (short)f;
                                                                                                f -= (float)i51;
                                                                                                i47 *= i47;
                                                                                                if (Test0032.bFld) break;
                                                                                                switch ((i51 * 5) +
                                                                                                    104) {
                                                                                                    case 170:
                                                                                                       
                                                                                                            Cls.instanceCount
                                                                                                            <<=
                                                                                                            Cls.instanceCount;
                                                                                                        O23 = O20;
                                                                                                        Test0032.strFld1 =
                                                                                                            strFld2;
                                                                                                        f -= (float)i53;
                                                                                                        i47 = i49;
                                                                                                        break;
                                                                                                    case 190:
                                                                                                        i45 *=
                                                                                                            (int)Test0032.cFld;
                                                                                                       
                                                                                                            Test0032.iArrFld[i51
                                                                                                            - 1] =
                                                                                                            (int)s;
                                                                                                        Test0032.strFld1 =
                                                                                                            strFld2;
                                                                                                    case 192:
                                                                                                        i52 = i1;
                                                                                                       
                                                                                                            Test0032.instanceCount
                                                                                                            +=
                                                                                                            (long)i51;
                                                                                                        i49 =
                                                                                                            (int)-20037L;
                                                                                                        lFld *=
                                                                                                            (long)-1.174F;
                                                                                                       
                                                                                                            Test0032.iArrFld[i48]
                                                                                                            -=
                                                                                                            (int)Test0032.dFld;
                                                                                                        break;
                                                                                                    case 370:
                                                                                                        lArr[i48] <<=
                                                                                                            (long)Test0032.byFld;
                                                                                                        break;
                                                                                                    case 107:
                                                                                                        lFld =
                                                                                                            (long)Test0032.byFld;
                                                                                                        break;
                                                                                                    case 293:
                                                                                                        break;
                                                                                                    case 398:
                                                                                                        break;
                                                                                                    case 223:
                                                                                                    case 424:
                                                                                                       
                                                                                                            Cls.instanceCount
                                                                                                            &=
                                                                                                            (long)213;
                                                                                                    case 306:
                                                                                                        byArr[i43] *=
                                                                                                            (byte)7;
                                                                                                        break;
                                                                                                    case 182:
                                                                                                    case 115:
                                                                                                       
                                                                                                            Test0032.bArrFld[i51
                                                                                                            - 1] =
                                                                                                            Test0032.bFld;
                                                                                                        break;
                                                                                                    case 298:
                                                                                                        strFld2 =
                                                                                                            strFld2;
                                                                                                        break;
                                                                                                    case 210:
                                                                                                       
                                                                                                            Test0032.iArrFld[i46]
                                                                                                            >>>=
                                                                                                            (int)lFld;
                                                                                                        break;
                                                                                                    case 240:
                                                                                                        Test0032.strFld =
                                                                                                            strFld2;
                                                                                                        break;
                                                                                                    case 127:
                                                                                                        f -= (float)8;
                                                                                                    case 454:
                                                                                                       
                                                                                                            Test0032.iArrFld[i48]
                                                                                                            = -1;
                                                                                                        break;
                                                                                                    case 114:
                                                                                                        Test0032.iFld = i46;
                                                                                                        break;
                                                                                                    case 117:
                                                                                                        break;
                                                                                                    case 381:
                                                                                                        i53 = i46;
                                                                                                        break;
                                                                                                    case 203:
                                                                                                        i47 *=
                                                                                                            (int)lFld;
                                                                                                        break;
                                                                                                    case 144:
                                                                                                        Test0032.dFld +=
                                                                                                            (double)-14L;
                                                                                                        break;
                                                                                                    case 271:
                                                                                                        i1 = Test0032.iFld;
                                                                                                        break;
                                                                                                    case 389:
                                                                                                        Test0032.iFld >>=
                                                                                                            i52;
                                                                                                        break;
                                                                                                    case 139:
                                                                                                        i52 =
                                                                                                            (int)Cls.instanceCount;
                                                                                                        break;
                                                                                                    case 279:
                                                                                                       
                                                                                                            Test0032.instanceCount
                                                                                                            =
                                                                                                            Test0032.instanceCount;
                                                                                                    case 434:
                                                                                                        break;
                                                                                                    case 351:
                                                                                                        i *= i51;
                                                                                                        break;
                                                                                                    case 411:
                                                                                                        i47 = i43;
                                                                                                        break;
                                                                                                    case 135:
                                                                                                        i += i50;
                                                                                                        break;
                                                                                                    case 111:
                                                                                                        if (b1) break;
                                                                                                    case 397:
                                                                                                        Test0032.byFld -=
                                                                                                            (byte)i55;
                                                                                                        break;
                                                                                                    case 136:
                                                                                                       
                                                                                                            Cls.instanceCount
                                                                                                            <<=
                                                                                                            (long)i49;
                                                                                                    case 418:
                                                                                                       
                                                                                                            Test0032.iArrFld[i44
                                                                                                            - 1] -=
                                                                                                            (int)Cls.instanceCount;
                                                                                                        break;
                                                                                                    case 193:
                                                                                                        Test0032.cFld *=
                                                                                                            (char)Test0032.byFld;
                                                                                                        break;
                                                                                                    case 330:
                                                                                                        Test0032.iFld -=
                                                                                                            (int)Test0032.dFld;
                                                                                                        break;
                                                                                                    case 105:
                                                                                                        if (b1) break;
                                                                                                        break;
                                                                                                    case 429:
                                                                                                        lFld ^=
                                                                                                            Cls.instanceCount;
                                                                                                        break;
                                                                                                    case 407:
                                                                                                        i53 <<= i51;
                                                                                                        break;
                                                                                                    case 338:
                                                                                                        i55 *= -79;
                                                                                                        break;
                                                                                                    case 146:
                                                                                                        i1 += i52;
                                                                                                        break;
                                                                                                    case 264:
                                                                                                        // Resetting
                                                                                                        // String
                                                                                                        // variable to
                                                                                                        // a short
                                                                                                        // value to
                                                                                                        // prevent OOM
                                                                                                        strFld2 = "";
                                                                                                        strFld2 +=
                                                                                                            "two";
                                                                                                        break;
                                                                                                    case 109:
                                                                                                        Test0032.dFld -=
                                                                                                            (double)Cls.instanceCount;
                                                                                                        break;
                                                                                                    case 387:
                                                                                                        i54 = 193;
                                                                                                        break;
                                                                                                    case 327:
                                                                                                       
                                                                                                            Test0032.iArrFld[i46
                                                                                                            + 1] += i53;
                                                                                                        break;
                                                                                                    case 393:
                                                                                                        i54 <<=
                                                                                                            (int)lFld;
                                                                                                        break;
                                                                                                    case 224:
                                                                                                        i54 = (int)f;
                                                                                                        break;
                                                                                                    case 152:
                                                                                                    case 321:
                                                                                                        // Resetting
                                                                                                        // String
                                                                                                        // variable to
                                                                                                        // a short
                                                                                                        // value to
                                                                                                        // prevent OOM
                                                                                                        strFld2 = "";
                                                                                                        strFld2 +=
                                                                                                            strFld2;
                                                                                                    case 375:
                                                                                                        f =
                                                                                                            (float)Test0032.instanceCount;
                                                                                                        break;
                                                                                                    case 147:
                                                                                                        Test0032.iFld =
                                                                                                            (int)Test0032.instanceCount;
                                                                                                        break;
                                                                                                    case 312:
                                                                                                       
                                                                                                            Test0032.iArrFld[i46]
                                                                                                            <<= i49;
                                                                                                        break;
                                                                                                    case 445:
                                                                                                       
                                                                                                            Test0032.iArrFld[i48
                                                                                                            - 1] =
                                                                                                            (int)f;
                                                                                                        break;
                                                                                                    case 186:
                                                                                                    case 156:
                                                                                                        i56 -= i43;
                                                                                                        break;
                                                                                                    case 289:
                                                                                                        i = (int)s;
                                                                                                    case 262:
                                                                                                        i47 -= i44;
                                                                                                    case 450:
                                                                                                        i54 =
                                                                                                            (int)3267110273L;
                                                                                                    case 265:
                                                                                                        i = i47;
                                                                                                        break;
                                                                                                    case 385:
                                                                                                        Test0032.strFld1 =
                                                                                                            Test0032.strFld;
                                                                                                        break;
                                                                                                    case 180:
                                                                                                        break;
                                                                                                    case 179:
                                                                                                        lFld +=
                                                                                                            (long)i53;
                                                                                                        break;
                                                                                                    case 140:
                                                                                                    case 261:
                                                                                                        O22 = O20;
                                                                                                        break;
                                                                                                    case 308:
                                                                                                        if (true)
                                                                                                            continue;
                                                                                                        break;
                                                                                                    case 227:
                                                                                                       
                                                                                                            Test0032.iArrFld[i43]
                                                                                                            >>= i44;
                                                                                                        break;
                                                                                                    case 444:
                                                                                                        i54 = i55;
                                                                                                        break;
                                                                                                    case 384:
                                                                                                        fArr2 = fArr2;
                                                                                                        break;
                                                                                                    case 275:
                                                                                                    case 243:
                                                                                                        i1 = iFld1;
                                                                                                        break;
                                                                                                }
                                                                                                break;
                                                                                            case 124:
                                                                                                i54 *= i47;
                                                                                                break;
                                                                                            case 131:
                                                                                                break;
                                                                                            case 112:
                                                                                                break;
                                                                                            case 108:
                                                                                                f -= (float)i1;
                                                                                            case 132:
                                                                                                Test0032.iArrFld[i48 + 1]
                                                                                                    -= (int)s;
                                                                                            case 120:
                                                                                                Test0032.iFld += i46;
                                                                                                break;
                                                                                        }
                                                                                        break;
                                                                                    case 107:
                                                                                        Cls.instanceCount -= (long)i50;
                                                                                        break;
                                                                                    case 102:
                                                                                        Test0032.dFld -= (double)f;
                                                                                        break;
                                                                                    case 118:
                                                                                        f -= (float)-1896226308L;
                                                                                        break;
                                                                                    case 117:
                                                                                        i = i49;
                                                                                        break;
                                                                                }
                                                                                break;
                                                                            default:
                                                                                Test0032.iFld = (int)12L;
                                                                        }
                                                                    }
                                                                    break;
                                                                case 87:
                                                                    Test0032.iArrFld[i48 + 1] |= i56;
                                                                    break;
                                                                case 81:
                                                                    Cls.instanceCount >>>= Cls.instanceCount;
                                                                    break;
                                                                case 82:
                                                                    break;
                                                                case 86:
                                                                case 72:
                                                                    i56 += i44;
                                                                    break;
                                                            }
                                                            break;
                                                        case 163:
                                                            // Resetting String variable to a short value to prevent OOM
                                                            Test0032.strFld = "hhhh";
                                                            Test0032.strFld += strFld2;
                                                            break;
                                                        case 124:
                                                            i54 += -13144;
                                                            break;
                                                        case 155:
                                                            i56 >>>= (int)lFld;
                                                            break;
                                                        case 165:
                                                            O20 = O21;
                                                        case 170:
                                                            break;
                                                        case 152:
                                                            Test0032.iArrFld = Test0032.iArrFld;
                                                            break;
                                                        case 127:
                                                            Test0032.iArrFld[i46 + 1] = i46;
                                                            break;
                                                        case 131:
                                                            break;
                                                        default:
                                                    }
                                                }
                                        }
                                        break;
                                    case 34:
                                        Test0032.instanceCount >>= (long)Test0032.iFld;
                                    case 35:
                                        Test0032.instanceCount -= (long)i56;
                                        break;
                                }
                            }
                        }
                    }
                case 101:
                    Test0032.iArrFld = FuzzerUtils.int1array(N, (int)-9);
                case 102:
                    i53 = (int)Cls.instanceCount;
                    break;
                case 103:
                    // Resetting String variable to a short value to prevent OOM
                    Test0032.strFld = "";
                    Test0032.strFld += Test0032.strFld;
                    break;
            }
        }

        FuzzerUtils.out.println("i f i1 = " + i + "," + Float.floatToIntBits(f) + "," + i1);
        FuzzerUtils.out.println("b i42 i43 = " + (b ? 1 : 0) + "," + i42 + "," + i43);
        FuzzerUtils.out.println("i44 i45 i46 = " + i44 + "," + i45 + "," + i46);
        FuzzerUtils.out.println("i47 i48 i49 = " + i47 + "," + i48 + "," + i49);
        FuzzerUtils.out.println("i50 i51 i52 = " + i50 + "," + i51 + "," + i52);
        FuzzerUtils.out.println("i53 i54 b1 = " + i53 + "," + i54 + "," + (b1 ? 1 : 0));
        FuzzerUtils.out.println("i55 i56 lArr = " + i55 + "," + i56 + "," + FuzzerUtils.checkSum(lArr));
        FuzzerUtils.out.println("cArr OArr fArr1 = " + FuzzerUtils.checkSum(cArr) + "," + FuzzerUtils.checkSum(OArr) +
            "," + Double.doubleToLongBits(FuzzerUtils.checkSum(fArr1)));
        FuzzerUtils.out.println("byArr fArr2 O = " + FuzzerUtils.checkSum(byArr) + "," +
            Double.doubleToLongBits(FuzzerUtils.checkSum(fArr2)) + "," + FuzzerUtils.checkSum(O));
        FuzzerUtils.out.println("O20 O21 O22 = " + FuzzerUtils.checkSum(O20) + "," + FuzzerUtils.checkSum(O21) + "," +
            FuzzerUtils.checkSum(O22));
        FuzzerUtils.out.println("O23 Cls = " + FuzzerUtils.checkSum(O23) + "," + Cls.instanceCount);

        FuzzerUtils.out.println("Test0032.instanceCount Test0032.cFld Test0032.dFld = " + Test0032.instanceCount + "," + (int)Test0032.cFld
            + "," + Double.doubleToLongBits(Test0032.dFld));
        FuzzerUtils.out.println("Test0032.bFld Test0032.byFld Test0032.strFld = " + (Test0032.bFld ? 1 : 0) + "," + Test0032.byFld + "," +
            Test0032.strFld.length());
        FuzzerUtils.out.println("Test0032.strFld1 Test0032.iFld strFld2 = " + Test0032.strFld1.length() + "," + Test0032.iFld + "," +
            strFld2.length());
        FuzzerUtils.out.println("lFld iFld1 Test0032.bArrFld = " + lFld + "," + iFld1 + "," +
            FuzzerUtils.checkSum(Test0032.bArrFld));
        FuzzerUtils.out.println("Test0032.iArrFld Test0032.dArrFld Test0032.lArrFld = " + FuzzerUtils.checkSum(Test0032.iArrFld) + ","
            + Double.doubleToLongBits(FuzzerUtils.checkSum(Test0032.dArrFld)) + "," + FuzzerUtils.checkSum(Test0032.lArrFld));
        FuzzerUtils.out.println("Test0032.sArrFld Cls = " + FuzzerUtils.checkSum(Test0032.sArrFld) + "," + Cls.instanceCount);

        FuzzerUtils.out.println("vMeth2_check_sum: " + vMeth2_check_sum);
        FuzzerUtils.out.println("vMeth1_check_sum: " + vMeth1_check_sum);
        FuzzerUtils.out.println("vMeth_check_sum: " + vMeth_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test0032 _instance = new Test0032();
            for (int i = 0; i < 10; i++ ) {
                try {
                    _instance.mainTest0032(strArr);
                 } catch (OutOfMemoryError ex) {
                    ex.printStackTrace(FuzzerUtils.err);
                    System.exit(1);
                 } catch (Exception ex) {
                    FuzzerUtils.out.println(ex.getClass().getCanonicalName());
                 }
             }
         } catch (Exception ex) {
            FuzzerUtils.out.println(ex.getClass().getCanonicalName());
         }
    }
}
///////////////////////////////////////////////////////////////////////
class Cls {

    public static final int N = 128;

    public static long instanceCount=-142L;

}
///////////////////////////////////////////////////////////////////////
class UserDefinedExceptionTest0032 extends RuntimeException {
    public int field;
    public UserDefinedExceptionTest0032() { super("UserDefinedExceptionTest0032"); }
    public UserDefinedExceptionTest0032(String mess) { super(mess); }
}

//DEBUG  Test0032 ->  Test0032
//DEBUG  main ->  main
//DEBUG  mainTest0032 ->  mainTest0032
//DEBUG  Cls ->  Cls vMeth mainTest0032 vMeth2 vMeth1
//DEBUG  vMeth ->  vMeth mainTest0032
//DEBUG  vMeth1 ->  vMeth1 vMeth mainTest0032
//DEBUG  vMeth2 ->  vMeth2 vMeth1 vMeth mainTest0032
//DEBUG  Depth = 4
//DEBUG  Classes = 2
//DEBUG  static objects = {}
