// Generated by Java* Fuzzer test generator (1.0.001). Sun Mar 29 19:44:21 2026
public class Test0056 {

    public static final int N = 128;

    public static long instanceCount=64299L;
    public int iFld=86;
    public int iFld2=-23996;
    public int iFld3=31472;
    public static volatile long lArrFld[]=new long[N];
    public static byte byArrFld[]=new byte[N];

    static {
        FuzzerUtils.init(Test0056.lArrFld, 2670741074L);
        FuzzerUtils.init(Test0056.byArrFld, (byte)-105);
    }

    public static long vMeth_check_sum = 0;
    public static long iMeth_check_sum = 0;

    public static int iMeth() {

        long meth_res = 0;
        int i2=7, i3=-2, i4=-108, i5=181, i17=121, i18=-7, i19=-15465, i20=9983, i21=4, iArr1[]=new int[N];
        long l=182L;
        float f2=-83.873F, fArr1[]=new float[N];
        byte by1=35;
        double d1=-1.60775;
        String str="one", str1="three";
        Object OArr[]=new Object[63];
        Cls O=new Cls();
        Cls1 O1=new Cls1();
        Cls2 O7=new Cls2(), O8=new Cls2(), O9=new Cls2();

        FuzzerUtils.init(iArr1, 58191);
        FuzzerUtils.init(OArr, new Cls2());
        FuzzerUtils.init(fArr1, 1.272F);

        for (i2 = (int) (3); i2 < 118; ++i2) {
            O = (O = (O = (O = O)));
            for (i4 = (int) (14); i4 > 1; --i4) {
                Cls1.instanceCount = (long)((i3 - (-iArr1[i4])) * Math.min(i4, i2));
                l = 2;
                while (--l > 0) {
                    long l1=8750063071268351656L;
                    OArr[(i3 >>> 1) % 63] = O1;
                    Cls.iMeth1();
                    f2 *= f2;
                    Cls.iFld1 -= (int)f2;
                    Cls.iFld1 += (int)f2;
                    switch ((int)((l % 5) + 51)) {
                        case 51:
                            iArr1[i2] = (int)by1;
                            i3 *= Cls.iFld1;
                            switch (((i4 >>> 1) % 9) + 7) {
                                case 7:
                                case 8:
                                    for (d1 = (double) (1); d1 > 1; d1 -= 2) {
                                        Cls.strFld = str;
                                        O7 = O7;
                                        Test0056.instanceCount = (long)-73;
                                        Cls.cFld = (char)by1;
                                        f2 = f2;
                                        i5 >>= 45202;
                                        Cls.cFld *= (char)Test0056.instanceCount;
                                    }
                                    // Resetting String variable to a short value to prevent OOM
                                    Cls.strFld = "";
                                    Cls.strFld += str;
                                    l1 <<= (long)113;
                                    f2 += (float)7;
                                    if (false) {
                                        f2 *= (float)-3017L;
                                        // Resetting String variable to a short value to prevent OOM
                                        str = "hhhh";
                                        str += str;
                                    }
                                    if (Cls.bFld) continue;
                                    break;
                                case 9:
                                    f2 = f2;
                                    try {
                                        switch ((((i2 >>> 1) % 7) * 5) + 91) {
                                            case 116:
                                                for (i18 = (int) (1); i18 < 1; ++i18) {
                                                    i17 = i5;
                                                    Cls.strFld = str1;
                                                    switch ((i2 % 9) + 123) {
                                                        case 123:
                                                            iArr1[i4] = i2;
                                                            Cls.iFld1 >>= i5;
                                                            f2 *= (float)0;
                                                            switch (((i4 % 6) * 5) + 80) {
                                                                case 105:
                                                                    i5 = (int)-2.316F;
                                                                    for (i20 = (int) (1); 1 < i20; i20 -= 3) {
                                                                        Cls.cFld = (char)-6695572248474424934L;
                                                                        i21 /= (int)(i21 | 1);
                                                                        if (true) break;
                                                                    }
                                                                    break;
                                                                case 97:
                                                                    f2 = (float)i3;
                                                                    break;
                                                                case 92:
                                                                    i3 = (int)d1;
                                                                case 101:
                                                                    i5 = Cls.iFld1;
                                                                    break;
                                                                case 81:
                                                                    Cls.dFld = (double)Cls1.instanceCount;
                                                                case 100:
                                                                    // Resetting String variable to a short value to
                                                                    // prevent OOM
                                                                    Cls.strFld = "";
                                                                    Cls.strFld += "one";
                                                            }
                                                            break;
                                                        case 124:
                                                            iArr1[i4 + 1] = -60155;
                                                        case 125:
                                                            Cls.iFld1 = i17;
                                                            break;
                                                        case 126:
                                                            break;
                                                        case 127:
                                                            break;
                                                        case 128:
                                                            break;
                                                        case 129:
                                                            // Resetting String variable to a short value to prevent OOM
                                                            str1 = "hhhh";
                                                            str1 += Cls.strFld;
                                                        case 130:
                                                            fArr1[(int)(l)] -= (float)-2273145348L;
                                                            break;
                                                        case 131:
                                                            f2 = (float)Cls.cFld;
                                                    }
                                                }
                                                break;
                                            case 108:
                                                fArr1[i2] += (float)Cls.instanceCount;
                                                break;
                                            case 121:
                                                Cls.dFld += (double)i5;
                                                break;
                                            case 124:
                                                by1 &= (byte)Cls2.instanceCount;
                                                break;
                                            case 122:
                                                by1 <<= (byte)Cls.iFld1;
                                                break;
                                            case 125:
                                                i21 *= (int)181L;
                                                break;
                                            case 113:
                                                if (Cls.bFld) continue;
                                                break;
                                        }
                                    }
                                    catch (NegativeArraySizeException exc8) {
                                        Cls.dFld *= (double)Cls2.instanceCount;
                                    }
                                    break;
                                case 10:
                                    f2 += (float)l;
                                    break;
                                case 11:
                                    Test0056.instanceCount ^= (long)i20;
                                    break;
                                case 12:
                                    iArr1[i4] *= (int)Cls.dFld;
                                    break;
                                case 13:
                                    break;
                                case 14:
                                    break;
                                case 15:
                                    try {
                                        i17 = (-734092023 / i19);
                                        Cls.iFld1 = (iArr1[i4] % i5);
                                        i19 = (Cls.iFld1 / -44);
                                    } catch (ArithmeticException a_e) {}
                                    break;
                            }
                            break;
                        case 52:
                            l1 = (long)by1;
                        case 53:
                            i21 -= (int)by1;
                            break;
                        case 54:
                            Cls.iFld1 = -25190;
                        case 55:
                            iArr1[i2] = -245;
                            break;
                        default:
                            Cls.iFld1 *= i19;
                    }
                }
            }
        }
        meth_res = i2 + i3 + i4 + i5 + l + Float.floatToIntBits(f2) + by1 + Double.doubleToLongBits(d1) + i17 +
            str.length() + i18 + i19 + str1.length() + i20 + i21 + FuzzerUtils.checkSum(iArr1) +
            FuzzerUtils.checkSum(OArr) + Double.doubleToLongBits(FuzzerUtils.checkSum(fArr1)) + FuzzerUtils.checkSum(O)
            + FuzzerUtils.checkSum(O1) + FuzzerUtils.checkSum(O7) + FuzzerUtils.checkSum(O8) + FuzzerUtils.checkSum(O9);
        iMeth_check_sum += meth_res;
        return (int)meth_res;
    }

    public static void vMeth(char c) {

        long meth_res = 0;
        int i1=139, i22=-3, i23=44, i24=173, i25=-7563, i26=-9240, i27=42361, i28=-62422, i29=94, i30=15, i31=15585,
            i32=-7, i33=248, i34=-173, i35=-3, iArr4[]=new int[N];
        long l2=-323856456L;
        float f3=1.435F;
        byte by2=-46;
        double d2=-1.21059, d3=-75.69469;
        boolean bArr[]=new boolean[N];
        Cls2 O10=new Cls2(), O11=new Cls2(), O12=new Cls2(), O13=new Cls2(), O14=new Cls2(), O15=new Cls2();

        FuzzerUtils.init(iArr4, 1);
        FuzzerUtils.init(bArr, true);

        Test0056.lArrFld[(i1 >>> 1) % N] -= (long)iMeth();
        switch ((((i1 >>> 1) % 2) * 5) + 43) {
            case 46:
                Cls1.instanceCount *= (long)Cls.iFld1;
                for (i22 = (int) (93); 2 < i22; i22 -= 3) {
                    Cls1.instanceCount = (long)i1;
                    synchronized (O11) {
                        l2 = 51;
                        while (--l2 > 0) {
                            for (i25 = (int) (1); i25 > 1; i25 -= 2) {
                                i27 = 1;
                                do {
                                    Cls.dFld = (double)f3;
                                    i1 += (int)by2;
                                    Cls.dFld = (double)86.174F;
                                    i28 = 1;
                                    while (++i28 < 1) {
                                        Cls2.instanceCount |= (long)i24;
                                        f3 += (float)i27;
                                        i26 += i1;
                                        iArr4 = FuzzerUtils.int1array(N, (int)-9);
                                        Cls.dFld = (double)-77.1000F;
                                    }
                                    for (i29 = (int) (1); i29 < 1; i29++) {
                                        Cls.iFld1 = i30;
                                        i23 = (int)Cls.dFld;
                                    }
                                    Test0056.instanceCount = (long)i26;
                                } while (--i27 > 0);
                                i30 -= i27;
                                Cls.cFld *= (char)Cls2.instanceCount;
                                i31 = 1;
                                while (++i31 < 1) {
                                    i30 >>>= Cls.iFld1;
                                    i1 = (int)d2;
                                }
                            }
                            Cls1.instanceCount -= (long)Cls.dFld;
                            f3 += (float)Test0056.instanceCount;
                            bArr[i22] = false;
                            i26 *= i29;
                            Cls1.instanceCount ^= (long)-4;
                            i24 -= (int)Cls.dFld;
                        }
                        Test0056.byArrFld = Test0056.byArrFld;
                        // Resetting String variable to a short value to prevent OOM
                        Cls.strFld = "";
                        Cls.strFld += Cls.strFld;
                    }
                    d3 = 51;
                    while (--d3 > 0) {
                        for (i32 = (int) (1); 1 < i32; i32--) {
                            if (true) {
                                Test0056.lArrFld[i32] = (long)i29;
                                Cls.iFld1 = i32;
                                // Resetting String variable to a short value to prevent OOM
                                Cls.strFld = "";
                                Cls.strFld += Cls.strFld;
                                Cls1.instanceCount -= (long)i22;
                                if (Cls.bFld) continue;
                            } else if (false) {
                                Test0056.instanceCount += (long)i27;
                                for (i34 = (int) (1); i34 > i32; i34 -= 3) {
                                    i35 >>= Cls.iFld1;
                                    i26 = (int)Cls.instanceCount;
                                }
                            } else if (Cls.bFld) {
                            }
                        }
                    }
                }
                break;
            case 47:
                Cls.sFld = (short)by2;
                break;
        }
        vMeth_check_sum += (int)c + i1 + i22 + i23 + i24 + l2 + i25 + i26 + i27 + Float.floatToIntBits(f3) + by2 + i28
            + i29 + i30 + i31 + Double.doubleToLongBits(d2) + Double.doubleToLongBits(d3) + i32 + i33 + i34 + i35 +
            FuzzerUtils.checkSum(iArr4) + FuzzerUtils.checkSum(bArr) + FuzzerUtils.checkSum(O10) +
            FuzzerUtils.checkSum(O11) + FuzzerUtils.checkSum(O12) + FuzzerUtils.checkSum(O13) +
            FuzzerUtils.checkSum(O14) + FuzzerUtils.checkSum(O15);
    }

    public void mainTest0056(String[] strArr1) {

        long meth_res = 0;
        int i=40231, i36=-13, i37=-19413, i38=-38582, i39=130, i40=-89, i41=10, i42=-31543, i43=10, i44=-112, i45=-6,
            i46=12, i47=-175, i48=-24952, i49=-49101, i50=-6, i51=13207, i52=8, i53=24826, i54=8, i55=6, i56=0,
            i57=-9490, i58=-6, i59=3, i60=11, iArr[][]=new int[N][N];
        float f=43.464F, f4=1.975F, fArr2[]=new float[N];
        byte by3=-101;
        long l3=6077L, l4=2470993531L;
        String strArr3[]=new String[N];
        double dArr1[]=new double[N];
        Object OArr2[]=new Object[92];
        Cls2 O16=new Cls2(), O17=new Cls2(), O18=new Cls2(), O19=new Cls2(), O20=new Cls2(), O21=new Cls2(), O22=new
            Cls2(), O23=new Cls2(), O24=new Cls2(), O25=new Cls2(), O26=new Cls2(), O27=new Cls2();

        FuzzerUtils.init(iArr, -1);
        FuzzerUtils.init(strArr3, "four");
        FuzzerUtils.init(fArr2, -1.741F);
        FuzzerUtils.init(dArr1, 0.38130);
        FuzzerUtils.init(OArr2, new Cls2());

        iArr[(i >>> 1) % N][(iFld >>> 1) % N] <<= (int)((long)((++f) - (Test0056.instanceCount * iFld)) << ((iFld - i) |
            (--i)));
        vMeth((char)(Cls.cFld));
        switch (((Cls.iFld1 >>> 1) % 5) + 67) {
            case 67:
                for (i36 = (int) (106); i36 > 4; i36 -= 2) {
                    synchronized (O17) {
                        for (i39 = (int) (6); i39 < 111; i39 += 3) {
                            strArr3[i39 + 1] = Cls.strFld;
                            i <<= i37;
                            Cls.iFld1 = i38;
                        }
                        for (i41 = (int) (i36); 1 < i41; i41 -= 3) {
                            i38 *= i36;
                        }
                        synchronized (O20) {
                            for (i44 = (int) (114); i44 > i36; i44--) {
                                iArr[i36][i36 - 1] = i46;
                                Cls.instanceCount = Cls.instanceCount;
                            }
                        }
                        switch (((i36 >>> 1) % 2) + 74) {
                            case 74:
                                fArr2 = fArr2;
                                Cls.instanceCount += (long)i37;
                                i47 = 108;
                                do {
                                    if (Cls.bFld) continue;
                                    iArr[i47][i47 - 1] <<= (int)Cls1.instanceCount;
                                    for (i48 = (int) (1); i48 < 5; i48++) {
                                        for (i50 = (int) (2); 1 < i50; --i50) {
                                            if (Cls.bFld) break;
                                        }
                                        f = (float)Cls.cFld;
                                        iArr[i36][i48] = (int)0.133F;
                                    }
                                    if (true) {
                                        i51 >>>= -5;
                                        f -= (float)-2.112178;
                                        Cls2.instanceCount = (long)f;
                                        i42 = (int)Cls2.instanceCount;
                                        i52 = 5;
                                        do {
                                            synchronized (O24) {
                                                for (i54 = (int) (1); i54 < 1; i54++) {
                                                    dArr1[i47 + 1] += (double)13;
                                                    dArr1[i47 + 1] = (double)iFld2;
                                                    Cls.bFld = Cls.bFld;
                                                    f = (float)i51;
                                                    Cls.strFld = Cls.strFld;
                                                    i38 >>= -3;
                                                    i += iFld;
                                                }
                                                i56 = 1;
                                                while ((i56 -= 2) > 0) {
                                                    i53 = 9;
                                                    Cls.bFld = true;
                                                    for (l3 = (long) (1); 1 < l3; l3--) {
                                                        Cls.cFld *= (char)Cls1.instanceCount;
                                                        // Resetting String variable to a short value to prevent OOM
                                                        Cls.strFld = "";
                                                        Cls.strFld += "four";
                                                        Cls.sFld += (short)i36;
                                                    }
                                                    i51 = 165;
                                                }
                                                i49 <<= (int)Test0056.instanceCount;
                                                Cls.instanceCount = (long)-9;
                                                if (Cls.bFld) continue;
                                            }
                                            i58 = 1;
                                            do {
                                                by3 += (byte)i55;
                                                iFld3 += iFld3;
                                                if (Cls.bFld) break;
                                                Test0056.instanceCount *= (long)i51;
                                                i53 = iFld;
                                                switch (((i36 % 8) * 5) + 96) {
                                                    case 116:
                                                        for (i59 = (int) (1); i52 < i59; i59 -= 3) {
                                                            strArr3[i58] += Cls.strFld;
                                                            Cls.strFld = Cls.strFld;
                                                            Cls.cFld ^= (char)i47;
                                                            Cls.instanceCount += (long)i46;
                                                            Cls1.instanceCount = (long)iFld;
                                                            i42 *= (int)1.118F;
                                                        }
                                                        f4 = 1;
                                                        while (++f4 < 1) {
                                                            Cls1.instanceCount = Cls.instanceCount;
                                                            f -= (float)i56;
                                                            iFld = (int)f;
                                                            iArr[(int)(f4 + 1)][i36] &= i47;
                                                            i60 = i36;
                                                            i53 *= -74;
                                                            switch ((i52 % 10) + 1) {
                                                                case 1:
                                                                    i49 = (int)Test0056.instanceCount;
                                                                    if (Cls.bFld) continue;
                                                                    Test0056.lArrFld = Test0056.lArrFld;
                                                                    if (true) continue;
                                                                    if (Cls.bFld) continue;
                                                                    switch ((i58 % 8) + 29) {
                                                                        case 29:
                                                                            iFld2 -= iFld;
                                                                            iFld3 *= i46;
                                                                            i51 >>>= 3;
                                                                            switch ((i47 % 5) + 32) {
                                                                                case 32:
                                                                                    if (Cls.bFld) continue;
                                                                                    strArr3[i36 - 1] = Cls.strFld;
                                                                                    Cls.sFld *= (short)-44308L;
                                                                                    switch (((i52 % 10) * 5) + 23) {
                                                                                        case 50:
                                                                                            switch ((i52 % 5) + 18) {
                                                                                                case 18:
                                                                                                    Cls.bFld = Cls.bFld;
                                                                                                    i40 = i54;
                                                                                                    Cls2.instanceCount
                                                                                                        ^=
                                                                                                        (long)Cls.sFld;
                                                                                                    break;
                                                                                                case 19:
                                                                                                    f = (float)Cls.sFld;
                                                                                                    break;
                                                                                                case 20:
                                                                                                    f *= (float)i40;
                                                                                                    break;
                                                                                                case 21:
                                                                                                    by3 >>= (byte)i47;
                                                                                                case 22:
                                                                                                    i38 +=
                                                                                                        (int)Cls.cFld;
                                                                                                    break;
                                                                                                default:
                                                                                                    Cls.cFld +=
                                                                                                        (char)Cls.instanceCount;
                                                                                            }
                                                                                            break;
                                                                                        case 30:
                                                                                        case 33:
                                                                                            // Resetting String
                                                                                            // variable to a short
                                                                                            // value to prevent OOM
                                                                                            Cls.strFld = "hhhh";
                                                                                            Cls.strFld += Cls.strFld;
                                                                                            break;
                                                                                        case 29:
                                                                                            i46 = i60;
                                                                                            break;
                                                                                        case 48:
                                                                                            iArr[(int)(f4)][i47 + 1]
                                                                                                <<= (int)13L;
                                                                                            break;
                                                                                        case 44:
                                                                                            Cls.bFld = Cls.bFld;
                                                                                            break;
                                                                                        case 66:
                                                                                            // Resetting String
                                                                                            // variable to a short
                                                                                            // value to prevent OOM
                                                                                            Cls.strFld = "";
                                                                                            Cls.strFld += Cls.strFld;
                                                                                        case 39:
                                                                                            f = (float)i58;
                                                                                            break;
                                                                                        case 31:
                                                                                            if (Cls.bFld) continue;
                                                                                            break;
                                                                                        case 32:
                                                                                        default:
                                                                                            // Resetting String
                                                                                            // variable to a short
                                                                                            // value to prevent OOM
                                                                                            Cls.strFld = "";
                                                                                            Cls.strFld += Cls.strFld;
                                                                                    }
                                                                                    break;
                                                                                case 33:
                                                                                    i45 = i49;
                                                                                case 34:
                                                                                    i55 = i43;
                                                                                    break;
                                                                                case 35:
                                                                                    Test0056.instanceCount = (long)-36039;
                                                                                    break;
                                                                                case 36:
                                                                                    Cls.strFld = Cls.strFld;
                                                                                default:
                                                                                    Cls2.instanceCount *= (long)f;
                                                                            }
                                                                            break;
                                                                        case 30:
                                                                            Test0056.lArrFld[i52 + 1] -= (long)f4;
                                                                            break;
                                                                        case 31:
                                                                            i38 = (int)f;
                                                                            break;
                                                                        case 32:
                                                                            Cls.strFld = Cls.strFld;
                                                                        case 33:
                                                                            i51 = i57;
                                                                            break;
                                                                        case 34:
                                                                        case 35:
                                                                            Cls.dFld = Cls.dFld;
                                                                            break;
                                                                        case 36:
                                                                        default:
                                                                            // Resetting String variable to a short
                                                                            // value to prevent OOM
                                                                            Cls.strFld = "";
                                                                            Cls.strFld += Cls.strFld;
                                                                    }
                                                                    break;
                                                                case 2:
                                                                    f -= (float)l3;
                                                                    break;
                                                                case 3:
                                                                    i49 = 94;
                                                                    break;
                                                                case 4:
                                                                case 5:
                                                                    Cls.cFld *= (char)i46;
                                                                    break;
                                                                case 6:
                                                                    Test0056.instanceCount *= Cls.instanceCount;
                                                                    break;
                                                                case 7:
                                                                    iArr[i58 + 1][i58] += (int)Cls.sFld;
                                                                case 8:
                                                                    i45 -= i58;
                                                                    break;
                                                                case 9:
                                                                    iFld3 ^= (int)Cls2.instanceCount;
                                                                case 10:
                                                                    Cls.strFld = Cls.strFld;
                                                                    break;
                                                                default:
                                                                    f -= (float)i58;
                                                            }
                                                        }
                                                        break;
                                                    case 136:
                                                        Test0056.instanceCount = (long)Cls.dFld;
                                                        break;
                                                    case 119:
                                                        i40 *= i51;
                                                        break;
                                                    case 127:
                                                        iArr[i36 - 1] = FuzzerUtils.int1array(N, (int)-252);
                                                        break;
                                                    case 99:
                                                        break;
                                                    case 130:
                                                        OArr2[(i57 >>> 1) % 92] = O24;
                                                        break;
                                                    case 132:
                                                        i57 &= i40;
                                                        break;
                                                    case 98:
                                                        // Resetting String variable to a short value to prevent OOM
                                                        Cls.strFld = "";
                                                        Cls.strFld += Cls.strFld;
                                                        break;
                                                    default:
                                                        i45 = (int)by3;
                                                }
                                            } while (++i58 < 1);
                                        } while (--i52 > 0);
                                    } else if (Cls.bFld) {
                                        i60 <<= (int)Cls2.instanceCount;
                                    }
                                } while (--i47 > 0);
                                break;
                            case 75:
                                break;
                            default:
                                l4 = (long)52335;
                        }
                    }
                }
            case 68:
                i40 <<= (int)Cls.sFld;
            case 69:
                iFld2 <<= i53;
                break;
            case 70:
                iFld3 += i46;
                break;
            case 71:
            default:
                Cls.strFld = Cls.strFld;
        }

        FuzzerUtils.out.println("i f i36 = " + i + "," + Float.floatToIntBits(f) + "," + i36);
        FuzzerUtils.out.println("i37 i38 i39 = " + i37 + "," + i38 + "," + i39);
        FuzzerUtils.out.println("i40 by3 i41 = " + i40 + "," + by3 + "," + i41);
        FuzzerUtils.out.println("i42 i43 i44 = " + i42 + "," + i43 + "," + i44);
        FuzzerUtils.out.println("i45 i46 i47 = " + i45 + "," + i46 + "," + i47);
        FuzzerUtils.out.println("i48 i49 i50 = " + i48 + "," + i49 + "," + i50);
        FuzzerUtils.out.println("i51 i52 i53 = " + i51 + "," + i52 + "," + i53);
        FuzzerUtils.out.println("i54 i55 i56 = " + i54 + "," + i55 + "," + i56);
        FuzzerUtils.out.println("l3 i57 i58 = " + l3 + "," + i57 + "," + i58);
        FuzzerUtils.out.println("i59 i60 f4 = " + i59 + "," + i60 + "," + Float.floatToIntBits(f4));
        FuzzerUtils.out.println("l4 iArr strArr3 = " + l4 + "," + FuzzerUtils.checkSum(iArr) + "," +
            FuzzerUtils.checkSum(strArr3));
        FuzzerUtils.out.println("fArr2 dArr1 OArr2 = " + Double.doubleToLongBits(FuzzerUtils.checkSum(fArr2)) + "," +
            Double.doubleToLongBits(FuzzerUtils.checkSum(dArr1)) + "," + FuzzerUtils.checkSum(OArr2));
        FuzzerUtils.out.println("O16 O17 O18 = " + FuzzerUtils.checkSum(O16) + "," + FuzzerUtils.checkSum(O17) + "," +
            FuzzerUtils.checkSum(O18));
        FuzzerUtils.out.println("O19 O20 O21 = " + FuzzerUtils.checkSum(O19) + "," + FuzzerUtils.checkSum(O20) + "," +
            FuzzerUtils.checkSum(O21));
        FuzzerUtils.out.println("O22 O23 O24 = " + FuzzerUtils.checkSum(O22) + "," + FuzzerUtils.checkSum(O23) + "," +
            FuzzerUtils.checkSum(O24));
        FuzzerUtils.out.println("O25 O26 O27 = " + FuzzerUtils.checkSum(O25) + "," + FuzzerUtils.checkSum(O26) + "," +
            FuzzerUtils.checkSum(O27));
        FuzzerUtils.out.println("Cls Cls1 Cls2 = " + Cls.instanceCount + "," + Cls1.instanceCount + "," +
            Cls2.instanceCount);

        FuzzerUtils.out.println("Test0056.instanceCount iFld iFld2 = " + Test0056.instanceCount + "," + iFld + "," + iFld2);
        FuzzerUtils.out.println("iFld3 Test0056.lArrFld Test0056.byArrFld = " + iFld3 + "," +
            FuzzerUtils.checkSum(Test0056.lArrFld) + "," + FuzzerUtils.checkSum(Test0056.byArrFld));
        FuzzerUtils.out.println("Cls Cls1 Cls2 = " + Cls.instanceCount + "," + Cls1.instanceCount + "," +
            Cls2.instanceCount);

        FuzzerUtils.out.println("iMeth_check_sum: " + iMeth_check_sum);
        FuzzerUtils.out.println("vMeth_check_sum: " + vMeth_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test0056 _instance = new Test0056();
            for (int i = 0; i < 10; i++ ) {
                try {
                    _instance.mainTest0056(strArr);
                 } catch (OutOfMemoryError ex) {
                    ex.printStackTrace(FuzzerUtils.err);
                    System.exit(1);
                 } catch (Exception ex) {
                    FuzzerUtils.out.println(ex.getClass().getCanonicalName());
                 }
             }
         } catch (Exception ex) {
            FuzzerUtils.out.println(ex.getClass().getCanonicalName());
         }
    }
}
///////////////////////////////////////////////////////////////////////
class Cls extends Test0056 {

    public static final int N = 128;

    public static volatile long instanceCount=-8613184816285463361L;
    public static int iFld1=121;
    public static char cFld=52932;
    public static double dFld=16.105528;
    public static short sFld=-14929;
    public static volatile String strFld="two";
    public static volatile boolean bFld=true;

    public static long iMeth1_check_sum = 0;

    public static int iMeth1() {

        long meth_res = 0;
        int i6=-46852, i7=2, i8=12, i9=9, i10=-236, i11=-5, i12=-7, i13=17390, i14=-183, i15=195, iArr2[]=new int[N],
            iArr3[]=new int[N];
        double d=6.95428, dArr[]=new double[N];
        float f1=43.246F, fArr[]=new float[N];
        byte by=3;
        Object OArr1[]=new Object[45];
        long lArr[]=new long[N];
        String strArr2[]=new String[N];
        Cls1 O2=new Cls1();
        Cls O3=new Cls(), O4=new Cls(), O6=new Cls();
        Cls2 O5=new Cls2();

        FuzzerUtils.init(OArr1, new Cls1());
        FuzzerUtils.init(fArr, -11.637F);
        FuzzerUtils.init(lArr, 240L);
        FuzzerUtils.init(iArr2, 3);
        FuzzerUtils.init(strArr2, "two");
        FuzzerUtils.init(dArr, -81.93956);
        FuzzerUtils.init(iArr3, -13);

        OArr1[(Cls.iFld1 >>> 1) % 45] = O2;
        i6 = 1;
        while (++i6 < 96) {
            Cls.cFld = (char)Cls.instanceCount;
            try {
                Cls.instanceCount += 7714898696633801197L;
                d = 1;
                do {
                    for (i7 = (int) (1); i7 < 1; ++i7) {
                        int i16=-7;
                        if (false) {
                            fArr[i6 - 1] -= (float)d;
                            Cls1.instanceCount -= (long)i6;
                            lArr[(int)(d + 1)] -= (long)i7;
                        } else {
                            Cls1.instanceCount = (long)i8;
                            for (i9 = (int) (1); i9 > 1; i9--) {
                                Cls.dFld = (double)i9;
                                for (i11 = (int) (1); i11 < 1; i11++) {
                                    synchronized (O6) {
                                        f1 += (float)-13743;
                                        OArr1[(i6 >>> 1) % 45] = O4;
                                        Cls.instanceCount |= 43013L;
                                    }
                                    iArr2[(int)(d - 1)] = (int)Cls2.instanceCount;
                                    i13 = i6;
                                    iArr2[i11 - 1] += i12;
                                }
                                f1 = (float)i7;
                                fArr[i6 - 1] -= (float)Cls.sFld;
                                Test0056.instanceCount = (long)i6;
                            }
                            if (true) {
                                Cls.iFld1 &= (int)60889L;
                                i14 = 1;
                                do {
                                    Cls1.instanceCount -= (long)8;
                                    // Resetting String variable to a short value to prevent OOM
                                    Cls.strFld = "hhhh";
                                    Cls.strFld += Cls.strFld;
                                } while ((i14 += 2) < 1);
                                try {
                                    i8 = (i12 % i14);
                                    i12 = (140671829 / i11);
                                    i13 = (Cls.iFld1 / i7);
                                } catch (ArithmeticException a_e) {}
                                iArr2[i6] <<= i8;
                                i12 += 74;
                            } else if (Cls.bFld) {
                                i8 -= i8;
                                f1 -= (float)Cls2.instanceCount;
                                Cls1.instanceCount = (long)7752;
                                switch (i6 + 22) {
                                    case 22:
                                        Cls.instanceCount *= (long)i7;
                                        break;
                                    case 23:
                                        Cls.cFld = (char)Cls.iFld1;
                                        switch ((i6 % 1) + 32) {
                                            case 32:
                                                Cls2.instanceCount = (long)i12;
                                                f1 = (float)i11;
                                                iArr2 = iArr2;
                                                Cls2.instanceCount -= (long)i11;
                                                lArr[(int)(d + 1)] = 141L;
                                                iArr2 = iArr2;
                                                break;
                                            default:
                                                iArr2[i6 + 1] -= i12;
                                        }
                                        break;
                                    case 24:
                                    case 25:
                                        if (i9 != 0) {
                                        }
                                        break;
                                    case 26:
                                    case 27:
                                        Cls2.instanceCount |= (long)i6;
                                        break;
                                    case 28:
                                        i10 -= (int)by;
                                        break;
                                    case 29:
                                        Cls.strFld = Cls.strFld;
                                        break;
                                    case 30:
                                        i10 = 13485;
                                    case 31:
                                        i13 &= i11;
                                    case 32:
                                        O4 = new Cls();
                                        break;
                                    case 33:
                                    case 34:
                                        fArr[i7] = (float)Cls1.instanceCount;
                                        break;
                                    case 35:
                                    case 36:
                                        break;
                                    case 37:
                                        Cls2.instanceCount -= (long)Cls.sFld;
                                        break;
                                    case 38:
                                        Cls.instanceCount = (long)-96;
                                    case 39:
                                        f1 += (float)-61300L;
                                        break;
                                    case 40:
                                        Cls.iFld1 |= i10;
                                    case 41:
                                    case 42:
                                        i15 += (int)Cls1.instanceCount;
                                        break;
                                    case 43:
                                        i8 = (int)-74.16572;
                                        break;
                                    case 44:
                                    case 45:
                                        i12 *= (int)Test0056.instanceCount;
                                        break;
                                    case 46:
                                        Test0056.instanceCount -= Cls2.instanceCount;
                                        break;
                                    case 47:
                                        Cls1.instanceCount = Cls2.instanceCount;
                                        break;
                                    case 48:
                                        Test0056.instanceCount >>= (long)i8;
                                    case 49:
                                        break;
                                    case 50:
                                        strArr2[i7 - 1] = Cls.strFld;
                                        break;
                                    case 51:
                                        break;
                                    case 52:
                                        Cls.iFld1 &= i12;
                                        break;
                                    case 53:
                                        Cls.dFld += (double)-22974;
                                    case 54:
                                        Cls.strFld = Cls.strFld;
                                        break;
                                    case 55:
                                        iArr2[i7 + 1] = Cls.iFld1;
                                    case 56:
                                        if (Cls.bFld) break;
                                        break;
                                    case 57:
                                        Test0056.instanceCount -= (long)f1;
                                        break;
                                    case 58:
                                        i8 = 49942;
                                        break;
                                    case 59:
                                        iArr2[i7] += i9;
                                        break;
                                    case 60:
                                        Cls2.instanceCount += (long)Cls.cFld;
                                        break;
                                    case 61:
                                        fArr[i6] += (float)Cls.iFld1;
                                        break;
                                    case 62:
                                        // Resetting String variable to a short value to prevent OOM
                                        Cls.strFld = "hhhh";
                                        Cls.strFld += Cls.strFld;
                                        break;
                                    case 63:
                                        Cls.instanceCount *= (long)f1;
                                        break;
                                    case 64:
                                        i13 += i13;
                                        break;
                                    case 65:
                                        i16 = (int)by;
                                        break;
                                    case 66:
                                        try {
                                            i15 = (i12 / -45021);
                                            i8 = (i12 / 24481);
                                            i13 = (i6 / i10);
                                        } catch (ArithmeticException a_e) {}
                                    case 67:
                                    case 68:
                                        Cls.sFld += (short)23;
                                        break;
                                    case 69:
                                        iArr2 = iArr2;
                                        break;
                                    case 70:
                                        i8 *= 75;
                                    case 71:
                                        Cls.iFld1 <<= -180;
                                        break;
                                    case 72:
                                        Test0056.instanceCount = -12089L;
                                        break;
                                    case 73:
                                        Cls.strFld = Cls.strFld;
                                    case 74:
                                        lArr[i7 - 1] = Test0056.instanceCount;
                                    case 75:
                                        by >>= (byte)i14;
                                        break;
                                    case 76:
                                        i16 = (int)Cls2.instanceCount;
                                    case 77:
                                        i15 -= Cls.iFld1;
                                        break;
                                    case 78:
                                        dArr[i7] -= (double)Cls.instanceCount;
                                    case 79:
                                        if (Cls.bFld) continue;
                                        break;
                                    case 80:
                                    case 81:
                                    case 82:
                                        iArr2[i7] = i15;
                                        break;
                                    case 83:
                                        try {
                                            Cls.iFld1 = (213 / i13);
                                            iArr2[i6] = (iArr3[i6] % i6);
                                            i12 = (i6 % 133);
                                        } catch (ArithmeticException a_e) {}
                                        break;
                                    case 84:
                                    case 85:
                                        break;
                                    case 86:
                                        Test0056.instanceCount += (long)by;
                                        break;
                                    case 87:
                                        break;
                                    case 88:
                                        // Resetting String variable to a short value to prevent OOM
                                        Cls.strFld = "";
                                        Cls.strFld += Cls.strFld;
                                        break;
                                    case 89:
                                        break;
                                    case 90:
                                        Test0056.instanceCount = (long)i9;
                                        break;
                                    case 91:
                                        if (true) continue;
                                        break;
                                    default:
                                        i10 = i10;
                                }
                            } else if (true) {
                                i15 += (int)2.200F;
                            }
                        }
                    }
                } while (++d < 16);
            }
            catch (UserDefinedExceptionTest0056 exc9) {
                Cls.dFld = (double)22251L;
            }
        }
        meth_res = i6 + Double.doubleToLongBits(d) + i7 + i8 + i9 + i10 + i11 + i12 + i13 + Float.floatToIntBits(f1) +
            i14 + i15 + by + FuzzerUtils.checkSum(OArr1) + Double.doubleToLongBits(FuzzerUtils.checkSum(fArr)) +
            FuzzerUtils.checkSum(lArr) + FuzzerUtils.checkSum(iArr2) + FuzzerUtils.checkSum(strArr2) +
            Double.doubleToLongBits(FuzzerUtils.checkSum(dArr)) + FuzzerUtils.checkSum(iArr3) +
            FuzzerUtils.checkSum(O2) + FuzzerUtils.checkSum(O3) + FuzzerUtils.checkSum(O4) + FuzzerUtils.checkSum(O6) +
            FuzzerUtils.checkSum(O5);
        iMeth1_check_sum += meth_res;
        return (int)meth_res;
    }

}
///////////////////////////////////////////////////////////////////////
class Cls1 extends Test0056 {

    public static final int N = 128;

    public static long instanceCount=79L;

}
///////////////////////////////////////////////////////////////////////
class Cls2 {

    public static final int N = 128;

    public static volatile long instanceCount=106L;

}
///////////////////////////////////////////////////////////////////////
class UserDefinedExceptionTest0056 extends RuntimeException {
    public int field;
    public UserDefinedExceptionTest0056() { super("UserDefinedExceptionTest0056"); }
    public UserDefinedExceptionTest0056(String mess) { super(mess); }
}

//DEBUG  Test0056 ->  Test0056 Cls Cls1 iMeth1 iMeth vMeth mainTest0056
//DEBUG  main ->  main
//DEBUG  mainTest0056 ->  mainTest0056
//DEBUG  vMeth ->  vMeth mainTest0056
//DEBUG  iMeth ->  iMeth vMeth mainTest0056
//DEBUG  Cls ->  Cls iMeth1 iMeth vMeth mainTest0056
//DEBUG  Cls1 ->  Cls1 iMeth vMeth mainTest0056 iMeth1
//DEBUG  Cls2 ->  Cls2 iMeth vMeth mainTest0056 iMeth1
//DEBUG  iMeth1 ->  iMeth1 iMeth vMeth mainTest0056
//DEBUG  Depth = 5
//DEBUG  Classes = 4
//DEBUG  static objects = {}
